duckduckgo/duckduckgo-privacy-extension

shared/data/tracker_lists/trackersWithParentCompany.json
shared/js/background.js
shared/js/https.js
shared/js/indexed-db.js
shared/js/settings.js
shared/js/utils.js
test/tests/https.js

**Reviewer:**
@jdorweiler @russellholt 
This PR adds an additional step to onBeforeRequest handler and the https module for Chrome, which does not obey asynchronous request resolvers. To verify this works, run the unit tests in both Chrome and Firefox, and in Chrome you'll want to double-verify that the upgrade was obeyed by 
looking at network tab. See attached screenshot for desired behavior.
Unit tests added for both cases (synchronous and asynchronous).

Port to Chrome: Synchronous https lookups

---

shared/js/ui/views/top-blocked-truncated.es6.js

Fix for Firefox flashing an empty state for the top blocked networks in the main popup.
2. Visit heavy tracker sites, like alternet.org or msnbc.com
3. Open the popup and make sure the top blocked part doesn't jump or flash empty states
4. Reset global stats and repeat

Set timeout for rerendering the top blocked pills

---

shared/js/ui/templates/shared/grade-scorecard-reasons.es6.js
shared/js/ui/templates/shared/tracker-networks-text.es6.js
shared/js/ui/templates/site.es6.js
shared/js/ui/templates/tracker-networks.es6.js
shared/js/ui/views/tracker-networks.es6.js

Small PR as a followup to #14: addressing the case when only 1 tracker is detected.
Text should say "Tracker Network" instead of "Tracker Networks" in that case.
2. Visit a site with one tracker, like https://submit.pandora.com/
3. There should be one tracker, and singular should be used in the main popup, in the tracker networks subview, and in the grade scorecard
4. Visit other sites with more trackers and make sure plural is used in that case

Use singular when there's only 1 tracker

---

Gruntfile.js

**Reviewer:**
@jdorweiler 
I missed this in #40 and it's preventing abp.js from generating correctly for Safari. Removing this line seems to fix it.

Remove safari abp preprocessing from Gruntfile

---

shared/js/ui/templates/privacy-practices.es6.js

Add missing punctuation in the privacy practices subview, for when the site has not been reviewed
2. Visit website with mixed privacy practices like github.com
3. The text in the privacy practices subview should end with a period after "review"

Missing period in privacy practices subview

---

shared/scss/_mixins.scss
shared/scss/views/_hero.scss

Adding fixed height and line height to prevent the subtitle from looking like it jumps down, whenever we enhancing a site
2. Test on sites with trackers such as msnbc.com or youtube.com - open the popup immediately while the page is still loading
3. The text should switch seamlessly from "calculating" to "privacy grade" to "enhanced from ... to ..." without jumping

Fix hero subtitle jumping in main popup

---

shared/js/companies.js

Followup from #11 - now sanity check and update old data to avoid showing that double header in the top blocked subview.
1. Uncomment line 123 in shared/js/companies.js (adds "twitter" manually to the data), add console logs to show the storageData where preferred
2. Build and reload extension
3. The "twitter" property should be gone

Sanity check data before adding companies from storage

---

shared/js/ui/templates/shared/hero.es6.js
shared/js/ui/templates/site.es6.js
shared/scss/base/base.scss
shared/scss/views/_privacy-practices.scss

Hero background color in the subviews should be gray, like in the main popup view.
I also had to update the neutral gray background color and tweak privacy practices styles to avoid weird differently colored lines from showing in the subviews.
2. Visit a site, open popup
3. Click into the subviews and make sure the hero header has the same gray color as the main popup view

Update hero header background color in the subviews

---

browsers/duckduckgo.safariextension/js/background.js
browsers/duckduckgo.safariextension/js/content-script.js

**Reviewer:**
@jdorweiler @dharb @laurengarcia 
Implements surrogate code injection for Safari similar to Chrome/FF.
1. Load jquery.com
2. Open up the console for jquery.com (not the extension page).
3. Should see message in the console `DDG BLOCKING AND USING SURROGATE https://google-analytics.com/ga.js`.
4. If you type `window._gaq` it should be the defined objection/functions from the surrogate code.

Safari surrogates

---

shared/scss/popup.scss

The placeholder was too short and it shows through because of 0.5 opacity when popup is disabled.
2. Open popup in the extension interface page (or any non-website page)
3. Popup should be disabled and look normal

Fix line in toggle on disabled state

---

shared/js/atb.js

**Reviewer:**
The old chrome extension store atb values in localStorage. We need to move these over to settings in-order to keep atb working.
You can setup different test conditions through the extension console:
1. User with old extension who is upgrading 
```
settings.updateSetting('atb', '')
localStorage['atb'] = 'v1-1'
```
Reload the extension and do a search. You should see that 'v1-1' is appended to the url
2. User who already has the new extension and doesn't need to migrate
```
settings.updateSetting('atb', 'v2-1')
localStorage['atb'] = 'v1-1'
```
Reload the extension and do a search. You should see that 'v2-1' is appended to the url
3. User who is installing from the chrome store should have atb generated automatically
```
settings.updateSetting('atb', '')
localStorage['atb'] = …
```

migrate atb

---

shared/js/ui/views/site.es6.js

**Reviewer:**
The popup recently started re-rendering in the disabled state way too much due to `updateTabData` events from the background process. Is/was causing a memory leak for new tabs (disabled state). I've fixed the re-rendering issue, but think I might be only addressing the symptom here, but the memory leak seems to have gone away with this fix. 
Will keep an eye on this.

fix re-renders in popup disabled state

---

shared/js/https.js

**Reviewer:**
@jdorweiler @nilnilnil 
Adds `&b=safari` to https url request for safari so that we can serve a different list to them if we need to.
In Safari, you should see the request in the console after a fresh install, where it's using the new url.
In Chrome/FF it should use the same url as before.

Add querystring param to https list request for safari

---

browsers/duckduckgo.safariextension/js/background.js
browsers/duckduckgo.safariextension/js/tab.js
browsers/duckduckgo.safariextension/js/tabManager.js

**Reviewer:**
@jdorweiler @laurengarcia 
https://app.asana.com/0/72649045549333/524358648218923
adobe.com --> should upgrade as usual
businessinsider.com --> shouldn't get stuck in redirect loop, should just fallback to using http

prevent https redirect loops in safari

---

shared/js/ui/templates/shared/grade-scorecard-reasons.es6.js

Previously we were specifically avoiding showing unknown privacy practices in the grade scorecard.
This change shows them with the red "x" icon.
1.  Build and reload extension
2. Visit site with unknown privacy practices (eg http://www.azfamily.com/)
3. Main popup should sow "unknown privacy practices"
4. Grade scorecard should show a line for "unknown privacy practices" as well, with a red x icon
5. Other privacy practices ratings are displayed correctly as well, depending on the site

Show unknown privacy practices in the grade scorecard

---

shared/js/ui/templates/shared/tracker-network-icon.es6.js
shared/js/ui/templates/site.es6.js
shared/js/ui/templates/tracker-networks.es6.js
shared/js/ui/views/tracker-networks.es6.js

Tracker network icon should be green when 0 found and site whitelisted, even though the grade is D.
Before we only looked at the grade to make that decision.
2. Go to sites like google.com
3. Whitelist the site - the trackers line and subview should show the green icon, because of the 0 trackers found
4. Other cases should work as usual: major trackers found when whitelisted - red icon; not whitelisted or whitelisted with no major trackers, green icon

Show green icon for tracker networks when 0 found and site whitelisted

---

shared/js/background.js
shared/js/tab.js
shared/js/tabManager.js

**CC:** @bsstoner @laurengarcia 
This adds a couple of extra methods to deal with HTTPS redirect loops.
Specifically it deals with two redirect loops that we found, one on http://store.steampowered.com/ (which only happened in FF) and one at http://raisingchildren.net.au/articles/safe_water_temperature.html (both Chrome and FF).
See descriptions inline for more info.
Visit both http://raisingchildren.net.au/articles/safe_water_temperature.html and http://store.steampowered.com/ on both Chrome and FF, there should be no HTTPS redirect loops.
Note, we removed the Steam Store rule from our HTTPS ruleset. To fudge it and pretend it's still there, you can add something like `if (reqUrl === 'http://store.steampowered.com/') { return 'https://store.steampowered.com/' }` …

Harden HTTPS redirect loop detection

---

shared/js/background.js

**CC:** @jagtalon 
As @jagtalon pointed out, no need to open /app if the user installs the extension from there
1. Remove current extension
2. Build and load from this branch
3. Post install page should open as usual
4. Now change `domain` in background.js to be the same as `postInstallUrl`
5. Repeat from step 1 - this time the post install page should NOT open
6. Feel free to `console.log` the domain and inside the if statement for further verification

Don't open post install page if extension is installed from there

---

shared/scss/views/_hero.scss

We used to break words and wrap whitespace, which leads to inconsistent behaviour for long URLs.
This change makes sure we always use ellipsis on them.
2. Load a page that breaks  the hero title in 2 lines, like https://user-images.githubusercontent.com/83453/33233089-a915a66a-d1c5-11e7-9d8c-15ec5e32351b.png
3. Text should now have ellipsis instead
4. Normal length URLs are unaffected

Always use ellipsis in the hero title when too long

---

scripts/tosdr.js

**CC:** @russellholt 
Some sites in tosdr are missing the url field (see https://github.com/tosdr/tosdr.org/blob/master/services/kolabnow.json for example), yet have multiple items in the urls field. This allows us to take the first item from the urls field in place of the url field in this case.
1. pull this down and run `grunt execute:tosdr --browser=chrome --type=dev`, then check shared/data/tosdr.js and search for 'kolab'. there should now be an entry.

allow sites with missing url field to use first related url

---

browsers/duckduckgo.safariextension/Info.plist
browsers/duckduckgo.safariextension/js/background.js

**Reviewer:**
Some users are reporting that the post install page is opening every time they open Safari. I can't repeat it but checking to see that there is an existing DDG page or safari gallery page should fix it.

only show install page on ddg or gallery

---

shared/js/background.js

**CC:** @bbraithwaite 
Remove www from postinstall page URL to avoid unnecessary redirect
1. Remove current extension
2. Build and load from branch
3. Postinstall page should open in a new tab

Remove unnecessary "www" in postinstall URL

---

shared/js/ui/models/site.es6.js
shared/js/ui/templates/shared/grade-scorecard-reasons.es6.js
shared/js/ui/templates/shared/tracker-network-icon.es6.js
shared/js/ui/templates/shared/tracker-networks-text.es6.js
shared/js/ui/templates/site.es6.js
shared/js/ui/templates/tracker-networks.es6.js
shared/js/ui/views/tracker-networks.es6.js

**Reviewer:**
@MariagraziaAlastra 
This was technical debt that I forgot about.
This PR disambiguates two site model properties that were poorly named and had changed over time.
`this.majorTrackersCount` -> `this.majorTrackerNetworksCount`
`this.totalTrackersCount -> totalTrackerNetworksCount`
Build this branch, visit sites and verify that counts are correct and there are no errors in popup console.

UI site model: disambiguate site properties

---

scripts/importers/companyList.js

**Reviewer:** @russellholt 
By mapping 'Amazon.com' to 'Amazon', we're not matching amazon requests with their entity data here: https://duckduckgo.com/contentblocking.js?l=entitylist . This is blocking first party requests to other amazon domains on the amazon website.
1. reload extension
2. visit amazon.fr
3. type into the search bar on the page. Autocomplete should appear. (the reason this is the case is due to autocomplete requests on amazon.fr going through amazon.co.uk)

Stop mapping Amazon.com to Amazon

---

shared/js/ui/templates/shared/email-feedback-footer.es6.js

I was running the linter and noticed an error on the email-feedback-footer. Nothing is actually broken, but it complains saying "chrome" is an undefined variable. 
Prefixing with "window" solves it.
2. Click on feedback
3. Footer should look as in #150

Fix linter error on feedback template

---

Makefile
package.json

**Reviewer:**
Firefox is getting rid of the beta channel. I'm adding a beta-firefox target to package.json that will build us a zip file. We can upload the zip file to an unlisted beta extension for testing. The id needs to be removed from the manifest to upload it to the unlisted extension.
1. `npm run beta-firefox`
2. You should have a zip file in `build/firefox/release/web-ext-artifacts`

beta firefox build target

---

shared/js/ui/base/model.es6.js
shared/js/ui/models/whitelist.es6.js

In https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/153 we noticed that the model's own properties were accidentally getting frozen (by [this line](https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/7d0afb1dbdd0430e30d92f1228d654d28364c7d4/shared/js/ui/base/store.es6.js#L60)) because they were being passed by reference.
This PR makes sure anything passed to the store is deep cloned so that problem doesn't happen. It also removes a hack we had to add in the whitelist model.
1. Try adding and removing some items in the whitelist - it should work without any errors
2. Other models should also work fine.

Prevent model from accidentally freezing its own properties

---

shared/js/ui/templates/site.es6.js
shared/js/ui/views/site.es6.js
shared/scss/popup.scss

Adding transition to the toggle text:
- "Added to whitelist" moves down by 16px while transitioning from 0 to 100 opacity
- "Site Privacy Protection" also moves down by 16px, transitioning from 100 to 0 opacity
- Popup remains visible for 2.5 seconds before reloading the page
2. Go on a site and click on the toggle button to whitelist it
3. A css transition, as described above, should show up
4. Tab should reload and the popup should show the regular whitelisted UI
5. Clicking again on the toggle to remove from whitelist should reload the tab immediately

Toggle text transition when site is whitelisted

---

shared/js/ui/views/site.es6.js

**Reviewer:** @andrey-p / @dharb 
Closing the window before reloading the tab somehow breaks reloading on FF.
Inverting the order (like it was before #158) fixes the issue.
1. Build and reload extension in FF
2. Go on a site and click on the toggle button to whitelist it. You should see a CSS transition on the toggle:
3. "Added to whitelist" text moves down by 16px while transitioning from 0 to 1 opacity
4. "Site Privacy Protection" text also moves down by 16px, transitioning from 1 to 0 opacity
5. Popup remains visible for 2.5 seconds before reloading the page
6. Tab should reload and the popup should show the regular whitelisted UI
7. Clicking again on the toggle to remove from whitelist should reload the tab immediately

Fix FF not reloading after whitelisting

---

shared/scss/popup.scss

On Windows FF, opacity transition on the "Added to whitelist" container element produces an unexpected black rectangle between icon and text when showing the animation and switching from 0 to 1 opacity.
Applying the transition to each child element (text and icon) individually seems to fix the problem.
Tested using virtual environment.
1. Build and reload extension on Windows FF
2. Try to whitelist a site via the main popup toggle
3. The animation should show with no glitches
4. Other browsers and platforms also work as expected

Fix black rectangle glitch on Windows FF

---

Makefile
browsers/chrome/manifest.json
browsers/firefox/manifest.json
shared/js/background/abp-lists.es6.js
shared/js/background/background.es6.js

**Reviewer:**
I ran into an problem where the onInstall handler isn't registered before the install event has fired. It's probably related to all the background files being browserifyed and the onInstall not being registered until near the end of the file. Adding it to abp-preprocess moves it up and seems to fix the problem. 
I was also getting some failing tests when build the beta firefox version about not finding the manifest files. The location seem to be relative to the new background.js file so I moved content-scripts to public/js. 
1. Install from ddh6. version 2018.3.15.3
2. post install page should open
3. you should have atb values in the url when you do a search.

move oninstall and content scripts

---

shared/js/background/https.es6.js

This fixes a couple of issues with HTTPS redirection that make it slower for cases where we can't redirect. See inline for more info.
Redirects should still work as before.
1. Visit e.g. http://theguardian.com
2. You should be taken to the HTTPS version
3. The popup should say "enforced encryption"

HTTPS fixes

---

shared/js/background/atb.es6.js

**CC:** @bbraithwaite 
Fixes a couple of incorrect paths for injected assets.
Testing this is pretty hairy since it's very closely tied to our install flow. The closest I got to replicating the issue is:
1. Open any DDG page (the extension install success page will do)
2. Reload the extension in the extensions window (about:debugging#addons on FF, chrome://extensions on Chrome)
3. There should be no errors mentioning `lastError` in the console.

Fix injected paths

---

shared/js/ui/models/site.es6.js
shared/js/ui/templates/shared/grade-scorecard-reasons.es6.js

**Reviewer:** @jdorweiler / @andrey-p 
Fix the following edge case on Google.com:
Now that we have unblocked trackers in the count, we have to be careful what we use to count major tracker networks.
It looks like the grade scorecard was using a different count for general trackers blocked/found, as well.
We're sticking to only showing the blocked trackers and tracker networks count unless the site is whitelisted, so I fixed accordingly.
2. Go to google.com
3. Site is graded D, 0 trackers found (since we can't block anything first party)
4. Go to the grade scorecard: it should say 0 trackers found and 0 major tracker networks found, both with green icons
5. Check the scorecard for other non-major tracker networks sites as well

Fix 0 found, 1 major blocked edge case

---

Gruntfile.js
package.json

**Reviewer:** self (trivial tooling change)
Adds `npm run test-debug`.
You'll see a URL in the console. You can open that, and the tests will run in your browser.
If there's an error, you can switch on "pause on uncaught errors" to debug.
You can also add `debugger` in your code to start debugging.

Add way to debug tests

---

Gruntfile.js
shared/js/ui/models/whitelist.es6.js
unit-test/ui/models/whitelist.es6.js

Update validation to allow localhost to be added to whitelist on settings page.
1. On the options page, add localhost to whitelist. Now visit a localhost address and open the popup. Privacy protection should be turned off.
2. Visit options page again and remove localhost from the whitelist. Privacy protection should be back on for localhost.
3. Add other urls both valid and invalid to the whitelist. Check that the validation still works properly.
4. `npm run test`

Allow localhost to be added to white list

---

shared/js/ui/templates/top-blocked-truncated-list-items.es6.js

We check whether a tracker is part of a major network in order to know when to show the generic pill.
Oath is part of the major networks but doesn't have an icon yet. Added a special case until we can add the icon for it.
1. (optional) Mock Oath being a top tracker network in the code
2. Build and reload extension
3. If you didn't do step 1, load 30 sites of which most have third party Oath trackers
4. Top blocked pills should show up - Oath will have the generic icon

Fix empty icon in top blocked pills

---

shared/js/background/atb.es6.js
shared/js/background/chrome-events.es6.js
shared/js/background/safari-events.es6.js

Add ATB params to post-install page
1. Uninstall extension
2. Build and reinstall 
3. Postinstall page should open and the URL should look like https://duckduckgo.com/app?post=1&atb=v113-1 
4. If installing from ddh6, the variant should be there as well, eg https://duckduckgo.com/app?post=1&atb=v113-1_f

Add ATB to postinstall page

---

shared/js/background/safari-events.es6.js

750 ms are not sufficient in Safari to retrieve ATB after install, it needs at least 3 seconds.
Followup from #206 
1. Upload to ddh6
2. Uninstall and reinstall extension 
3. post install page should open in a new tab, with URL like https://duckduckgo.com/app?post=1&atb=v113-1_f

Safari needs a longer timeout after install

---

shared/js/ui/models/whitelist.es6.js
unit-test/ui/models/whitelist.es6.js

**CC:** @andrey-p 
Following up from #199, this also allows to whitelist the localhost when a port is specified (currently, strings like 'localhost:8080' are not considered valid).
2. Go to the options page
3. Try whitelisting 'localhost', 'localhost:8080' (or use any port) - both should be valid
4. Things like 'localhost:asdlajshdkja' should still be invalid
5. Try whitelisting other domains: they should get validated as usual
6. After whitelisting a domain, navigate to it and make sure it's actually whitelisted
7. Play around with adding and removing domains using the toggle and the options page to make sure functionality is intact

When a port is specified for localhost, it should still be accepted as valid

---

shared/js/background/safari-wrapper.es6.js

Revert one of the changes from #212, and add `tabManager` as a global for that file so linting doesn't complain.
I'm gonna look at this in more detail tomorrow.

Temporarily use global tabManager for safari-wrapper

---

shared/js/background/safari-events.es6.js
shared/js/background/safari-wrapper.es6.js
shared/js/background/tab-manager.es6.js
shared/js/ui/base/chrome-ui-wrapper.es6.js
shared/js/ui/base/safari-ui-wrapper.es6.js
shared/js/ui/models/privacy-options.es6.js
shared/js/ui/models/whitelist.es6.js
shared/js/ui/views/site.es6.js

**CC:** @MariagraziaAlastra 
This drops the use of globals on `contentWindow` for Safari. See inline comments for more info.
1. Make Safari passes information correctly between the background tab and the popup:
- number of trackers blocked updates
- top trackers gets updated and reset correctly
- whitelisting via the toggle works
- grade is shown correctly
2. Make sure Safari passes information correctly between the background tab and the options page:
- the embedded tweet blocking toggle should work
- you can manually add / remove sites to the whitelist, and that gets updated in the popup
3. When you whitelist a site via the popup in Chrome/FF, the popup should close and the page should refresh.

Tidy up globals in Safari

---

package-lock.json
package.json
shared/js/background/chrome-events.es6.js
shared/js/background/classes/https-redirects.es6.js
shared/js/background/classes/tab.es6.js
shared/js/background/redirect.es6.js
shared/js/background/tab-manager.es6.js
unit-test/background/classes/https-redirects.es6.js

Fixes redirect loop protection in the extension so it doesn't count any redirects that we haven't initiated.
I also took the opportunity to tidy the implementation up a bit.
To test sites that were breaking due to the redirect loop counting:
1. Go to https://fishing-peche.dfo-mpo.gc.ca/
2. Press "English" (page loading shouldn't fail)
3. Go to https://www.canada.ca/en/revenue-agency/services/e-services/e-services-individuals/account-individuals.html
4. Press "Sign-In Partner Login / Register" (page loading shouldn't fail)
To test a site with a redirect loop problem (from https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/83):
1. Fudge the https.js so it upgrades this broken site, e.g. add `if (host.indexOf("raisingchildren") > -1) { …

Fix redirect counting

---

shared/js/background/trackers.es6.js

If the entityList endpoint is unresponsive when the extension is loaded, the entityList variable remains undefined. The isTracker function later attempts to check request entities against an undefined variable, which throws errors and breaks the extension. This just instantiates entityList as an empty object, which fixes this.
1. Change the entityList endpoint in constants.js to a url that doesn't respond.
2. Compile and load extension in browser.
3. Visit a site with trackers. Check popup to see that trackers were found. Check extension console to see that no errors are thrown.

Set default value for entityList variable

---

shared/js/ui/base/safari-ui-wrapper.es6.js

Fixes two issues with how Safari handles feedback opening:
- popup doesn't hide when pressing "report broken site" in the popup
- feedback doesn't open from the options page
1. Open feedback from the popup - popup should hide, and feedback page should open
2. Open feedback from the options page - feedback page should open

Fix feedback opening in Safari

---

shared/js/background/chrome-events.es6.js
shared/js/background/safari-events.es6.js
shared/js/ui/base/chrome-ui-wrapper.es6.js
shared/js/ui/base/safari-ui-wrapper.es6.js
shared/js/ui/models/feedback-form.es6.js
shared/js/ui/models/mixins/parse-user-agent.es6.js
shared/js/ui/pages/feedback.es6.js
unit-test/ui/models/feedback-form.es6.js

**CC:** @MariagraziaAlastra 
**Depends on:** Will cause a conflict with #227, I'll resolve when either gets merged
This PR does two things:
1. Fixes settings (specifically ATB params) not being retrieved correctly from extension pages on Safari
2. Starts retrieving extension version via `fetch` and the background process, since extension pages don't have access to the version in Safari
1. Add e.g. `return console.log(this)` where the feedback form is being submitted: https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/d0046ef7723d2a4974d890155ecdcd096706fd5e/shared/js/ui/models/feedback-form.es6.js#L35
2. Go to the feedback page in both Safari and Chrome with console log open
3. Press "submit" and verify that both ATB and extension version are set …

Safari: Fix how ATB and version are passed to extension pages

---

shared/js/content-scripts/element-hiding.js

cc: @jdorweiler 
It appears that certain libraries, such as cloudflare's rocketloader, hijack the standard document.onreadystatechange event and change what it does. This throws permission errors when we attempt to call it in a content script:
This PR moves away from using the onreadystatechange event, replacing it with a standard event listener. Strangely, this only seems to be an issue in Firefox.
1. Visit a site affected by issue in Firefox. One such site is recipetamer.com, another is redsecurity.info.
2. Check console to see that no permission errors are being thrown.
3. Ensure that element hiding still works properly by visiting a site where it's currently active (yahoo.com for one).

avoid using onreadystatechange, since libraries may hijack it.

---

shared/js/background/redirect.es6.js
shared/js/background/safari-events.es6.js
shared/js/ui/base/chrome-ui-wrapper.es6.js
shared/js/ui/base/safari-ui-wrapper.es6.js
shared/js/ui/models/search.es6.js

**CC:** @jdorweiler @jkv 
Makes sure the ATB param is added correctly when searching through the popup.
1. Search via the popup search box on FF, Chrome, Safari
2. The search should work correctly.
3. The ATB param should be correctly added.

Fix ATB param on Safari popup search

---

shared/js/background/atb.es6.js
unit-test/background/atb.es6.js

**CC:** @zachthompson @jkv 
Adds handling for clients with missing ATB params.
Basically:
1. When we detect a falsy ATB param, add `e=1` to query string.
2. After that, set ATB to v1-1, which clients can't get into normally.
3. Next time the client searches, ATB will be present so `e=1` shouldn't appear.
Here's how to manually test:
1. Install extension
2. Via the console, run `dbg.settings.removeSetting('atb')`
3. Run a search (you should see the set_atb call in the console with e=1)
4. Run a search again (atb param added to the search should be v1-1)

Handle clients with empty ATB

---

shared/js/background/classes/https-redirects.es6.js
unit-test/background/classes/https-redirects.es6.js

**CC:** @zachthompson @nilnilnil 
Fire anonymous pixel on unique (per tab) mainframe HTTPS downgrades.
2. Visit sites that won't upgrade like http://bl.ocks.org/billdwhite/36d15bc6126e6f6365d0 
3. Check the 'edh' pixel fires
4. Run unit tests

Anonymous alert when HTTPS upgrades fail

---

shared/js/background/classes/score.es6.js
shared/js/background/trackers.es6.js
shared/js/background/utils.es6.js
unit-test/background/classes/score.es6.js
unit-test/background/utils.es6.js

Update find parent. Instead of splitting the domain before calling the function, it will do it for you now.
1. npm test
2. Check sites that have first party trackers like yahoo.com. You should see unblocked first party trackers in the tracker detail subview.

Split domains in findParent

---

shared/js/background/load.es6.js

We didn't have a check in place in load.js to verify if the xhr response is empty, before attempting to parse it. This PR fixed it.
2. try setting xhr data to valid JSON or empty response
3. In the console, set breakpoints on the modified lines and see how the xhr response is handled

Validate JSON data coming from endpoints

---

shared/js/background/chrome-events.es6.js
shared/js/background/https.es6.js
unit-test/background/https.es6.js
unit-test/data/httpsRequests.json

cc: @jdorweiler @zachthompson @russellholt 
When a site is loaded over https, all active mixed content is blocked at the browser level before we have a chance to upgrade the requests to https. Mixed passive content is often blocked for several reasons (block-mixed-content header/meta tag, user agent). This PR fixes many sites broken due to improperly set up https websites that contain http resource links by appending the 'upgrade-insecure-requests' response header to the document.
1. npm run test
2. visit site with mixed content, such as https://www.protrails.com/trail/744/aspen-snowmass-4-pass-loop. The mixed content should now load over https.

Fixed mixed content issues by appending 'upgrade-insecure-request' header

---

shared/js/background/utils.es6.js

For whatever reason it appears that tldjs.parse(url) in extractHostFromUrl is returning an urlObj without a hostname. I would assume that this is due to tldjs choking on some kind of url, but I haven't been able to reproduce it so I'm not 100% sure. I just saw this error cropping up in the new chrome extension error page:
This just makes sure that hostname is defined so no errors are thrown.

Set hostname to empty string if it's null so extractHostFromUrl returns something

---

shared/js/background/chrome-events.es6.js
shared/js/background/trackers.es6.js
shared/js/background/utils.es6.js
unit-test/background/utils.es6.js

Beacon and ping type requests are slipping through currently, because they're not included in the list of resource types we recognize and block.
However, adding "beacon" to the list errors on Chrome, while "ping" doesn't seem to block anything in Firefox.
With this change we'll add either beacon or ping on extension install/update depending on the browser.
Also add "beacon" as a reason for blocking these requests.
2. check both firefox and chrome.
3. visit a site that uses beacons (google, youtube, amazon etc) and disable privacy protection
4. in the network tab you should be able to see the beacons loading (usually you can filter by "analytics" to make them show up)
5. enable privacy protection; now the beacon requests should be blocked …

Block requests with type "beacon" or "ping"

---

shared/js/background/classes/https-redirects.es6.js
shared/js/background/redirect.es6.js
unit-test/background/classes/https-redirects.es6.js

**CC:** @nilnilnil @jdorweiler 
It's currently possible for redirect protection to be triggered manually, e.g. if a user presses enter multiple times on the URL bar while it's loading.
This PR adds a limit of 7 hits per main frame URL within 3s. This should be pretty easy for a redirect loop to hit, not so much for a human being.
1. Open a site which is currently vulnerable to HTTPS redirect loops (some NSFW Tumblr ones apparently?) and verify the redirect protection still does its thing
2. Try opening the same HTTP link manually, end verify that redirect protection doesn't trigger (e.g. no `ehd` pixel with error code `13`.)

Make sure redirect protection doesn't trigger accidentally

---

shared/data/defaultSettings.js
shared/js/background/chrome-events.es6.js
shared/js/background/https.es6.js
shared/js/background/pixel.es6.js
unit-test/background/pixel.es6.js

**Reviewer:**
Count the number of attempted and failed https upgrades.
1. When first loading the extension both counts should be zero
```
window.dbg.settings.getSetting('attemptedUpgrades')
window.dbg.settings.getSetting('failedUpgrades')
```
2. Visit some http sites and the attempted total should increment each time.
```
window.dbg.settings.getSetting('attemptedUpgrades')
```
3. Clear the https whitelist and visit some broken https sites `failedUpgrades` should increment.
```
window.dbg.https.whitelist = []
window.dbg.settings.getSetting('failedUpgrades')
```
4. Reload the extension. You should see a network request with the successes and failure parameters go out. 
5. The totals should reset to zero.

Send https upgrade failure total

---

shared/js/background/https.es6.js
unit-test/data/httpsRequests.json

**CC:** @jdorweiler @MariagraziaAlastra 
It turns out there's a potential redirect loop caused by adding the `upgrade-insecure-requests` header to webpages. When a site loads over https but includes js that rewrites the site url to http, the `upgrade-insecure-requests` header on the main document causes that request to be upgraded to https. It's definitely a rare edge case, but this fixes it anyway. I also added a test for this specific case.
1. rebuild extension
2. visit site that does a silly http rewrite, like https://slither.io (we don't even upgrade this site anyway, in order to trigger the redirect loop you have to manually type https in the address bar)
3. site should not get stuck in redirect loop. give it a min to load, the site is quite slow.

catch potential https redirect loop caused by upgrade-insecure-requests header

---

shared/js/background/chrome-events.es6.js
shared/js/background/redirect.es6.js
shared/js/background/utils.es6.js

#311 Added the beacon or ping type to the list of blockable requests, but Firefox sometimes gets mistaken as Chrome and we add "ping" (which FF claims is supported but doesn't do anything) instead of "beacon" to the list.
This happens because Chrome is the default browser name we use, in case getBrowserInfo() is not available. However, sometimes it takes a while for it to be available on FF and we set the request types for the onBeforeRequest handler too early.
This PR fixes that by double checking the UA string before returning the browser name.
2. Go on sites with beacons like github.com
3. Check on the network tab and in the background that beacon requests (in github's case, it's google analytics) are blocked
4. Open the popup: all …

Fix adding 'beacon' as blockable request type on FF

---

shared/js/background/classes/site.es6.js

**CC:** @andrey-p @jdorweiler 
We've received feedback a few times from users who have run into issues with the extension while doing local development, and there's no reason to keep privacy protection on for local addresses.
We were already not grading localhost domains, as long as the address was written in the form of http://localhost:... etc
This PR disables grading when localhost is written as 127.0.0.1, and for non routable meta-addresses (0.0.0.0 which is also local): they'll be treated as a special page.
2. To see localhost, you can just use Python's SimpleHTTPServer, eg: `python -m SimpleHTTPServer 8000`
2. Visit localhost in the form of eg http://localhost:8000
3. Open the popup - the grading should be disabled and the domain …

Disable privacy protection on localhost

---

shared/js/background/classes/site.es6.js

The temp whitelist used to only apply to main domains, which means if we attempt fixing a broken site by adding it to the whitelist, it won't work for any of its subdomains.
This PR fixes that.
2. navigate to suntrust.com - the site should be whitelisted and nothing should be blocked
3. try logging in with random credentials - now you'll be redirected to a subdomain
4. at this point, the site should still be whitelisted
5. try other sites in the temp whitelist: https://github.com/duckduckgo/content-blocking-whitelist/blob/master/trackers-whitelist-temporary.txt
6. check normal sites - they should still have protection on

Apply temp whitelist rules independently of the subdomain

---

integration-test/config.json
integration-test/ui/feedback.js
shared/js/ui/views/feedback-form.es6.js

Makes sure the disabled state for the submit feedback button is correctly reset. I broke it by merging https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/328 without testing fully :(
I've also added some integration tests to prevent this from happening again.
1. Play around with the feedback form (both broken site mode and non-broken site mode)
2. Make sure it's possible to submit the form when everything is filled out in both cases.

Reenable feedback button correctly

---

shared/js/background/chrome-events.es6.js
shared/js/background/chrome-wrapper.es6.js
shared/js/background/classes/site.es6.js
shared/js/background/redirect.es6.js

**Reviewer:**
Fix for #362 
Hides sendMessage error in Firefox. `Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.`
1. npm run dev-firefox
2. load extension and open debug console
3. navigate to some sites. You shouldn't see any `Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.` errors

hide lastError from sendMessage

---

integration-test/background/atb.js
shared/js/background/atb.es6.js

**CC:** @jkv 
Adds logic to set a generalized ATB param that the ATB service passes us.
1. Manually set your ATB to e.g. `v123-4`
2. Do a search
3. Your ATB should now be `v123-1`
4. A more recent ATB like `v161-5` should be unaffected
5. Tests should be passing (`npm run test-int`)

Add logic to generalize atb param if the atb service tells us to

---

integration-test/background/atb.js
shared/js/background/atb.es6.js
unit-test/background/atb.es6.js

**Depends on:**  Internal Changes
Adds ability to parse additional url params from success page
1. Visit https://duckduckgo.com?natb=v123-1zz&cp=atbzz
2. Install extension
3. Ajax call to /exti/ should include `cp=atbzz` (See Kibana)

Check for and parse additional success page params

---

browsers/chrome/manifest.json

**CC:** @kdzwinel 
This PR adds the prepopulated ID for DuckDuckGo to the search provider in Chrome settings. Doing this will tell the browser to use Chromium's built-in settings for DuckDuckGo. This will allow the extension to set our new tab page.
1. Build the extension for Chrome
2. For now, you'll need a build of Chrome 75 - you can use Chrome Canary, Dev, or Beta. See https://www.chromium.org/getting-involved/dev-channel
3. Load the extension. Verify that new tabs open the DuckDuckGo new tab page.

Add prepopulated_id to the search provider

---

browsers/chrome/manifest.json
browsers/firefox/manifest.json

Changes `d` omnibox keyword binding to `ddg`. Addresses https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/388.
1. Build and install extension in Firefox and Chrome
2. Type d then space in omnibox / address bar. In Chrome the omnibox should no longer show 'DuckDuckGo Privacy Essentials' in the left, and in Firefox the first autocomplete suggestion should not be 'DuckDuckGo Privacy Essentials'.
3. Repeat 2 this time using ddg instead of d. This should make Chrome show 'DuckDuckGo Privacy Essentials' in the left of the omnibox, and make Firefox show 'DuckDuckGo Privacy Essentials' as the first autocomplete suggestion.

Change d omnibox keyword to ddg

---

shared/js/background/redirect.es6.js

**Reviewer:**
Fix isSameDomainRequest for Chrome. The request initiator is not the full URL so looking for exact matches fails in some cases. 
1. go to bbc.com/news 
2. there should be trackers listed in the popup

use match for isSameDomainRequest in chrome

---

test-blocking.js

**Reviewer: @jdorweiler  **
Allows test blocking to dump tracker domains for visual inspection.
1. Run with --trackers option
1. Observe trackers dumped to console once test is complete
n/a

dump tracker domains option

---

unit-test/background/banner.es6.js

- Updates check for `getDaysBetween()` to handle case when value is 0
- Go to https://duckduckgo.com/?natb=v215-2rz&cp=atbhc
- Open new tab and install extension
- Visit https://google.com
- Should see `d=0` in evg pixel
- Uninstall extension
- Go to https://duckduckgo.com/?natb=v215-1rz&cp=atbhc
- Open new tab and install extension
- Visit https://google.com
- Should see `d=1` in evg pixel
- Uninstall extension
- Go to https://duckduckgo.com/?natb=v214-2rz&cp=atbhc
- Open new tab and install extension
- Visit https://google.com
- Should see `d=7` in evg pixel

Update date-related tests

---

shared/js/background/banner.es6.js
shared/js/background/chrome-events.es6.js
shared/js/background/experiments.es6.js
shared/js/background/pixel.es6.js
shared/js/background/storage/tds.es6.js

**Reviewer:**
Disables pixels that we're not using anymore.
1. Install extension
2. Open the extension network tab
3. Interact with the popup, you shouldn't see any pixel requests to improving.duckduckgo.com
4. The only allowed pixel is when submitting a broken site report from the whitelist toggle

Disable unused pixels

---

shared/data/surrogates.txt

Add missing method `window.googletag.setAdIframeTitle` to gpt surrogate. Looks like this is causing a little breakage specifically on [walmart.com product pages](https://www.walmart.com/ip/2-pack-Neutrogena-Moisturizing-Body-Oil-Light-Sesame-Formula-16-fl-oz/754642451?selected=true).
1. build extension
2. visit link above, check that there are no blank images or iframes on the page

add setAdIframeTitle method to gpt surrogate

---

shared/js/background/chrome-events.es6.js

This removes the modifications to the DNT header, as Mozilla asked us not to modify it.

Remove changes to the DNT header

---

shared/data/experiments-out.js
shared/js/background/chrome-events.es6.js

Removes the fingerprint protection experiment gates. The experiment did not show any increase in breakage or reported issues, so I'd like to enable this feature for all users.

Enable fingerprint protection for all users

---

shared/html/popup.html
shared/js/ui/pages/popup.es6.js
shared/js/ui/templates/search.es6.js
shared/js/ui/templates/site.es6.js
shared/js/ui/templates/top-blocked-truncated.es6.js
shared/js/ui/templates/top-blocked.es6.js
shared/scss/_mixins.scss
shared/scss/_vars.scss
shared/scss/base/base.scss
shared/scss/popup.scss
shared/scss/views/_hero.scss

Previously the order of elements in the popup was not guaranteed because they were slotted one after the other on a first-come-first-served basis and the underlying logic had network and other async calls. In order to maintain visual hierarchy, we were relying on `position: absolute` to explicitly set their position. This was hard to maintain and fragile.
With this PR, I have created hardcoded containers in the markup and render items inside them, regardless of when they become available. This allowed me to remove the fixed and absolute positioning and just let elements follow the normal flow, so that I could also remove the fixed heights of the body and other elements.
This PR also runs a minor review on elements heights to make them all more uniform in …

Improve css positioning in popup

---

shared/js/background/redirect.es6.js
shared/js/background/storage/tds.es6.js

**Reviewer:**
This updates the tracker blocking logic to check for cname entries. If a request for a first party is actually a CNAME to a third party tracker, block it as if it were not behind a CNAME.

Add cname support for blocking trackers

---

package-lock.json
package.json

Updates the privacy-grade dependency to 1.03, which includes the cname blocking logic.

Update privacy grade to 1.03

---

shared/js/background/classes/agentspoofer.es6.js

This fixes an issue where if the user agent safe list is longer than a single entry, it won't correctly apply the safe listing.

Fix issue with processing User Agent Safe List

---

shared/data/fingerprint-protection.js
shared/js/content-scripts/GPC.js

This adds some content checks into the anti-fingerprinting script injection, and will not inject scripts if the content type is json or xml. 
Fixes issue #503

Stop injecting anti-fingerprint protections into xml and json documents

---

shared/data/fingerprint-protection.js
shared/js/background/chrome-events.es6.js
shared/js/background/classes/agentspoofer.es6.js
shared/js/background/storage/agents.es6.js

Brave generally doesn't include a special UA, so JS agent parsing libraries don't correctly identify Brave user agent strings. It looks like there was a logic error in how excluded regex patterns were being matched, which this should fix, so we can also ignore certain Brave strings are are DDG internal only.
**Reviewer:**

Break-fix: Disable UserAgent spoofing & fix issue with Temp Storage FP protection

---

shared/js/background/tracker-utils.js
shared/js/background/utils.es6.js
unit-test/background/tracker-utils-tests.js

Modifies the referrer header truncation function to include a trailing '/' when the referrer is modified to a domain. This is because some sites do security checking on referrer, and may not match without this trailing slash.

Add trailing slash to modified referrer

---

integration-test/background/atb.js

**Reviewer:**
Due to a bug the current test for the post-install page always passes. This PR solves that by fixing the async/await logic.
- Run the first test in `integration-test/background/atb.js`

Fix postinstall page test

---

shared/js/content-scripts/block-cookie.js

**Reviewer:**
On extension startup it is possible that the content-script message handler in the background is not ready when we query from the content-script. In this case we get an `undefined` response. This PR handles this case to avoid showing an error in the console.

Fix error when no response is received from bg

---

shared/js/background/chrome-events.es6.js
shared/js/background/storage/cookies.es6.js
shared/js/content-scripts/block-cookie.js

**Reviewer:** @sammacbeth @jonathanKingston @kdzwinel 
Cookie exclusion list was not being cached. If the list endpoint returned a 304 there would be no response and the list would fail to load. This PR adds caching based on the UserAgent list implementation.
1. Load extension
2. Visit site with excluded cookie domain (e.g. google 3rd party login)
3. Login should work
4. Reload extension (to force reloading exclusion list)
5. Repeat steps 2-3
**Note:** Since this relies on getting a 304 response you may need to reload the extension in quick succession

Add caching for exclusion list

---

shared/js/background/storage/cookies.es6.js

**Reviewer:**
Fixes an issue after #582 if there is an update-to-date etag in settings, but the data is missing in `chrome.storage`.

Fix cookie config load error when data is missing in storage

---

shared/js/background/chrome-events.es6.js
shared/js/content-scripts/floc.js

**Tech Design:** https://app.asana.com/0/481882893211075/1200159597529958/f
This disables FLoC API by opting all sites out of FLoC and removing the JS API.
1. run chrome (89+) with flags that force FLoC on:
```
/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --enable-blink-features=InterestCohortAPI --enable-features="FederatedLearningOfCohorts:update_interval/10s/minimum_history_domain_size_required/2,FlocIdSortingLshBasedComputation,InterestCohortFeaturePolicy"
```
1. clear browsing history
1. visit couple of websites
1. verify that document.interestCohort() doesn't return a cohort number (in context where we don't block the API - e.g. safelisted or any chrome:// page)
1. verify that document.interestCohort() is not …

Disable FLoC

---

integration-test/background/test-fingerprint.js

FingerprintJS result is an object which is not hashable, so the set
comparison was not working.
**Reviewer:**

Fix fingerprint tests

---

shared/js/background/chrome-events.es6.js
shared/js/background/csp-blocking.es6.js

**Reviewer:**
Scripts injected by extensions can be blocked by CSPs in Firefox. If a CSP `report-uri` is specified, the browser will report this, including the `moz-extension://` url to the injected script. On Firefox this is a unique identifier which is persistent for a browser, including in private browsing windows.
This PR blocks CSP reports which contain a moz-extension:// URL, preventing this identifier from being leaked.
1. Grab privacy-test-pages with this PR: https://github.com/duckduckgo/privacy-test-pages/pull/35
2. Visit `/security/csp-report/index.html`
3. There should be no reported leakages. In the network console one of the csp-reports should be blocked.
As this is Firefox-only, our integration test setup cannot test for this issue.

Block CSP reports that contain a moz-extension URL

---

shared/js/ui/models/whitelist.es6.js
unit-test/ui/models/whitelist.es6.js

**Reviewer:**
The domain parsing in the UI for adding sites to the unprotected site list was treating IPs as invalid inputs (see #571). This PR fixes that issue.
1. Open the popup and click 'unprotected sites'
2. At the bottom of the page, choose 'Add unprotected site' and type an IP address (e.g. `1.1.1.1`) and click 'Add'
3. The IP should be added to the list.

Allow IPs to be added to unprotected site list

---

package.json

Let's make `lockfileVersion: 1` stick!
Make sure that you can `npm i` on your machine and build the extension.

🔒 Require version npm 6 so that the lockfileVersion is always 1

---

shared/js/content-scripts/click-to-load.js

This removes innerHTML calls, replacing them with textNodes. This removes the ability to insert links or styles via configuration, so changes to link text or destination will require code changes going forward.

Remove innerHTML calls in favor of text nodes

---

browsers/firefox/manifest.json

This change adds the preference button in about:addons and also embeds it in the extensions site:

Add preferences button to firefox

---

shared/js/content-scope/canvas.js

Fixes #610
See #610.
I've ignored for now only 255,0,0,255 pixels and 0,0,0,0 which are a canvas default.
I would normally assign these variables but we are in a very hot path here.
1. Visit: https://labs.phaser.io/edit.html?src=src/scenes/ui%20scene.js&v=3.53.1
2. See the score is in the wrong position (this might not be in a consistent place due to the random pixels)
After the fix is applied, the score text should be in the top left.

Ignore phaser text calculation to canvas randomisation

---

shared/js/content-scope/cookie-protection.js

**Reviewer:**
When we load a content-scope script on a page, after the first tick any global could be polluted or changed by other scripts in the page. This can break some of our protection implementations.
In the case of #680, the page loaded a polyfill which changed `Promise` and `Promise.prototype.then`. This then caused an issue when we subsequently called the polyfilled `Promise.then` with a native `Promise` instance.
The PR fixes this specific case by creating the `then` function during the script's first tick, where we are sure (are we?) that we have the native `Promise.prototype.then`.
See #680

Prevent polyfill side-effects from 1p cookie protection

---

shared/data/web_accessible_resources/fb-sdk.js
shared/js/content-scripts/click-to-load.js

This removes the usage of the style data in remote config, and also fixes an issue where some comment sections don't load after enabling (due to a FB update)

Remove remote styling & fix comment issue on some sites

---

browsers/chrome/manifest.json
browsers/firefox/manifest.json

- PR: Prevent polyfill side-effects from 1p cookie protection
- Add getAll linker object to ga surrogate
- PR: Wrap floc code in try
- GPC DOM API not injected into frames
- Storage test intermittent failures
- Privacy Grade tests failing
- Update logo in extensions
- PR: Same domain trackers are sometimes undefined if they haven't been see… #659
- PR: Add preferences button to firefox
- PR: Update chrome store description
- PR: Remove selenium tests
- PR: Change chrome.extension.getURL to chrome.runtime.getURL
- PR: Add Canvas unit test
- PR: Ignore phaser text calculation to canvas randomisation
- PR: Update autofill version
- PR: Add www. back into safelisting
- Site Breakage: reuters.com (2021-05-13)
- PR #673: Full Click to load release
- PR: Allow postinstall page to be disabled by …

Release: 2021.6.2

---

browsers/chrome/managed-schema.json
browsers/chrome/manifest.json
managed-storage.md
shared/js/background/chrome-wrapper.es6.js
shared/js/background/settings.es6.js

Allows some settings to be pre-configured by system administrators via extension managed storage. Initially this adds support for the `hasSeenPostInstall` which can be used to prevent the post install page being shown on new installs.
Following instructions from [here](https://extensionworkshop.com/documentation/enterprise/adding-policy-support-to-your-extension/), the following policy would disable the post install page:
```json
{
"policies": {
"3rdparty": {
"Extensions": {
"jid1-ZAdIEUB7XOzOJw@jetpack": {
"hasSeenPostInstall": true
}
}
}
}
}
```
Fixes #567 and #519
For Firefox:
1. Put the above JSON into a file call `policies.json` and put it into the appropriate location for Firefox on your OS (e.g. on mac in (`Firefox.app/Contents/Resources/distribution`).
2. Open Firefox on a new …

Allow postinstall page to be disabled by managed storage

---

integration-test/background/click-to-load-integration-tests.js

This updates how the Click to Load integration tests determine whether Facebook requests are loading. Instead of assuming "0" requests will be successful, it looks at requests that are expected (iFrame requests are generally sent regardless, and blocked by the extension).
It should now consistently pass if things are working right with CTL.

DRAFT: Attempt 2 to fix ctl integration tests

---

shared/js/content-scope/audio-protection.js

Fixes #708
This fixes the permission denied issue which is breaking the method and failing gracefully (like it should). For blank input we will now skip adding noise. However we should investigate further / switch to the computing of blank data to fully match canvas.

Fix audio buffer permission denied in Firefox.

---

package-lock.json
package.json

Update autofill to 3.0.1:
- Fix breakages on other platforms 🔧
- Remove autofill from signup page 🦆

Update autofill to 3.0.1

---

shared/html/devtools-panel.html
shared/js/devtools/panel.es6.js

**Reviewer:**
#728 changed the set of features that can be toggled on a global and per-site basis. This PR updates the debugger panel to dynamically pull in the set of configurable features from the config, so it will stay up-to-date to future changes to features.
While we can present feature toggles for all features, the following don't yet support site-specific exceptions:
* `contentBlocking` - currently broken
* `trackingCookies3p` - only supports 3rd party exceptions
* `clickToPlay` - only supports global disable
* `gpc` - only works for JS API, header is still sent.
These should be fixed by #749 .

Support new configurable features in debugger panel

---

shared/js/background/atb.es6.js
unit-test/background/atb.es6.js

**Reviewer: TBD**
Adds support for DDG subdomains that include dashes in ATB accepted URL regex.
- e.g https://dev-machine.duckduckgo.com
- Build Chrome/FF dev build
- Install extension
- Visit a DDG subdomain that includes a dash (`-`)
-  [ ] Ensure the `atb=` param is appended to the URL

Allow dashes in ddg subdomain regex

---

shared/scss/base/_forms.scss

A tiny spacing issue in feedback.html:
- In the popup, click on the cog
- Click on Share Feedback
- The checkbox should have the appropriate spacing

Fix spacing in feedback.html

---

integration-test/background/click-to-load-integration-tests.js

These tests are essentially being ignored already as we manually check every time a test fails and merge if these are the reason of failure. This is causing overhead to a merge and in reality we should be fixing the test.

Disable click to load tests due to perma failures

---

shared/js/background/email-utils.es6.js
shared/js/background/events.es6.js

In the current version, there is an error in the console when visiting the settings page. For some reason, the background page tries to create a new context menu item with the same id. This change moves the creation of the context menu item to the `onInstalled` event, thus fixing the issue. This is not happening in Firefox.
1. On Chrome, go to settings
2. There should be no error in the console

Prevent error in settings page on Chrome

---

.gitignore
.gitmodules
Makefile
package.json
scripts/generateEtags.js
shared/js/background/settings.es6.js
shared/js/background/storage/tds.es6.js

This replaces this hard coded config that is already outdated and will be forgotten about.
It also adds in a pre-generated etags config file which prevents the extension needing to load the file output from the server if it matches the bundled version saving us start up time and server costs.
Checking the e-tag works:
1. Load the extension with web ext
2. Debug the extension in about:debugging#/runtime/this-firefox
3. Open the inspector
4. Clear the extension storage in the inspector
5. Reload the extension
6. Ensure that the network tab load for the `extension-config.json` is a 304
Ensure there are no "TDS: data update failed" in the console.

Add config submodule as preloaded config

---

shared/js/background/allowlisted-trackers.es6.js

**Reviewer:**
Followup from #756. Need an OR instead of an AND to return when the allowlist is empty. 
1. Current allowlist is empty. Built the extension and check that it returns false

fix empty allowlist check

---

.github/workflows/build.yml

**Reviewer:**
Currently we run CI twice per commit in PRs - once triggered by the PR, another triggered by the push. This changes the CI triggering so we only run the PR build.

Prevent duplicated CI builds on PR

---

shared/js/background/events.es6.js

**Reviewer:**
For third-party cookie blocking we block the cookie getter/setter for iframes where the iframe origin is a tracker domain, which is owned by a different entity to the top-level frame domain.
In order to do this partyness check, we need the document url of the iframe, and the URL of the tab the frame is in. For the former we were using `sender.url`, which in Firefox can be `about:blank` in some circumstances. When that case happens, the check would always return that `about:blank` was third-party to whatever the tab URL was. Because the check for whether the frame document URL was a tracker used the `documentUrl` parameter sent by the content script (which would not be `about:blank`), it was possible to block cookies in a iframe from a tracker domain when it was embedded on a …

Correctly calculate partyness for about:blank frames

---

browsers/chrome/manifest.json
browsers/firefox/manifest.json
scripts/bumpVersion.js

@jonathanKingston Just FYI, I have tweaked the bumpVersion script to use all dots in the version, because dashes are not allowed (failed validation when uploading to Mozilla).

Bump version

---

shared/js/background/events.es6.js
shared/js/background/settings.es6.js
shared/js/background/storage/tds.es6.js

**Reviewer:**
Manual testing is the only way I've found to resolve this issue mentioned in: https://app.asana.com/0/1200223097357040/1201035302493499/f
For this ensure you're on an old copy of the extension copy in privacy-configuration module (you can checkout an old commit and then run `npm run generate-etags`)
1. Load the extension with web-ext
2. Inspect the storage to see if there's what is stored in the indexedDB
3. Check network requests to see if a 304 occurred
4. Update the code (web ext should trigger an update)
5. Check the storage again to verify it's still the remote copy

Resolve reinstall caching previous bundled config values

---

shared/js/background/email-utils.es6.js
shared/js/background/events.es6.js

In https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/767 we moved the context menu creation on `onInstalled` to avoid an error in Chrome when visiting the settings page. Apparently, that was a Chrome bug and no longer happening, but the change broke context menu autofill on Firefox (see https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/876).
- On Firefox, install and enable autofill
- On any input field, open the context menu
- You should see the Dax autofill menu item
- On Chrome, open the settings page
- You should see no error in the console

Reinstate autofill from context menu on Firefox

---

shared/js/content-scripts/click-to-load.js

**Reviewer**: @jonathanKingston
**Cc**: @Charlie-belmer, @ladamski
This is a grab-bag of  Click to Play code improvements that I've split-out from my current project work. I've explained each change in the commit descriptions (please don't squash the commits!), but I'll also summarise here:
1. Some superficial changes, including fixing comments and clearing trailing whitespace.
2. Changed the CTP placeholder code to reduce ways the website's styles could screw them up. Most importantly I start putting as much of the placeholder inside a shadowRoot as possible.
3. Properly handled entries in `social_ctp_configuration.json` which don't include the `informationalModal` key. Currently the code completely fails, but instead we should just consider that `shouldShowLoginModal` is false and not …

Click to Play code improvements

---

shared/js/content-scripts/click-to-load.js

**CC:** @Charlie-belmer, @kdzwinel, @ladamski 
@kdzwinel noticed the fonts are broken in our Click to Play placeholders. It turns out, my [recent change](https://github.com/duckduckgo/duckduckgo-privacy-extension/commit/4e39246d28e7ca606256f65444792ecea0a686b3) to put the placeholder's content inside a `shadowRoot` broke them. I didn't realise that `@font-face` is broken inside of `shadowRoot` on Chrome. ([See related discussion](https://github.com/mdn/interactive-examples/issues/887).)
With this change, we keep the `@font-face` stuff outside of our `shadowRoot`, but leave everything else inside.
1. Browse to https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/ and ensure the font used by our placeholders looks correct:

Fix the fonts in our Click to Play placeholders

---

shared/js/background/classes/site.es6.js
shared/js/background/devtools.es6.js
shared/js/background/events.es6.js
shared/js/background/utils.es6.js
shared/js/content-scope/utils.js
shared/js/devtools/panel.es6.js
shared/js/ui/models/site.es6.js

When feature key is missing from the config we should disable the feature. This already got us in trouble once and we partially addressed it with https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/938 .
1. Go to chrome-extension://hacmkdifffpphkffddioobolnmelljoa/html/list-editor.html in the extension
2. Change config to 
```json
{
"readme": "https://github.com/duckduckgo/privacy-configuration",
"version": 1636990486124,
"features": {},
"unprotectedTemporary": [
]
}
```
3. Make sure that all features, both content world (e.g. fingerprinting, 1p cookie expiry date thing) and background-page (e.g. GPC headers, content blocking) are disabled.

Features missing from config should be disabled.

---

.github/workflows/stage.yml
package-lock.json
package.json
scripts/asana-release.js

**Reviewers:** @jonathanKingston @MariagraziaAlastra @sammacbeth 
**Asana:** https://app.asana.com/0/0/1200750505563921/1201183123265449/f
Automate the Asana paperwork!
- Run the workflow, with manual input of version (as the current stage.yml)
- Run the script and commit the changes
- Generate a new Release draft (prerelease: true)
- Use the list of commits from the previous tag to the current to populate the release notes
- Build zip files and upload them to the release ← We already have most of this logic in publish.yml
- Asana Script:
- Get list of tasks in the Extension release project under the Release section
- Duplicate the release template, paste in the list of tasks in the appropriate section
- Upload the zip files to Asana
Give it a first pass, then we'll merge and try to cut …

Improve release automation with Asana magic

---

browsers/firefox/manifest.json

It turns out that the extension is broken for Firefox versions below
65. For example, we use APIs like `Element.srcElement`[1],
`Element.attachShadow`[2], `globalThis`[3] and pass the
"visible" option to `browser.contextMenus.create`[4]. Rather than to
workaround those issues (and likely more), let's just drop support for
those old versions of Firefox.
1 - https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement#browser_compatibility
2 - https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow#browser_compatibility
3 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility
4 - https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/menus/create#browser_compatibility
**Reviewer:** …

Increase minimum supported Firefox version to 65

---

shared/js/background/broken-site-report.js
shared/js/background/classes/https-redirects.es6.js
shared/js/background/events.es6.js
shared/js/background/https.es6.js
shared/js/background/message-handlers.js
shared/js/ui/base/model.es6.js
shared/js/ui/models/site.es6.js
shared/js/ui/models/submit-breakage-form.es6.js
shared/js/ui/views/search.es6.js
shared/js/ui/views/site.es6.js
shared/js/ui/views/top-blocked-truncated.es6.js
unit-test/background/broken-site-report.js
unit-test/background/classes/https-redirects.es6.js
unit-test/background/reference-tests/broken-site-reporting-tests.js

Removes all tracking pixels other than the site report as it was all unused.
I renamed the class and hard coded the pixel name so it can't be used again without reimplementing it as it breaks addon policy.
https://app.asana.com/0/892838074342800/1200747843240318/f
1. Open up the browser inspector
2. Report a broken site
3. Ensure the report is firing correctly

Remove unused pixel tracking

---

shared/js/background/message-handlers.js

Click to Play is intended to protect the user from tracking via
embedded third-party content. The placeholder elements should never be
displayed for first-party embedded content.
**CC:** @Charlie-belmer, @ladamski, @kdzwinel 
1. Ensure Facebook Click to Load still works correctly: https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/

Don't display Click to Play placeholders for first-party domains

---

shared/data/web_accessible_resources/fb-sdk.js
shared/js/content-scripts/click-to-load.js
shared/js/content-scripts/fb-surrogate-xray.js

Move the entity name into the event details for Click to Play events,
instead of putting them in the event name. Also include the
replaceSettings and random widget ID where relevant.
Some tweaks to how we do the CTP events ready for the YouTube changes. 
1. Test that the Facebook CTP feature still works OK https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/

Rethink Click to Play events

---

shared/js/ui/models/submit-breakage-form.es6.js
unit-test/background/reference-tests/broken-site-reporting-tests.js

This PR updates reference tests after latest changes to HTTPS tests and small adjustment to broken site reporting tests - https://github.com/duckduckgo/privacy-reference-tests/pull/24 . It also fixes a bug in how surrogates are reported in the breakage reports (previously surrogated hosts went into both `blockedTrackers` and `surrogates` fields, they should have gone only to `surrogates`).
1. Send a breakage report from a site that uses a surrogate (e.g. https://privacy-test-pages.glitch.me/tracker-reporting/1major-with-surrogate.html) and double check that report being sent only mentions surrogate in the `surrogates` field and not the `blockedTrackers` field of the report
2. Double check that blocked trackers are still correctly sent with `blockedTrackers`

Reference tests update and surrogate reporting fix

---

shared/js/content-scripts/click-to-load.js

Split out the DuckWidget creation and element replacing logic from
createReplacementWidget function. Tidy up some of the function and
variable names to make the code easier to understand. Begin emitting
events when a tracking element is replaced, so that the surrogate
scripts can tie tracking elements to their corresponding placeholder.
**CC:** @ladamski, @kdzwinel, @Charlie-belmer 
See above.
1. Check that the Facebook CTP still works as expected: https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/

Split apart createReplacementWidget function and add events

---

integration-test/background/click-to-load-facebook.js

Since we're planning to expand the Click to Load feature to apply to
embedded content from other companies, we should rename the
Facebook-specific integration tests.
**CC:** @jonathanKingston @ladamski 
I've split out the file rename from my work to make these tests more reliable. I wanted to avoid losing the commit history of this file, sometimes Git gets confused and messed up the history for files when they are renamed and changed substantially at the same time.
1. Ensure the Facebook CTP integration tests still run and test (flakily).

Rename Facebook Click to Load integration test file

---

shared/js/background/redirect.es6.js

**Reviewer:**
We are currently restricting 1p cookie access to tracker scripts which are on a 3rd party domain to the site's domain. We should, however, not be doing this for trackers which share the same ownership as the site. This PR fixes this so we properly honor our same-entity exception.

Same-entity rule for 1p cookie protections

---

integration-test/background/click-to-load-youtube.js
integration-test/helpers/requests.js
integration-test/helpers/testConfig.js
shared/data/web_accessible_resources/youtube-iframe-api.js
shared/js/background/debug.es6.js
shared/js/background/events.es6.js
shared/js/background/message-handlers.js
shared/js/content-scripts/click-to-load.js

Add privacy protection from embedded YouTube videos and
playlists. Block third-party YouTube requests and display a
placeholder for the corresponding element that allows users to
unblock the content again. Where possible, also upgrade embedded
videos to use youtube-nocookie.com.
**CC:** @ladamski, @kdzwinel, @Charlie-belmer, @sammacbeth  
1. Add the following entry to your `social_ctp_configuration.json` file: https://gist.github.com/kzar/89bc3b8971daef09334da5a0799589c0
2. Navigate to the YouTube test page and follow the instructions: https://privacy-test-pages.glitch.me/privacy-protections/youtube-click-to-load/

Implement YouTube Click to Load

---

shared/js/background/events.es6.js
shared/js/background/redirect.es6.js

**Reviewer:**
Fixes an issue where we incorrectly showed the message "temporarily disabled Privacy Protection" for all tabs which are open on extension start.

Don't create Tab objects for initial tabs until config is loaded.

---

scripts/asana-release.js

**Reviewer:** @jonathanKingston @shakyShane 
In the latest release I noticed that the testing subtasks didn't show testing steps. This should fix it.

Include notes when duplicating the testing tasks

---

integration-test/background/click-to-load-facebook.js

Sometimes the Facebook Click to Load integration tests fail when there
are less requests made than usual. Let's reduce the expected request
count down from five to three to get the tests passing more reliably.
**CC:** @sammacbeth

Reduce the expected Facebook request count in the integration tests

---

integration-test/background/url-parameters.js
integration-test/data/configs/url-parameters.json
shared/js/background/atb.es6.js
shared/js/background/classes/tab.es6.js
shared/js/background/redirect.es6.js
shared/js/background/storage/tds.es6.js
shared/js/background/url-parameters.es6.js
shared/js/ui/models/submit-breakage-form.es6.js
unit-test/background/atb.es6.js
unit-test/background/reference-tests/url-parameters-tests.js

Implement the URL tracking parameters protection feature. The feature
strips known tracking parameters for navigations, assuming that
neither the initiator URL (referrer) nor request URL (destination) are
allowlisted.
See also the reference tests[1] and test pages[2] for more details.
1 - https://github.com/duckduckgo/privacy-reference-tests/tree/main/url-parameters
2 - https://privacy-test-pages.glitch.me/privacy-protections/query-parameters
**Reviewer:** @SlayterDev 
**CC:** @kdzwinel

Implement URL tracking parameters protection feature

---

CONTRIBUTING.md
Gruntfile.js
package.json

This reinstates the watching for content scope.
- I removed the `npm install` step from the dev commands to prevent overriding `npm link`.
- I skipped autofill for now as it's a little more involved and we can add it later.
- This force installs the node_module dependencies and builds it.

Add back in node module watching and building for content-scope-scripts

---

shared/js/background/helpers/arguments-object.js

**Reviewer:** @SlayterDev 
For https://github.com/duckduckgo/content-scope-scripts/pull/48 to expose the settings configuration to content scope scripts.
- This exposes the ability to do feature flag checks as otherwise the data isn't available in the content script at runtime.
- It removes the need to send blank settings objects to reduce data sent a little.
@SlayterDev This is going to be needed in your next project also for hardware fingerprinting
1. With the debugger to ensure the config is passed to the `args` property
2. Alternatively check out the content scope patch and ensure https://coveryourtracks.eff.org/ WebGL is working with the flag en/disabled.

Add support for feature settings in args object

---

browsers/chrome/manifest.json
browsers/firefox/manifest.json
package-lock.json
package.json
scripts/asana-release.js
shared/data/bundled/extension-config.json
shared/data/etags.json

**Reviewer:** @sammacbeth or @GioSensation 
https://app.asana.com/0/312629933896096/1202181759555718/f

Release 2022.4.26

---

integration-test/background/grades.js

The privacy grade tests were often failing on the Twitter test case,
let's disable that one for now to get the tests passing more
reliably.
Verify that the integration tests pass locally and in CI.

Disable failing Twitter privacy grade test case

---

integration-test/background/click-to-load-youtube.js

Sometimes the YouTube Click to Load integration tests fail when there
are less requests made than usual. Let's reduce the expected request
count down from six to two to get the tests passing more reliably.
Verify that integration tests are still passing both on CI and locally.

Reduce the expected YouTube request count in the integration tests

---

integration-test/helpers/harness.js
package-lock.json
package.json

Puppeteer recently added headless support for running Chrome
extensions[1], so let's make use of that. Also, let's take care to
properly wait for the extension's background page to load.
1 - https://github.com/puppeteer/puppeteer/pull/8260
**CC:** @kdzwinel, @ladamski 
Verify that integration tests are still passing both on CI and locally.

Run the integration tests in headless Chrome

---

integration-test/background/click-to-load-facebook.js
integration-test/background/click-to-load-youtube.js
integration-test/helpers/apiSchema.js
integration-test/helpers/backgroundWait.js
integration-test/helpers/pageWait.js
integration-test/helpers/testConfig.js

While they run reliably locally, some of the Click to Load integration
tests are flaking on CI. These improvements aim to help reduce those
flakes:
- If a test page fails to load, let's mark the test as skipped rather
than as a failure. There's not much we can do to get around network
failure.
- Take care to wait between unblocking a YouTube video and clicking
to play it.
- Take care to wait for pages to finish closing.
- Avoid exceeding Jasmine's 20 second timeout when waiting for the
extension configuration to load. If extension configuration fails
to load, throw a clear exception to explain that.
- When clicking the Facebook Click to Load buttons, ignore buttons
that Puppeteer fails to click.
- Fix a bug where the test extension configuration would still
attempt to be unloaded, even …

Improve reliability of Click to Load integration tests

---

shared/js/background/email-utils.es6.js

An error is thrown if our context menu already exists when we attempt
to create it. That error can be simply ignored, since there is no
further action required.
1. Verify that the "Use Duck Address" context menu still works when you right click on email input fields.

Suppress duplicate context menu error

---

browsers/chrome-mv3/manifest.json

With Chrome 101 support for requestDomains match conditions was added
to the declarativeNetRequest API[1]. We need those for fundamental
extension functionality, so let's set that as the minimum version to
ensure the MV3 build of the extension works correctly.
1 - https://groups.google.com/a/chromium.org/g/chromium-extensions/c/4971ZS9cI7E/m/pkmHIGv3DgAJ
None really, this just affects the WIP Chrome MV3 build.

Require Chrome >=101 for the Chrome MV3 extension

---

browsers/chrome-mv3/manifest.json

The inject.js content script attempts to run scripts in a way that
isn't allowed with Chrome MV3. For now, let's simply disable that
content script while we get the build running.
None really, this just affects the WIP Chrome MV3 build.

Disable inject.js content script for MV3 extension

---

integration-test/config-mv3.json
integration-test/helpers/backgroundWait.js
integration-test/helpers/harness.js
package.json

Add an integration test runner for Chrome MV3. This is to aid the
transition between Chrome MV2 and Chrome MV3.
Also expand on the integration test helpers to properly handle
extensions with a background ServiceWorker instead of a background
page.
Check that the MV2 integration tests are still passing.
Note: This PR does not actually enable any MV3 integration tests, that will come later!

Add Chrome MV3 integration test runner

---

shared/js/background/events.es6.js
shared/js/background/wrapper.es6.js

Chrome MV3 no longer supports blocking requests using the webrequest
API. Disable those incompatible code-paths for our Chrome MV3 extension.
**Reviewer:** @muodov 
- Check that tracker blocking still works with the MV2 extension.
- Check that the integration tests are still passing.

Disable blocking webRequest listeners for MV3

---

shared/js/background/debug.es6.js
shared/js/shared-utils/parse-user-agent-string.es6.js

The background "page" of an extension is replaced with a background
ServiceWorker in Chrome MV3. ServiceWorker's do not have access to the
`window` Object, instead `self` or `globalThis` must be used.
- Ensure the integration tests still pass.

Replace `window` usage in the background

---

shared/js/content-scripts/click-to-load.js

When sending the "getImage" message, an empty options Object wasn't
being handled correctly and resulted in an attempt to fetch an image
called "/img/social/[object%20Object]".
This regression was introduced when Promisifying the CTP messaging
code, see https://github.com/duckduckgo/duckduckgo-privacy-extension/commit/ad1fb76eb6ef04ad6ac79a442e24f9069ae1569f#diff-b739ace550706db1913f39023ec658272583c9b920f50576ad216ad164f289dcR2
**CC:** @ladamski 
**Depends on:** 
1. Install the extension
2. Open the background console, clear any errors/logs.
3. Load https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/ in a new tab.
4. Ensure the placeholders (and icons in placeholders are displayed correctly).
5. Ensure there are not lots of errors about …

Fix CTP getImage exceptions

---

browsers/chrome-mv3/manifest.json
shared/js/background/events.es6.js
shared/js/background/onboarding.es6.js
shared/js/background/wrapper.es6.js

Chrome MV3 replaces tabs.executeScript and tabs.insertCSS with
scripting.executeScript and scripting.insertCSS respectively. Add API
wrappers that abstract the differences between those APIs (as far as
possible).
Also, add the "scripting" permission for the Chrome MV3 extension, so
we can use the new APIs.
See https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#code-execution
1. Verify the integration tests are still passing.
2. Build and install the MV2 extension, then test the following:
- Open a new tab, perform a search on duckduckgo.com and verify the purple welcome banner is shown.
- Facebook Click to Play works correctly, [using the test page](https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/)
- Click the extension …

Add executeScript and insertCSS wrappers

---

browsers/chrome-mv3/manifest.json

It turns out chrome.scripting.executeScript support for the
injectImmediately option[1] was only added with Chrome
102[2]. Increase the minimum supported Chrome version to 102 for the
MV3 build.
1 - https://developer.chrome.com/docs/extensions/reference/scripting/#property-ScriptInjection-injectImmediately
2 - https://bugs.chromium.org/p/chromium/issues/detail?id=1217895#c20
Nothing to test really.

Require Chrome >=102 for the Chrome MV3 extension

---

integration-test/background/atb.js
integration-test/background/click-to-load-facebook.js
integration-test/background/click-to-load-youtube.js
integration-test/background/grades.js
integration-test/background/https-loop-protection.js
integration-test/background/onboarding.js
integration-test/background/storage.js
integration-test/background/test-fingerprint.js
integration-test/background/url-parameters.js
integration-test/content-scripts/autofill-test.js
integration-test/content-scripts/gpc.js
integration-test/content-scripts/test-canvas.js
integration-test/helpers/pageWait.js

Use the `backgroundWait` and `pageWait` integration test helpers
consistently. That way, we can avoid repeating code and avoid failing
when pages/requests load too slowly. It also means that we're properly
waiting for the extension configuration to have loaded before running
the tests.
Along with that, expand the `pageWait` test helpers to provide more
useful output on timeout and to provide a `waitForNetworkIdle` wrapper.
1. Ensure integration tests are still passing.

Use backgroundWait and pageWait integration test helpers consistently

---

integration-test/background/atb.js
integration-test/background/click-to-load-facebook.js
integration-test/background/grades.js
integration-test/background/onboarding.js
integration-test/background/test-fingerprint.js
integration-test/background/url-parameters.js
integration-test/content-scripts/autofill-test.js
integration-test/content-scripts/input-detection-site-list.js
integration-test/data/configs/click-to-load-facebook.json
integration-test/data/configs/click-to-load-youtube.json
integration-test/data/configs/storage-blocking.json
integration-test/data/configs/url-parameters.json
integration-test/helpers/apiSchema.js
integration-test/helpers/backgroundWait.js
integration-test/helpers/testConfig.js

With Chrome Manifest V3, the extension's background page is replaced
with a background ServiceWorker that no longer has access to a
`window` Object. Let's replace (where possible) references to the
`window` Object (and implicit references to `window.dbg`) with
references to `globalThis`. While this isn't enough to get the
integration tests passing for Chrome MV3, it removes one more reason
for the tests to fail!
Note: Some references to `window` would have worked, since they are in
a page instead of the background ServiceWorker. `self` would
have worked too. Let's replace those anyway, to set a clear
example about which global Object to use.
**CC:** @ladamski 
1. Ensure integration tests are still passing.

Use `globalThis` instead of `window` in integration tests

---

shared/data/constants.js
shared/js/background/events.es6.js
shared/js/background/utils.es6.js
unit-test/background/utils.es6.js

Our main webRequest.onBeforeRequest listener, responsible for core
extension functionality like tracker blocking and smarter encryption
only fired for a subset of the available request types:
["main_frame", "sub_frame", "stylesheet", "script", "image",
"object", "xmlhttprequest", "websocket", "other", "ping"/"beacon"]
At the time of writing, that misses the following request types on
Chrome:
["csp_report", "font", "media"]
and the following requests types on Firefox:
["object_subrequest", "xslt", "xml_dtd", "font", "media",
"csp_report", "imageset", "web_manifest", "speculative"]
We want to intercept all request types, and since the default is to simply
match all request types[1], we can just remove the request type filter
entirely.
1 - …

Fire handleRequest onBeforeRequest listener for all request types

---

shared/js/background/email-utils.es6.js
shared/js/background/events.es6.js
shared/js/background/wrapper.es6.js

With Manifest v3, the background ServiceWorker restarts often. It
turns out that the code that sets up periodic alarms is re-run each
time the ServiceWorker restarts, and that causes the alarms to
reset - they are always X minutes from firing, but will never fire!
We need to take care to check an alarm doesn't already exist, before
attempting to create it. Let's add a createAlarms wrapper to make that
easy to get right.
See also this great writeup by wOxxOm:
https://stackoverflow.com/questions/66391018/how-do-i-call-a-function-periodically-in-a-manifest-v3-chrome-extension/66391601#66391601
**CC:** @jonathanKingston 
1. This is not easy to test, but the easiest way is probably to add console logging to `onAlarm` listener in events.es6.js to ensure the scheduled …

Add createAlarm wrapper to avoid overwriting existing alarms

---

shared/js/background/classes/tab.es6.js
shared/js/background/redirect.es6.js
shared/js/background/tab-manager.es6.js

Requests initiated by ServiceWorkers are given a tabId of -1, but we
still want to block tracking requests that they might make. So let's:
- Stop ignoring requests with a tabId of -1.
- Create an opaque Tab Object for those requests, but skip storing it
for later lookup (since by definition we aren't sure which tab the
request originated from).
- Consider the site URL for such requests to be the request
initiator, when available. Otherwise, the request will always be
considered to have originated from its own URL and will therefore
always be considered a first party request.
1. Check that ServiceWorker initiated requests can be blocked, e.g. by using the test page https://privacy-test-pages.glitch.me/privacy-protections/request-blocking/

Properly handle requests initiated by ServiceWorkers

---

.github/workflows/tests.yml

The test artifacts from the MV2 integration tests are cleared when we
run the MV3 integration tests, so we should save them beforehand.
1. Check that GitHub saves the integration test artifacts successfully.

Save integration test artifacts before running MV3 tests

---

integration-test/background/storage.js
integration-test/data/configs/storage-blocking.json
package-lock.json
package.json
shared/data/bundled/extension-config.json
shared/data/etags.json
unit-test/background/reference-tests/expire-1p-tracking-cookies.js

We have recently improved first-party cookie protection to also cover
first-party cookies created by first-party scripts. Update the
content-scope-scripts dependency to include those improvements, update
the bundled extension configuration and make the corresponding changes
to the tests.
1. Navigate to https://privacy-test-pages.glitch.me/privacy-protections/storage-blocking
2. Click to start the test.
3. Using the developer tools, ensure that the cookies `jsdata`, `tptdata` and `tpsdata` have an expiry date of 7 days in the future.

Update content-scope-scripts dependency

---

shared/js/background/atb.es6.js
shared/js/background/debug.es6.js
shared/js/background/events.es6.js
shared/js/background/load.es6.js
shared/js/background/message-handlers.js

For the MV3 transition we need to move extension state that persists
for the session over to session storage. Otherwise it will be lost
when the background ServiceWorker restarts. Let's start with the
devMode flag.
1. Ensure that you can still access the `dbg` Object from the extension background page when dev build of the extension is installed.
2. Ensure that Click to Load placeholders are created with an open shadowRoot when dev build of extension is installed, but closed shadowRoot when release build of extension is installed. (You can use [the test page here](https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/).)
3. Ensure that the `test=1` parameter is added to the uninstall URL when the a dev build of the extension is installed, but …

Store devMode flag in session storage

---

integration-test/background/onboarding.js
shared/js/background/events.es6.js

When the extension is installed some onboarding messaging is displayed
the first time the user performs a DDG search. The onCommitted event
listener required for that is sometimes triggered twice in quick
succession by the browser. To avoid the onboarding messaging being
displayed twice when that happens, there were two workarounds:
1. Adding an onBeforeNavigate listener that kept track of the event's
timestamp in a local variable. onCommitted events fired before the
most recent recorded timestamp are ignored.
2. The showWelcomeBanner and showCounterMessaging settings are checked
and cleared immediately when the event is fired, so that the second
time it is fired the onboarding messaging isn't displayed.
The first approach isn't compatible with manifest V3, since state can
no longer be …

Avoid using onBeforeNavigate timeStamp for onboarding banner

---

shared/js/background/devtools.es6.js
shared/js/devtools/panel.es6.js

With Chrome MV3, the background ServiceWorker becomes inactive
periodically and any open messaging connections are
disconnected. Let's take care to reopen connections from our devtools
page when this happens, to stop the devtools page from breaking. Also,
let's  add a comment to explain why maintain the port to tabId mapping
outside of session storage is acceptable.
MV2
- Install the extension, open the options page and change URL to `devtools-panel.html`.
- Navigate to a website with trackers (e.g. news website) in a new tab, point our devtools page to the website and ensure blocked trackers etc are listed as expected.
MV3
- Build a MV3 version of the extension: `npm run dev-chrome-mv3`
- Install the extension, open the options page and change URL to …

Maintain devtools connections for MV3 builds of the extension

---

integration-test/background/request-blocking.js
shared/js/background/classes/tab.es6.js
shared/js/background/events/3p-tracking-cookie-blocking.js
shared/js/background/redirect.es6.js
shared/js/background/tab-manager.es6.js
unit-test/background/3p-cookie-serviceworker-workaround.js

Requests initiated by ServiceWorkers are given a tabId of -1, but we
still want to block tracking requests that they might make. So let's:
- Stop ignoring requests with a tabId of -1.
- Create an opaque Tab Object for those requests, but skip storing it
for later lookup (since by definition we aren't sure which tab the
request originated from).
- Consider the site URL for such requests to be the request
initiator, when available. Otherwise, the request will always be
considered to have originated from its own URL and will therefore
always be considered a first party request.
- Disable 3p cookie protections for such requests for now, since that
led to breakage (e.g. prevented Twitter users from logging out of
their accounts). That breakage led to this change being reverted
originally.
- …

Reland "Properly handle requests initiated by ServiceWorkers"

---

shared/data/web_accessible_resources/fb-sdk.js

Some websites that use the Facebook SDK check that the login status is
valid before proceeding. Let's start returning the "unknown" status
instead of just an empty string.
1. Navigate to https://nextdoor.co.uk/login/
2. Ensure the Facebook button is not greyed out and works when you click on it.

Adjust Facebook SDK "surrogate script" to return valid login status

---

integration-test/background/click-to-load-facebook.js

The Facebook Click to Load test page has recently been updated to fix
much of the broken content. That has had the knock on effect of
meaning the page takes longer to finish loading. When testing the
Facebook SDK schema, let's not wait for all requests to finish,
otherwise the chances are it will timeout.
1. Check that the Facebook Click to Load integration tests are passing (and not marked pending).

Fix the Facebook SDK schema test

---

shared/js/background/email-utils.es6.js
shared/js/background/wrapper.es6.js

When the user requests a new @duck.com email address alias, we attempt
to fetch them one. If that should fail, we will retry a few times
before giving up. So far, we kept track of the current fetch attempt
in a local variable, but for Chrome MV3 compatibility we need to move
that to session storage instead.
1. Install the extension and open the background console.
2. Open the extension settings page and click "Enable" under the Email Protection heading.
3. Complete the process to enable email protection.
4. Unplug your computer from the network, or add a `0.0.0.0 quack.duckduckgo.com` entry to your `/etc/hosts` file.
5. Click the extension icon and click "Create new Duck Address"
6. Verify that an `Error fetching new alias TypeError: Failed to fetch` message …

Put email alias fetch attempt count in session storage

---

shared/js/background/classes/site.es6.js
shared/js/background/events.es6.js
shared/js/background/utils.es6.js
unit-test/background/classes/site.es6.js

The executeScript APIs do not allow scripts to be injected into the
new tab page. This required some improvements to the code that
determines if a URL is for a new tab page, since neither
'about:newtab' nor 'https://duckduckgo.com/chrome_newtab' were being
handled correctly.
1. Open a new tab and ensure an exception about executeScript not being possible for the new tab page aren't shown.
2. Navigate to https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/ and ensure the placeholder elements are still shown and work correctly.

Avoid executing the CTL content script for the new tab page

---

shared/js/background/redirect.es6.js

We strip known tracking parameters for navigations. Sometimes it is
necessary to disable that if breakage occurs, or if the user has
chosen to disable protections for a website. Both the request URL and
the initiator URL are checked, to see if the feature is disabled, but
a typo prevented the initiator URL from being checked correctly.
For Chrome, the request initiator is in the `initiator`
property[1] (not `initiatorUrl`) and for Firefox it is in the
`originUrl` property[2]. Let's correct that here.
1 - https://developer.chrome.com/docs/extensions/reference/webRequest/#event-onBeforeRequest
2 - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest#details_2

Properly check the request initiator for tracking parameters protection

---

integration-test/background/grades.js

The privacy grade integration test for independent.co.uk was failing
since the enhanced privacy grade has changed. Adjust the expected
privacy grade to get the test passing again.
**Reviewer:** @shakyShane

Fix failing privacy grade integration test case

---

package-lock.json
package.json

**Asana:** https://app.asana.com/0/312629933896096/1202778915747370/f
Bump the autofill version to 5.0.1. No visible changes in the extensions. Most changes are for other platforms and there are also a bunch of minor improvements to form detection accuracy.
The changes have been tested extensively on other platforms and smoke tested on extensions as well. Email autofill testing steps are in https://app.asana.com/0/1198964220583541/1200583647142330/f.

Bump autofill to 5.0.1

---

integration-test/config-mv3.json
package-lock.json
package.json
shared/js/background/background.es6.js
shared/js/background/declarative-net-request.js
shared/js/background/storage/tds.es6.js
tsconfig.json
unit-test/background/declarative-net-request.js
unit-test/data/tds.json
unit-test/helpers/mock-browser-api.js
unit-test/helpers/tds.es6.js

Add Chrome MV3 tracker blocking support using the declarativeNetRequest
API and the ddg2dnr ruleset generation library[1].
Note that blocked trackers are not yet reported properly in the popup
UI or our devtools panel, though the necessary getMatchDetails API +
ruleId -> match details lookups are in place.
1 - https://github.com/duckduckgo/ddg2dnr
1. Build the Chrome MV3 extension: `npm run dev-chrome-mv3`
2. Install that in Chrome.
3. Ensure tracker blocking works (e.g. browse to a news website or [our test page](https://privacy-test-pages.glitch.me/privacy-protections/request-blocking/) and ensure requests are blocked).
4. Ensure the unit tests and MV3 integration tests pass: `npm run test` and `npm run test-int-mv3`
Note: It is expected that blocked trackers …

Add tracker blocking support to Chrome MV3 extension

---

integration-test/data/api_schemas/facebook-sdk.json
shared/data/web_accessible_resources/fb-sdk.js

**Reviewer:** @ladamski, @kzar or @sammacbeth 
It seems like this API has been removed and I can't see it in the documentation: https://developers.facebook.com/docs/messenger-platform/discovery/checkbox-plugin/
🛑  This is currently permanently failing so breaking ci.

Remove CheckboxPlugin interface from Facebook surrogate

---

shared/js/ui/views/email-alias.es6.js
shared/scss/popup.scss

**Reviewer:** @GioSensation
Task: https://app.asana.com/0/0/1202815012139664/f
Update to allow popover to scroll vertically, which will allow access to the email alias button when both it and top blocked are disabled.
1. Load extension 
1. Make sure to browse until "Top Tracking Offenders" button shows (if not already)
1. Log into email protection account
1. "Create new Duck Address" button is below the fold, but can now be scrolled to

Allow body to scroll vertically to reach email alias button

---

shared/js/background/events.es6.js

Task: https://app.asana.com/0/1162895505193104/1202817610595239/f
Allow autofill to run when site is allowlisted
1. Load this extension branch in Firefox and enable Email Protection
1. Go to https://duckduckgo.com/newsletter
1. Confirm autofill is showing and working, confirm right click context menu is showing and working
1. Disable tracking protections, page refreshes
1. Confirm autofill is showing and working, confirm right click context menu is showing and working

Enable autofill when protections are disabled

---

shared/js/background/classes/tab.es6.js
shared/js/background/classes/tracker.js
shared/js/background/redirect.es6.js
shared/js/ui/models/mixins/calculate-aggregation-stats.js
shared/js/ui/models/site.es6.js
shared/js/ui/models/submit-breakage-form.es6.js
shared/js/ui/templates/shared/grade-scorecard-reasons.es6.js
shared/js/ui/templates/shared/tracker-networks-text.es6.js
shared/js/ui/templates/shared/utils.js
unit-test/background/click-to-load-tests.js
unit-test/background/reference-tests/broken-site-reporting-tests.js

Store trackers on their blocking status to prevent missing reporting to the dashboard some trackers.
- Clean up all trackerBlocked code as had almost zero use.
- Clean up major tracker computation as we only care about their presence now rather than counting.
- Made site reporting rely on the tab.trackers data and cleaned up the computation.
- Made the test rely on construction of tab data to make it less brittle.
- Rollup urlsList as map to simplify logic
See: https://app.asana.com/0/0/1202655299377825/f

Rollup on action

---

shared/js/background/debug.es6.js
shared/js/background/events.es6.js
shared/js/background/message-handlers.js
shared/js/background/utils.es6.js

https://app.asana.com/0/312629933896096/1201066533025796/f
Changes to synced storage for the session key sent to the content script (used for psudo-randomisation)
1.  Open [several canvas draw pages](https://good.third-party.site/features/canvas-draw.html)
2. Click 'draw pattern'
3. Ensure the output is the same across the same page.
4. Open a different first party domain: https://bad.third-party.site/features/canvas-draw.html
5. Click 'draw pattern'
6. Ensure the output is different to the previous hashes.
Open the extension debugger and run _dbg.utils.resetSessionKey()_ and verify the tabs have different hashes; this simulates session key expiry via the alarm.

Sync session key via session storage

---

shared/data/web_accessible_resources/fb-sdk.js
shared/js/content-scripts/click-to-load.js

We warn the user about the privacy implications before they click to
login a website via Facebook. The modal has a "Go back" button, but so
far the website wasn't informed that the login process was
aborted. With this change, we're performing the proper callback and
since the `authResponse` property isn't provided, the website knows
the login wasn't completed[1].
1 - https://developers.facebook.com/docs/reference/javascript/FB.login/v14.0
1. Navigate to https://www.duolingo.com/?isLoggingIn=true
2. Click "I already have an account"
3. Select "Facebook"
4. Click "Go back"
5. Ensure the "Facebook" button works when clicked again (and does not display a spinner animation forever).

Inform website that Facebook login failed when user rejects it

---

browsers/chrome/manifest.json
browsers/firefox/manifest.json

We agreed to support back to the previous ESR Firefox
release[1] (currently 91) and Chrome releases for the past
year[2] (currently back to 92). We will bump these minimum version
numbers periodically in line with that policy.
1 - https://endoflife.date/firefox
2 - https://chromiumdash.appspot.com/releases?platform=Windows
**Reviewer:** @ladamski

Increase minimum supported Chrome and Firefox versions

---

shared/js/background/classes/tab.es6.js
shared/js/background/devtools.es6.js
shared/js/background/events/referrer-trimming.js
shared/js/background/helpers/arguments-object.js
tsconfig.json

The argumentsObject and referrer trimming code were failing TypeScript
linting, so linting was disabled for those files. Let's fix the
problems and enable TypeScript linting again for them.

Correct some type checking issues with referrer trimming

---

shared/js/background/utils.es6.js
unit-test/background/trackers.es6.js
unit-test/background/utils.es6.js

This fixes a regression in the ad domain detection where we expect getBaseDomain to return null when a domain provided by SERP is unparsable, but getBaseDomain will always return the hostname (even if it's nonsensical).
This is Ad 11 and Add 12 in https://www.search-company.site/
I also fixed a no-op test that we forgot to update when we first merged the bat.js work. I only detected it because I had an outdated privacy grade reference that was still returning `firstParty` when running the tests locally.

Bugfix: getBaseDomain should return null when invalid

---

shared/data/bundled/extension-config.json
shared/data/etags.json
shared/js/background/classes/ad-click-attribution-policy.js

Marking draft as CI should fail if working correcly; testCases still need amending.
This is to simplify the parsing logic as we already verify an ad click based on the adDomainParameterName parameter name in the link click.
https://app.asana.com/0/0/1202808108652811/f
Corresponding config change should probably land first so we can just run bundle-config instead of hand hacking it: https://github.com/duckduckgo/privacy-configuration/pull/345

Remove parameterName and parameterValue from ad-attribution feature to simplify code

---

integration-test/background/click-to-load-facebook.js

Occasionally the network will be too slow on the GitHub CI runner for
any Facebook requests to be made within 15 seconds. When that happens,
let's mark the tests as skipped (pending) instead of failing (or
passing).

Mark Facebook CTL tests as pending when network is too slow

---

shared/js/content-scripts/click-to-load.js

Embedded Facebook videos are created by having a div element in the page that has (amongst other attributes) a data-href attribute that specifies the video's URL. The Facebook SDK then uses that to create the video iframe. Our "surrogate script" does the same.
It turns out that when the protocol prefix of that URL isn't specified (e.g. the URL starts '//'), then the SDK and our surrogate script need to take care to add the correct protocol to the URL (e.g. 'http:' or 'https:') based on the window location. Otherwise, the video fails to load.
1. Navigate to https://forums.spacebattles.com/threads/ace-combat-7-discussion-thread.366416/page-160?post=61183897#post-61183897
2. Click to load the Facebook video.
3. Ensure it loads and can be played.

Fix Facebook videos if protocol isn't specified in data-href

---

integration-test/background/grades.js

**Reviewer:**
Reddit.com grading test is constantly failing, we're allowing all grades other than 'C+'; we should just disable as removing soon anyway.

Disable reddit test as constant flaking

---

package-lock.json
package.json
shared/js/background/declarative-net-request.js
tsconfig.json
unit-test/background/declarative-net-request.js
unit-test/helpers/mock-browser-api.js

The extension redirects requests to common third-party scripts to subbed out "surrogate scripts". We do that instead of simply blocking the third-party scripts since this way, we avoid breaking websites that assume the APIs provided by the third-party scripts will always be present.
1. Build the chrome-mv3 extension: `npm install && npm run dev-chrome-mv3`
2. Install that
3. Browse to https://www.theguardian.com/
4. Open the developer tools, switch to the "Network" panel and ensure that the following surrogate scripts are redirected: `gpt.js` and `analytics.js`.
Note: It is expected that some redirections will fail with an "net::ERR_UNSAFE_REDIRECT" error. See https://crbug.com/1361350

Add Chrome MV3 support for "surrogate script" redirections

---

shared/js/background/atb.es6.js
shared/js/background/before-request.es6.js
shared/js/background/broken-site-report.js
shared/js/background/csp-blocking.es6.js
shared/js/background/debug.es6.js
shared/js/background/declarative-net-request.js
shared/js/background/email-utils.es6.js
shared/js/background/events.es6.js
shared/js/background/message-handlers.js
shared/js/background/startup.es6.js
shared/js/background/storage/https.es6.js
shared/js/background/storage/tds.es6.js
shared/js/ui/base/ui-wrapper.es6.js
tsconfig.json

The TypeScript linter tsc is set to ignore some modules, since there
are some linting errors in those files. The problem with that (other
than missing out on the benefits of type checking), is that when one
of the ignored modules is later imported by a non-ignored module, the
previously-ignored module will start being checked again. This results
in a kind of trap where importing the wrong module suddenly results in
dozens of linting errors!
Let's improve the situation by reducing the number of ignored
modules.
One interesting linting error I hit was:
Module '"X"' declares 'Y' locally, but it is not exported.
It turned out, that was caused by modules that used CommonJS exports,
but that started with an ES import. To fix those errors, I switched
back to CommonJS imports in those situations. …

Reduce the number of files ignored by tsc linting

---

shared/js/background/atb.es6.js
shared/js/background/before-request.es6.js
shared/js/background/csp-blocking.es6.js
shared/js/background/email-utils.es6.js
shared/js/background/events.es6.js
shared/js/background/startup.es6.js
shared/js/ui/base/ui-wrapper.es6.js

**Reviewer:**
This partial reverts the changes in https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/1452 by instead exporting the CJS module.exports for TSC; this should assist our migration to ESM without having an impact.

Export for tsc as well as be CJS whilst we transition imports

---

unit-test/background/declarative-net-request.js
unit-test/background/reference-tests/3p-cookies-tests.js

The declarativeNetRequest unit tests would fail very occasionally, usually around the "surrogate script" checks. It turns out, that depending on the order the unit tests run, the shared Trackers instance would have different "lists" set and that would change the outcome of the surrogate declarativeNetRequest tests.
Generally, `Trackers.supportedSurrogates` would have the value:
```json
{
"ga.js": "data:application/javascript;base64,KGZ1bmN0aW9uKCkge30pKCk7Cmdvb2dsZS1hbmFseXRpY3MuY29tL2FuYWx5dGljcy5qcyBhcHBsaWNhdGlvbi9qYXZhc2NyaXB0CihmdW5jdGlvbigpIHt9KSgpOw==",
"sdk.js": "data:application/javascript;base64,KCgpID0+IHsKfSkoKQ=="
}
```
But occasionally[1] the value would be:
```json
{
"tracker": "data:application/javascript;base64,KGZ1bmN0aW9uKCkge3ZhciB0cmFja2VyPXRydWV9KSgpOw==", …
```

Fix test surrogate script declarativeNetRequest unit test flakes

---

.github/workflows/beta.yml
Makefile
browsers/chrome-mv3/manifest.json
browsers/chrome/manifest.json
browsers/firefox/manifest.json
package.json
scripts/bumpVersion.js
scripts/chrome-store-publish.sh
shared/data/bundled/extension-config.json
shared/data/etags.json

**Reviewer:**
https://app.asana.com/0/0/1203197597853167/f
- Set up build process for a Chrome MV3 beta build.
- Add an action that we can trigger to automatically publish a new version to the Chrome beta channel.

Chrome MV3 Beta channel

---

shared/js/background/declarative-net-request.js
shared/js/background/events.es6.js
shared/js/background/tab-manager.es6.js
unit-test/background/declarative-net-request.js

Users can allowlist (disable protections) for websites from the popup
UI and also from the options page. To make that work with Chrome MV3,
we need to add a declarativeNetRequest rule that ensures requests
initiated by domains that the user has allowlisted aren't blocked or
redirected.
**CC:** @jonathanKingston 
1. Produce a Chrome MV3 build of the extension (`npm install && npm run dev-chrome-mv3`).
2. Install that in Chrome.
3. Try allowlisting websites, both from the options page and the popup UI and ensure it works.
4. Click to reload the extension from the extensions page.
5. Make sure the websites you allowlisted are still allowlisted (try opening them in a new tab too).
6. Remove any allowlisted websites from the options page and ensure they are no longer …

Add Chrome MV3 support for user allowlisting

---

shared/js/background/devtools.es6.js
shared/js/background/events.es6.js
shared/js/background/startup.js
shared/js/devtools/panel.es6.js
shared/js/ui/base/ui-wrapper.es6.js
shared/js/ui/views/mixins/unload-listener.es6.js

The extension's popup UI allows the user to do several things,
including disabling/enabling protections for the current website.
When the user disables protections for a website, the website is added
to the allowlist. After a delay (or when the user clicks away) the
popup UI is closed and the website is reloaded automatically. Until
now, that worked by listening for the window.unload event, and then
using the chrome.extension.getBackgroundPage() API to fetch the
background page before triggering the unload function in the
background.
With Chrome Manifest v3, the getBackgroundPage() API is no longer
available and so a different approach must be used. We're now opening
a messaging connection to the background, sending through user actions
as they happen, then finally having the background …

Fix detection of popup UI close for Chrome MV3

---

integration-test/background/click-to-load-youtube.js

The YouTube Click to Load integration tests check a bunch of things, including that interacting with the YouTube Iframe API works correctly. Unfortunately, these tests fail sometimes when run inside a GitHub action since the test runner is too slow to load (or even request) the Iframe API script. When the script has failed to be requested in time, let's mark the test as pending (aka skipped) instead of declaring a failure.
1 - https://developers.google.com/youtube/iframe_api_reference

Avoid failing YouTube CTL tests when network is slow

---

shared/data/constants.js

**Reviewer:**
In #1486 we added dynamic config URLs based on the extension manifest version. However, we used a helper function from `wrapper.es6.js`, which uses es6 imports. Because `constants.js` is also loaded from node for the `bundleConfig` script, this breaks because node can't mix require and import statements.
This PR fixes it by just using the `chrome.runtime` API directly with a null check, which works on both platforms.

Fix constants when run from node.

---

shared/js/background/declarative-net-request.js
shared/js/background/events.es6.js
shared/js/background/tab-manager.es6.js
unit-test/background/declarative-net-request.js

Simplify and improve Chrome MV3 user allowlisting implementation
There was some room for improvement with the Chrome MV3 user
allowlisting implementation:
1. There was no need to recreate the user allowlisting
declarativeNetRequest rule on extension update, since dynamic
rules persist through extension updates[1].
2. The TabManager.setList() method can be called for the
"allowlisted", "denylisted" and "allowlistOptIn" events. We should
check the event is "allowlisted" before treating it as such.
1 - https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#dynamic-and-session-scoped-rules
1. Try allowlisting a website from the popup UI or the options page.

Simplify and improve Chrome MV3 user allowlisting implementation

---

shared/js/background/declarative-net-request.js
unit-test/background/declarative-net-request.js

The declarativeNetRequest onConfigUpdate listener was becoming
unwieldy. This was making future expansion tricky. For example user
"denylisting" support where the extension configuration rules also
need to be updated at the point the user denylists a website. Let's
split out some of the logic into helper functions, that can then be
reused more easily.
1. Make sure tracker blocking and the tracker blocking allowlist still work for Chrome MV3 builds of the extension.
2. Ensure the unit tests + integration tests still pass.

Refactor declarativeNetRequest onConfigUpdate logic

---

package-lock.json
package.json
shared/js/background/declarative-net-request.js
shared/js/background/tab-manager.es6.js
unit-test/background/declarative-net-request.js
unit-test/data/extension-config.json

Chrome MV3 support for contentBlocking, unprotectedTemporary and denylisting
We have added support for the contentBlocking[1] and
unprotectedTemporary[2] allowlists + and user "denylisting" in
ddg2dnr. Update the dependency, and set up the plumbing required to
pass the user denylisted domains through to the ruleset generation
code.
1 - https://github.com/duckduckgo/privacy-configuration/blob/main/features/content-blocking.json
2 - https://github.com/duckduckgo/privacy-configuration/blob/main/features/unprotected-temporary.json
1. Open the developer tools for a new tab, switch to the Network pane.
2. Navigate to welt.de and verify that no requests are blocked.
3. Click the extension icon, verify that it warns the user that protections were disabled for the page …

Chrome MV3 support for contentBlocking, unprotectedTemporary and denylisting

---

integration-test/background/request-blocking.js

The number of expected blocked requests was hard-coded in the request
blocking integration tests, which meant that they started failing when
the page was updated to make more requests. Let's make use of the test
count that we already have instead, that gets them passing again +
will hopefully avoid the same thing happening next time.
1. Check integration tests pass.

Get request blocking integration tests passing

---

shared/js/background/message-handlers.js

**Reviewer:**
Fixes an issue where cookie protections are active in iframes even when site protection is disabled. Requires consent-scope-scripts updated with https://github.com/duckduckgo/content-scope-scripts/pull/188.

Always send content scripts args - even when protections are disabled

---

integration-test/background/request-blocking.js
package-lock.json
package.json
shared/js/background/declarative-net-request.js
unit-test/background/declarative-net-request.js
unit-test/helpers/mock-browser-api.js

We already avoid blocking ServiceWorker initiated requests in the MV2
extension, since each time we enabled the blocking of those we saw
major website breakage. In the future, we'd like to start blocking
those requests again, but we'll have to do so carefully.
Anyway, it's important that request blocking is consistent between MV2
and MV3 builds of the extension. So for now, let's also avoid blocking
ServiceWorker initiated requests for Chrome MV3 builds too.
Note: The way we do this, is to ignore requests with a tabId of
-1 (aka requests not associated with a tab). This could also
lead to other requests being ignored, but since that's
consistent with the MV2 code-path[1] it seems the right approach.
1 - https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/92222c85b04894a7f411cd8 …

Avoid blocking ServiceWorker initiated requests for Chrome MV3

---

shared/html/devtools-panel.html
shared/js/background/devtools.es6.js
shared/js/background/events.es6.js
shared/js/devtools/panel.es6.js

**CC:** @kzar 
https://app.asana.com/0/312629933896096/1202714468322458/f
This adds some visual improvements to the devtools panel, to make working with it easier:
- on/off visibility
- disabled protection buttons now highlight in red, enabled in green
- current selection visibility
- when hovering over a table cell, the cell and row will be highlighted for extra visibility
- the contents of the hovered cell will expand if necessary (i.e., if the contents are cut short) to make the full contents visible
- hovering over protection buttons will also change their colour slightly to indicate the hover
- fixes colouring on `set-cookie-tracker` rows (were not highlighting before)
- updates the red colour for "blocked" to be less harsh, easier on the eyes
- adds …

Improve devtools visual elements

---

shared/js/background/before-request.es6.js
shared/js/background/events.es6.js

On tab navigate we're losing navigations of pages that are fully served by service workers. We need to model the tab data from webNavigations instead.
See: https://app.asana.com/0/312629933896096/1203403741315745/f
**STR**
1. Type into the address bar [browsersync.io](https://browsersync.io/) and enter
2. Type into the address bar [cnn.com](https://cnn.com/) and enter (in the same tab)
3. Type into the address bar [browsersync.io](https://browsersync.io/) and enter (in the same tab)
**Expected results**
- No trackers are loaded
- Some third parties
**Actual results**
- CNN trackers are shown

Fix up service worker tab navigation issues

---

integration-test/background/storage.js

**Reviewer:**
A bug in JS cookie protection caused iframe cookies to be blocked when protections were disabled for a site. This was fixed in #1534. This PR adds a test for this case.

Add test for non-blocking of iframe cookies when site allowlisted.

---

shared/js/background/message-handlers.js
shared/js/background/utils.es6.js

`browser.extension.getViews` is not supported in MV3 https://app.asana.com/0/0/1203479085724011/f
**Reviewer:** @kzar @sammacbeth 
When I updated the dashboard, I used `browser.extension.getViews()` to get access to the popup for closing it. 
This is not supported in MV3 - and actually we use the `notitfyPopup()` elsewhere already for closing, so this PR prevents us having 2 separate ways for doing the same thing 💪🏻

fix(mv3): fix reload+close following protections toggle

---

shared/js/background/broken-site-report.js

**Reviewer:**
Escaping the TDS etag value in broken site reports broke the server site parsing of the value. This PR fixes this by not piping this value through `URLSearchParams` - we add the value directly to the URL, `/` and all.
1. Submit a broken site report
2. Request from the background page should include `tds=W/%2226f3dfbb234cfd28a47af59b497e301c` in it (with `/` unescaped).

Fix encoding of TDS parameter in broken site reports

---

shared/js/background/atb.es6.js

**Reviewer:**
1. Inspect extension's background page
2. Perform a search request
3. In background page, you should see a request to atb.js with `email=0`
4. Go to https://duckduckgo.com/email and signup / login to your existing account
5. Perform search again
6. In background page, you should see a request to atb.js with `email=1`
7. Go extension Settings -> Email Protection -> Disable
8. Perform search again 
9. In background page, you should see a request to atb.js with `email=0`

Add email param to atb request

---

.github/workflows/release.yml

Set release tag explicitly, rather than implicitly tagging latest `develop` commit.

Release CI: create tag on the commit the build is run on.

---

shared/js/background/before-request.es6.js

We listen for chrome.tabs.onCreated events, to keep track of which tabs are open on which URLs. We also listen for
chrome.webRequest.onBeforeRequest events to enforce tracker blocking and other features on MV2. The onBeforeRequest code-path is also active for Chrome MV3 builds for now (but non-blocking), though the aim is to disable that in the future.
In the mean time, it turns out that while on MV2 the tabs.onCreated event fired reliably before the onBeforeRequest event for a new tab, with Chrome MV3 that is no longer the case. Let's take care to return if the current tab isn't known yet, before trying to access the tab's details.
1. Check tests are still passing.
2. Check that an exception is not logged to the background ServiceWorker …

Avoid throwing exceptions when new tabs are created for MV3

---

package-lock.json
package.json
shared/js/background/classes/tracker.js
shared/js/background/utils.es6.js

https://app.asana.com/0/0/1203197597853143/f
Attributes sites and trackers to their parents in the dashboard, where applicable.
Before             |  after
:-------------------------:|:-------------------------:

Attribute trackers to parents when defined

---

shared/js/background/declarative-net-request.js
shared/js/background/events.es6.js
unit-test/background/declarative-net-request.js

Fix user allowlist for after upgrade from MV2 to MV3 extension
When the user "allowlists" (disables protections for) a domain, we add
the domain to our user allowlisting declarativeNetRequest rule. That
works fine, but unfortunately does not consider domains that the user
allowlisted before migrating from the Chrome MV2 to Chrome MV3
extension.
We previously handled this case, since we wrongly believed dynamic
rules were lost on an extension update. We since removed the code
however[1]. Let's reapply those changes, to handle the MV2 -> MV3
upgrade case.
1 - https://github.com/duckduckgo/duckduckgo-privacy-extension/commit/8b95cd144051da4d41ae4c2fc4ed6c1f94c88915
1. Follow instructions (and use test builds) here: https://app.asana.com/0/0/1203569813824180/f

Fix user allowlist for after upgrade from MV2 to MV3 extension

---

shared/html/devtools-panel.html
shared/js/devtools/panel.es6.js

https://app.asana.com/0/312629933896096/1202714468322468/f
This:
- adds support for filtering requests on URL
- adds support for hiding _only_ 1P requests
- fixes cookie rows not being hidden by toggle
Test search filter:
1. Open http://privacy-test-pages.glitch.me/privacy-protections/request-blocking/ ("the site")
2. Open devtools panel, set target to the opened site
3. On the site, click "Start the test"
4. Switch back to the panel
5. A bunch of requests should show (about 19)
6. In the filter box, type "img" and hit enter
7. One request should now show
8. Empty the filter box and hit enter
9. All previous requests should now show
Test 1P filter:
1. Open https://www.tumblr.com/explore/trending
2. Open the devpanel and set target to opened site (note, you …

Improve devtools panel filters

---

integration-test/background/url-parameters.js
integration-test/config-mv3.json
integration-test/data/configs/url-parameters.json

Let's enable the URL tracking parameter protection integration tests
for Chrome MV3. That required a couple of small tweaks:
1. Since the "breakage flag" is not set with Chrome MV3, we needed to
disable the corresponding test case.
2. We needed to accept the URL ending with a trailing "?", since it
turns out that declarativeNetRequest query tranform rules do not
take care to remove that when removing the last parameter.

Enable Chrome MV3 URL tracking parameter protection integration tests

---

integration-test/config-mv3.json

Previously, we only enabled certain integration tests for the Chrome
MV3 manually. Since we're nearing feature parity, let's do the
opposite and only disable the failing integration tests manually.

Enable integration tests for Chrome MV3 by default

---

integration-test/background/click-to-load-facebook.js
integration-test/background/click-to-load-youtube.js
integration-test/config-mv3.json
integration-test/data/click-to-load-tds.json
integration-test/data/configs/click-to-load-youtube.json
integration-test/helpers/harness.js
integration-test/helpers/testConfig.js
shared/js/background/message-handlers.js

A lot of the Click to Load integration tests were disabled recently,
during the migration to Chrome MV3 and the new Click to Load
configuration system. While Click to Load YouTube is not yet working
correctly for Chrome MV3, let's get the other integration tests
running again.
1. Check that the integration tests are passing.

Get some of the Click to Load integration tests running again

---

shared/js/background/startup.js
shared/js/background/storage/https.es6.js
shared/js/background/storage/tds.es6.js

**Reviewer:**
In Firefox `indexedDB` can be disabled, for example with the "History -> Always use private browsing mode" setting. In this case, we fail to load our blocklists correctly, as the indexedDB exception is not caught.
This PR fixes this issue by catching the failure case, and resetting our stored etags. This means that the extension will refetch the lists every time (though the browser cache will cache it within the same session).
1. In Firefox settings enable: "History -> Always use private browsing mode"
2. Load the extension in `about:debugging`
3. Go to `about:addons` and 'Manage' the settings for this extension. Set 'Run in Private windows' to 'Allow'.
4. Check that the extension is working (popup and tracker blocking works).
5. Reload the extension and check that it …

Fix https/tds storage when indexedDB is disabled

---

Makefile

Our dev-firefox, dev-chrome and dev-chrome-mv3 Node.js "scripts" pass
the --watch=1 argument to Grunt via the Makefile. It turns out, that
with Node.js 19[1], the --watch argument is now supported by Node.js
as well. Grunt therefore starts passing that argument through to
Node.js instead, which causes the build to fail.
Let's stop passing the --watch argument for now while we figure it
out, at least that way the builds will work again.
1 - https://nodejs.org/en/blog/announcements/v19-release-announce/#node-watch-experimental
**Reviewer:** @GuiltyDolphin 
**CC:** @sammacbeth

Remove grunt --watch argument

---

package-lock.json
package.json
shared/js/background/broken-site-report.js
shared/js/background/email-utils.es6.js
shared/js/background/events.es6.js
shared/js/background/message-handlers.js
shared/js/background/pixels.js
unit-test/background/pixels.js

**CC:** @jonathanKingston @englehardt @sammacbeth 
**Depends on:** https://github.com/duckduckgo/duckduckgo-autofill/pull/242
Send pixel events when user selects Personal Duck Address or Private Duck Address in autofill popup.
Pixel names follow existing naming convention (see here: https://app.asana.com/0/0/1203215367236121/f)
```
email_filled_{main,random}_extension_{$browser}
```
Firefox is excluded (see https://app.asana.com/0/0/1203364229726655/f)
1. Setup repo together with https://github.com/duckduckgo/duckduckgo-autofill/pull/242
2. Build & load extension in Chrome
3. Go to duckduckgo.com/email and Signup/Login to email protection
4. Inspect extension's background page
5. Goto to any page where Autofill pops up, and select Private Duck Address
6. You …

Autofill pixels

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/1203789390844840/1203789390844840
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.1.2
Updates Autofill to version [6.1.2](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.1.2).
* Type consistency internally + when consumed by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/247
* Improve hybrid form UX by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/248
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/6.1.1...6.1.2

Update autofill to 6.1.2

---

integration-test/data/configs/click-to-load-youtube.json
package-lock.json
package.json
shared/js/background/message-handlers.js
shared/js/content-scripts/content-scope-messaging.js

Let's simplify the Click to Load message handlers now that the
content-scope-script migration is complete:
- Instead of passing the whole content-scope-script configuration
for Click to Load to the background and back to the content script
again, let's only pass what's required.
- Instead of handling the simple messaging and enabled/disabled
logic in the background, let's let the content script take care of
it. That should make porting the feature to other platforms
simpler.
- Combine the messages needed for to start Click to Load into one,
to reduce the back-and-forth + fix a race condition.
- Remove some now unused message handlers and rename the
"enableSocialTracker" message to "unblockClickToLoadContent".
- Remove the workaround for being passed the incorrect action to
unblock.
- …

Simplify Click to Load message handling

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/1203845335740051/1203845335740051
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.2.0
Updates Autofill to version [6.2.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.2.0).
* Send autofill pixels on macOS by @sixers in https://github.com/duckduckgo/duckduckgo-autofill/pull/249
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/6.1.2...6.2.0

Update autofill to 6.2.0

---

integration-test/background/click-to-load-facebook.js

Since we started also protecting Facebook login buttons with a
shadowRoot, the integration tests started clicking the login buttons
as well as the "Unblock ..." buttons. That caused the login overlay to
display which stopped the unblock buttons from working. In turn, that
caused the requests not to be unblocked.
1. Check the Facebook Click to Load integration tests pass, and not marked with pending "Timed out waiting for Facebook requests!".

Fix the Facebook Click to Load request integration tests

---

shared/js/background/email-utils.es6.js

Hides the Email Protection context menu item in insecure contexts, because autofill is disabled there so the button doesn't work.
1. Visit http://privacy-test-pages.glitch.me/autofill/frame-parent.html (note the `http://`)
2. Open the context menu and verify that the Email Protection autofill item is not there
3. Use the `https://` protocol
4. Verify that the context menu item is present and working

Hide Email Protection context menu in http://

---

CONTRIBUTING.md
Gruntfile.js
Makefile
package-lock.json

**Reviewer:**
- Reinstates the watch command as 'monitor' internally. No other changes needed to dev flows.
- Externally presenting it as watch=1 and 0 still.

Reinstate watch command

---

package-lock.json
package.json
shared/js/background/email-utils.es6.js
shared/js/background/message-handlers.js

**Reviewer:**
**Depends on:**  https://github.com/duckduckgo/duckduckgo-autofill/pull/243
- Run `npm install` to updates autofill
- Adds support for in-context signup saving dismissal state information
- Adds support for in-context signup firing pixel data
- In-context signup depends on `incontextSignup` being in the enabled features
- https://github.com/duckduckgo/privacy-configuration/pull/674
1. Build extension (~make sure to enable `incontextSignup` as a feature~ -- already added to features)
2. Go to web page with email field, e.g. https://duckduckgo.com/newsletter
3. Confirm in-context signup tooltip shows
- This can be used to sign up or log in to an Email Protection account
- This can be dismissed, and disappears completely on the second dismissal
---
- To see the specific tasks …

Add Email Protection in-context signup support

---

.github/workflows/release.yml

**Reviewer:**
Make a full release when running the release pipeline.
This change is because, when we create a draft release, the tag is only created when someone publishes that draft. This means that, unless the draft is published immediately, the tag will be incorrect. This is especially problematic when we use the Github release to download source for extension release, as if the tag commit is wrong, it will not reproduce the same build.

Do not create release as draft

---

shared/js/background/dnr-click-to-load.js
shared/js/background/message-handlers.js
shared/js/background/utils.es6.js

Remove some more old Click to Load code
In the past, we needed to disable the Click to Load feature for
Firefox versions <= 88. Since our minimum supported version is now
91[1], this check can be removed.
Also, the deprecated clickToLoadClicks field has been removed[2] from
the "getClickToLoadState" response handler in content-scope-scripts,
so that can be removed too.
1 - https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/3a23810d164e9bd17823d0cecc79f7731a8290ce/browsers/firefox/manifest.json#L6
2 - https://github.com/duckduckgo/content-scope-scripts/commit/cec60d47bd0c6881ddb9b0643d40f9a5efef1e29#diff-658f5706013e4033baa9dd3e8885fcbd34cf73ea331a3bfd34764a39b0d0186aR1317-R1318
1. Check Click to Load still works (e.g. on [the Facebook test …

Remove some more old Click to Load code

---

integration-test/config-mv3.json

The Click to Load YouTube integration tests do not yet work for Chrome
MV3 builds of the extension. Unfortunately, while migrating our
integration tests to Playwright, we introduced a typo that started
the tests running anyway. Let's fix that typo, so the tests don't keep
running and failing.

Fix typo in integration test configuration

---

package-lock.json
package.json
shared/js/background/dnr-config-rulesets.js
unit-test/background/declarative-net-request.js

Since the ddg2dnr library does not enforce "minSupportedVersion"
option for features in the extension-config.json configuration, let's
take care to remove disabled and unsupported features from the
configuration before passing it to ddg2dnr.
**Cc:** @jdorweiler

Ensure only enabled+supported feature configs are passed to ddg2dnr

---

integration-test/helpers/requests.js

It turns out that if the extension blocks a request, but then replaces
the corresponding element very quickly afterwards, Puppeteer will
report the request as 'net::ERR_ABORTED' instead of
'net::ERR_BLOCKED_BY_CLIENT'. Let's consider both as blocked, for the
purposes of the integration tests.
**CC:** @ladamski 
1. just check that the Click to Load integration tests still work.

Improve logPageRequests integration test helper

---

integration-test/config.json
package-lock.json
package.json
shared/js/background/before-request.js
shared/js/background/click-to-load.js
shared/js/background/dnr-click-to-load.js
shared/js/content-scripts/content-scope-messaging.js

Historically, the Click to Load placeholders were only drawn once at
the point page load completed. That had two problems:
1. Sometimes placeholders would take too long to display, if the page
took a long time to load fully.
2. Sometimes placeholders would not be displayed at all, if the
blocked content was only created after page load had finished.
To fix that, let's send a message to the content-scope-script to
ensure that placeholders are refreshed each time a Click to Load
request is blocked.
Also tweak the response messages to be inline with the recent
content-scope-script changes to make response messages easier to
identify.
Unfortunately the YouTube Click to Load integration tests need to be
disabled for now, since we had to disable the "hideTrackingElement"
option for now which …

Trigger refresh of Click to Load placeholders on request block

---

integration-test/data/configs/click-to-load-facebook.json
integration-test/data/configs/click-to-load-youtube.json
package-lock.json
package.json
shared/js/background/click-to-load.js
unit-test/data/extension-config.json

Initially the Click to Load feature was misnamed "clickToPlay". Also
the Facebook entity name was inconsistently called either "Facebook"
or "Facebook, Inc.". We have corrected those the extension
configuration, content-scope-scripts and the reference tests. Let's
update those dependencies and make the necessary extension changes
here.
**CC:** @kdzwinel 
1. Ensure the unit tests still pass.
2. Ignore if Facebook integration tests are marked pending, Sam has a follow-up to switch to Playwright for those.
3. Edit the configuration and check the "clickToLoad" feature controls Facebook/YouTube Click to Load, instead of the "clickToPlay" feature.
4. Smoke test Click to Load still works.

Switch Click to Load to the "clickToLoad" feature name

---

Makefile

**Reviewer:**
Fixes an issue since #1735 when developing with content-scope-scripts. This change limits what gets copied to `shared/content-scope/scripts` so this doesn't pollute the workspace and break other build targets.
Note, you may need to run `make clean` to remove your existing `shared/content-scope-scripts` folder for this change to fix your local copy.
1. `npm ci`
2. `cd /path/to/content-scope-scripts && npm ci && npm link`
3. `cd /path/to/extension`
4. `npm link @duckduckgo/content-scope-scripts`
5. `npm test`
6. `npm run dev-chrome`
These steps should complete as expected with no errors.

Fix C-S-S copy step to avoid copying unnecessary files.

---

Makefile

Let's have Browserify generate source maps again for development
builds, they make debugging the code a lot easier. But let's keep them
off for production builds, since the background.js bundle grows from
~2 MB to ~5 MB when we add them.

Fix source maps for development builds

---

Makefile

The Makefile is set up to notice changes to the code, rebuilding as
necessary. Let's also have it watch for changes to our other
repositories (under node_modules/@duckduckgo/) and repositories that
have been combined with this one (under packages/).
1. Run `make dev browser=chrome type=dev` twice.
2. It should say "make: Nothing to be done for 'dev'."
3. Edit a file under `packages/privacy-grade` or `node_modules/@duckduckgo/*`
4. Run `make dev browser=chrome type=dev` and ensure the bundles are rebuilt.

Ensure Makefile notices changes to our other repositories

---

Makefile

It turns out that including packages/privacy-grade/node_modules caused
builds to break on macOS when some temporary Puppeteer files were
included by mistake. Let's exclude node_modules for packages/.

Avoid Make watching for changes to packages/*/node_modules

---

Makefile

It turns out that Browserify does not follow symlinks for `--global
--only ...`. Let's fix that by passing it a list of the symlinked
targets.
1. Point the content-scope-scripts directory to a local path in package.json, e.g. `"@duckduckgo/content-scope-scripts": "../content-scope-scripts",`
2. `make clean`
3. `npm run test`
4. Ensure tests build and run OK. (Without this change, bundling should fail.)

Fix importing ES Module imports when our other repositories are symlinked

---

Makefile

The manifest.json target in the Makefile copied the locales/ directory
for the chrome target. That clashed with the $(BUILD_DIR)/_locales
target, causing the first chrome build to fail after a `make clean`.
Another issue, was that for chrome-mv3 target some of the required
directories weren't ready in time for the first build after a `make
clean`.
These targets probably need to be tidied up, but as a workaround let's
ensure that only the browsers/BROWSER/*.json files are copied for the
manifest.json target, and that the prerequisite directories are
created for the other problematic targets.
1. `make clean && make dev browser=chrome type=dev`
3. `make clean && make dev browser=chrome-mv3 type=dev`
5.  Ensure builds are created first time, …

Fix Chrome build targets after make clean

---

.gitignore
Makefile
browsers/chrome-mv3/managed-schema.json
package.json

The Makefile had an issue whereby copied files were not re-copied when
they were updated. This could cause builds to contain out of date
files.
While I was fixing that, I decided to refactor/tidy the Makefile:
- Grouped all top-level targets together at the start of the Makefile.
- Added some missing comments.
- Used whitespace more consistently.
- Moved some out of place targets into the correct section.
- Added missing .PHONY target dependencies.
There is more work to do, in particular it would be nice to use
automatic dependency generation (e.g. `browserify --list`) in order to
reduce regeneration of the bundles.
1. Check build outputs are identical.
2. Check when files are changed (e.g. shared/data/constants.json) they are copied again …

Tidy up the Makefile and ensure updated files are copied again

---

package-lock.json
packages/privacy-grade/package.json

The privacy-grade tests were using an ancient puppeteer version, but we can't upgrade to the latest without breaking our extension integration tests. We can just remove puppeteer from the privacy-grade `package.json` so it will inherit the version that the extension uses.

Use parent puppeteer version in privacy-grade

---

Makefile
shared/js/background/devbuild-reloader.js

1. Fix the build/ path in `make clean`, since the browser + type
variables shouldn't be used there.
2. Ensure build-locales is run before build-$(browser) when rebuilding
the content-scope-scripts repository.
3. Ensure the reloader keeps checking when unpacked extension
directory is cleared. That way, it will reload on next build.
1. Run `make clean browser=foo type=bar` and check that the build directory is still removed correctly.
2. Point package.json at a freshly cloned local copy of content-scope-scripts, run `npm install` for the extension and `npm run dev-chrome` and ensure the build succeeds.

Squash three more bugs in the Makefile

---

Makefile

The $(BUILD_DIR)/buildtime.txt target in the Makefile depends on
the $(BUILD_TARGETS) variable, and so it must come after the other
build targets have been created and the variable updated.
Also, the $(BUILD_DIR)/data/surrogates.txt target should depend on the
source surrogate scripts as well as the target surrogate
scripts. That way, incremental builds after a surrogate script change
will take care to regenerate surrogates.txt immediately, instead of
the next time around (after the files have been copied into the build
directory).
**CC:** @sammacbeth @jonathanKingston 
**Depends on:**

Ensure surrogates.txt is rebuilt before buildtime.txt

---

scripts/asana-release.js

Updates the release asana script to:
- Put the release task in the "Extension Releases" section of the project.
- Add the version number to the 'Release version' field of PR tasks. This indicates which extension version this PR change will land in.
- Adds another `Asana-Enable` header to disable `new_goal_memberships` warnings.

Set release version in Asana when preparing release task

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.4.3
Updates Autofill to version [6.4.3](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.4.3).
- Remove manual server setup in tests by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/289
- Add windows release automation by @szanto90balazs in https://github.com/duckduckgo/duckduckgo-autofill/pull/272
- Fix extension release flow by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/294
* Update Asana integration to include expected header by @alistairjcbrown in https://github.com/duckduckgo/duckduckgo-autofill/pull/295
- Set tooltip initial offscreen position by @alistairjcbrown in …

Update autofill to 6.4.3

---

Makefile

There was a bug in the Makefile, whereby `make clean` would run
`rm -rf $(BUILD_DIR)` which usually resulted in `rm -rf build//` being
run. By happenstance this worked, clearing the build directory. I
fixed that, by changing the script to run `rm -rf build` directly.
However, it turns out that the release target also runs `make clean`,
but with the BUILD_DIR variable set correctly. It expected only the
targetted build to be cleared, so when the whole build directory was
cleared instead the release process failed.
For now, let's revert that change, to unblock today's release. In the
future, we should handle this properly.

Revert recent change to clean target in Makefile

---

shared/js/background/dnr-service-worker-initiated.js
unit-test/background/declarative-net-request.js

ServiceWorker initiated request blocking can often cause problems, so
we gate that behind the "serviceworkerInitiatedRequests"
feature. Unfortunately however, we did not disable the blocking for
MV3 builds properly. Let's fix that here.
See https://crbug.com/1421697

Fix disabling of ServiceWorker initiated request blocking for MV3

---

Makefile

For Chrome MV3 builds, we need to fetch a list of domains that are
then used to generate a "Smarter Encryption" (HTTP -> HTTPS upgrade)
declarativeNetRequest ruleset. We were writing that list of domains as
a text file in the source tree, but that was confusing and could cause
a second incremental build to be triggered during development.
Let's save that text file in the build directory instead, that way
it's clearer, we avoid triggering builds twice and we can remove
the rsync exception.
1. Run `make clean`
2. Run `make dev browser=chrome-mv3 type=dev` and ensure `build/chrome-mv3/dev/data/bundled/smarter-encryption-rules.json` was created OK.
3. Run `make dev browser=chrome-mv3 type=dev` and ensure it reports "make: Nothing to be done for 'dev'."

Avoid triggering Chrome MV3 builds twice

---

integration-test/request-blocking.spec.js

Ensure ServiceWorker initiated request blocking is enabled before
running the request blocking integration tests. Otherwise, the tests
start failing if we disable it in the extension configuration.
**Reviewer:**

Fix request blocking integration tests for Chrome MV3

---

packages/privacy-grade/src/classes/trackers.js

Rewrite has caused variable to be missing causing unknown trackers to not be shown.
https://app.asana.com/0/home/1199237043596759/1204287107601468
Fixing the type for this being optional would have caught this. As we don't have tests here this seems like the next best thing.

Fix shadowed variable rewrite issue preventing unknown trackers from being shown

---

Makefile

We have a problem that sometimes surrogates.txt will be generated
early, before the surrogate scripts are copied into the build
directory. That causes surrogates.txt to be empty/invalid, and
also causes a second incremental build to run during
development. Let's just have the surrogates.txt target depend on
LAST_COPY instead. The cost of regenerating the file unnecessarily for
incremental builds seems worth generating it reliably.
Ideally, we would have targets for all copied files in the
Makefile, and then we could set proper dependencies for the
surrogates.txt target to ensure it's only regenerated when the
surrogate scripts have changed. In practice though, we have a
LAST_COPY target that represents all the file copying.
1. Run `make clean`
2. Run `make dev browser=chrome-mv3 type=dev` …

Ensure surrogates.txt target is triggered each time files are copied

---

packages/privacy-grade/package.json

Bumps the version to match the last tag on the original privacy-grade repo.

Bump privacy-grade version

---

shared/js/background/broken-site-report.js
shared/js/background/message-handlers.js
unit-test/background/reference-tests/broken-site-reporting-tests.js

Updates the reference test plumbing to support the new breakage reference tests. See https://github.com/duckduckgo/privacy-reference-tests/pull/83.
Asana: https://app.asana.com/0/0/1204319236595708/f
Broken site reporting reference tests against https://github.com/duckduckgo/privacy-reference-tests/pull/83 should pass.

Update reference test integration to support new breakage reference tests

---

packages/ddg2dnr/lib/temporaryAllowlist.js
packages/ddg2dnr/test/ampProtection.js
packages/ddg2dnr/test/temporaryAllowlist.js
packages/ddg2dnr/test/trackerAllowlist.js

The contentBlocking "feature" in the configuration is primarily used
to disable tracker blocking (and a few related features) for domains
where users report breakage. During debugging/development however,
sometimes the feature is disabled entirely to disable those features
for all websites. Let's take care to generate the correct allowing
rule for when the contentBlocking feature is disabled entirely.
1. Ensure requests are blocking for Chrome MV3 builds on the test page: http://privacy-test-pages.glitch.me/privacy-protections/request-blocking/
2. Disable the contentBlocking feature entirely in the extension config.
3. Refresh the test page, and ensure requests are no longer blocked.

Ensure contentBlocking "feature" is properly disabled for MV3 builds

---

shared/js/background/email-utils.js

**Reviewer:** @sixers 
No longer update `lastUsed` when firing the autofill shown pixel.
1. Open the background script devtools on the Network tab
2. With autofill enabled, open the tooltip on a page, for example https://privacy-test-pages.glitch.me/autofill/modal.html
3. Note the `duck_address_last_used` parameter (it should not be today)
4. Open the tooltip again. The parameter should stay the same
5. Now select an address
6. Open the tooltip again. The parameter should now be set to today

Autofill shown should not update lastUsed

---

Makefile

**Reviewer:**
In #1903 I missed that we need `woff2` fonts for autofill. This PR re-adds those fonts.
1. Load a page where autofill is triggered.
2. Check that the ProximaNova font is loaded correctly in the popup.

Re-add fonts for autofill

---

shared/js/background/message-handlers.js

Task: https://app.asana.com/0/0/1204498944638779/f
Make the period of time in which in-context signup is visible configurable through the remote config. This value is currently not in place and so the value will default back to the current value of 3.

Control how long in-context signup is visible through remote config

---

.github/workflows/checks.yml
Makefile
integration-test/click-attribution.spec.js
integration-test/helpers/playwrightHarness.js
integration-test/helpers/testPages.js
playwright.config.js

Seperated from #1939 because this migration was a bit more complex.

Migrate click attribution tests to Playwright

---

integration-test/amp-protection.spec.js

Avoids loading the entire page for AMP page tests - once the navigation is committed, we can check the URL is correct.

Speed up AMP protection tests

---

integration-test/url-parameters.spec.js

The URL tracking parameter protection tests should make use of the
test url-parameters.json configuration. It seems that got missed when
we ported the test to Playwright. Let's fix that here, to get those
tests passing more reliably again.
1. Check URL tracking parameter protection integration test is passing.

Use test configuration for URL tracking parameter protection tests

---

shared/js/background/url-parameters.js

**Reviewer:** @jonathanKingston @kzar 
This fixes url param stripping when parameters aren't properly percent decoded. Note I've also removed code that deals with Regex parameters as we no longer have these in our lists.
Make sure to enable queryParameters in your local config.
Check the tests here: https://privacy-test-pages.glitch.me/privacy-protections/query-parameters/
---
- https://app.asana.com/0/0/1204621210866535

Fix percent encoding errors for param stripping

---

integration-test/data/staticcdn/trackerblocking/config/v2/extension-chromemv3-config.json
integration-test/request-blocking.spec.js
shared/js/background/dnr-service-worker-initiated.js
shared/js/background/tab-manager.js
unit-test/background/declarative-net-request.js

**Reviewer:**
Fixes syncing allowlist changes to serviceworker tabs.
1. go to https://privacy-test-pages.glitch.me/privacy-protections/request-blocking/
2. disable protections
3. run test
4. 'serviceworker-fetch' should be allowed.

Fix allowlisting does not disable serviceworker request blocking in the same session

---

shared/data/constants.js

#1989 regressed the `bundle-config` script, as `chrome` is missing when running in node. This PR fixes that.

Allow constants.js to be used in non-extension environments

---

shared/js/background/events.js
shared/js/background/message-handlers.js

Adds an explicit default export from `message-handlers.js` that contains the default set of message handlers. We then also export a function that allows new handlers to be registered.
This will enable us to move handlers out of the central message handler file, and register handlers per-feature.

Allow message handlers to be registered dynamically

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/7.1.0
Updates Autofill to version [7.1.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/7.1.0).
* Tons of form fixes by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/322
* Email Protection for Windows + Windows compatibility patches by @greyivy in https://github.com/duckduckgo/duckduckgo-autofill/pull/323
* Fix form submission overtriggering by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/324
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/7.0.1...7.1.0
This release has been tested during autofill development. For smoke test steps see [this …

Update autofill to 7.1.0

---

shared/js/background/email-utils.js

**Reviewer:**
**Related task:** https://app.asana.com/0/0/1204132671693381/f
Remove support for temporary pixel `email_incontext_eligible` now that it's no longer needed
This change can land as-is, but there's a complementary Autofill PR: https://github.com/duckduckgo/duckduckgo-autofill/pull/330

Remove in-context eligible pixel

---

package-lock.json
shared/js/background/tracker-utils.js
unit-test/background/tracker-utils-tests.js

We're removing the eTLD+1 referrer trimming feature for breakage and party reasons.

Do not strip subdomains when referrer trimming

---

integration-test/atb.spec.js

**Reviewer:**
ATB search workflow tests are reliably flaky on CI. Fixing them will make CI faster.

Reduce atb test flakiness.

---

shared/js/background/broken-site-report.js
shared/js/background/classes/tab-state.js
shared/js/background/classes/tab.js
shared/js/background/message-handlers.js
shared/js/content-scripts/content-scope-messaging.js
unit-test/background/classes/tab.js

We'd like to get a better idea about how often the Facebook Click to
Load feature causes problems for users. We're adding "breakage flags"
to that end, which are included when a user reports a broken webpage.
**Reviewer:** @franfaccin 
**Depends on:** https://github.com/duckduckgo/content-scope-scripts/pull/610
1. Build extension, taking care to include linked content-scope-scripts changes.
2. Open developer tools for extension background page, switch to network panel.
3. Test sending breakage reports, then inspect the sent reports using the networks panel.
4. Check that `ctlFacebookPlaceholderShown` breakage flag is only set to true if there was a placeholder shown on the page. And that `ctlFacebookLogin` is only set to true if the user has clicked a login button (even if they then abort …

Add Facebook Click to Load breakage flags

---

.github/workflows/checks.yml
.github/workflows/ddg2dnr.yml

**Reviewer:** @shakyShane @sammacbeth @kzar 
The ddg2dnr workflows were running twice at each push for open PRs. This should fix it 💪.
Note: the release checks run twice because they run on different machines (ubuntu + macOS). Not sure why that is needed, but apparently it's intentional, so I'll leave it be.
Just check the workflow widget down below. The 2 ddg2dnr steps should only run once. The total number of checks is now 17 vs the previous 19.

Improve workflow efficiency

---

Makefile

Sourcemaps tip the size of `background.js` to over 4mb, which the Firefox addon store refuses to analyze. Let's revert to only including source maps in dev builds.

Only ship sourcemaps in dev builds

---

browsers/chrome-mv3/manifest.json
browsers/chrome/manifest.json
integration-test/fire-button.spec.js

This will allow us to submit to stores without having to submit justifications for these APIs before we're actually using them.

Remove Fire button permissions until we ship.

---

unit-test/background/newtab-tracker-stats.js
unit-test/helpers/mock-browser-api.js
unit-test/inject-chrome-shim.js

Fixes an issue where we can't spy on `browserWrapper.syncToStorage` when using ESBuild to bundle the tests.

Move newtab-tracker-stats tests to esbuild

---

Makefile
shared/js/background/storage/https.js
unit-test/background/checksum.js
unit-test/background/storage/checksum.js
unit-test/background/storage/https.js

- The code to check the checksum of HTTPs bloom filters was disabled after we stopped including a `Buffer` polyfill.
- This also prevented us migrating the test for this to ESBuild.
- This PR replaces the `Buffer` usage for browser-compatible JS, so we can reenabe this check, and move the https test out of the legacy folder.

Fix checksum code for browsers

---

shared/js/background/classes/site.js

- After clearing tabs from with the fire button, the privacy dashboard was showing a 'normal' view, rather than the 'special page' view we expect for the new tab page.
- Due to the way the redirect to the NTP happens in this case, we were picking up the URL with ATB params included.
- Our 'special page' detection code expected an exact match, so this URL wasn't detected as 'special'.
- This PR makes the matching accept parameters on the NTP url.

Also treat new tab page with ATB params as 'special'

---

shared/js/background/broken-site-report.js
shared/js/background/classes/tab-state.js
shared/js/background/classes/tab.js
shared/js/background/message-handlers.js
shared/js/content-scripts/content-scope-messaging.js
unit-test/background/classes/tab.js

**CC:** @jonathanKingston 
**Depends on:** https://github.com/duckduckgo/content-scope-scripts/pull/648
MVP infra for generic debug flags for C-S-S features. This is not yet a full Messaging implementation, which should come in later stages of the project.
0. Add a log to the breakage report, or set up a proxy to see the breakage pixel URL
1. Build the extension with C-S-S changes from https://github.com/duckduckgo/content-scope-scripts/pull/648
2. Open any page with enabled protections (e.g. example.com)
3. Trigger the protections:
- `navigator.hardwareConcurrency`
- `(await navigator.getBattery()).charging` (Chromium only)
4. Send a breakage report form
5. Verify that `debugFlags` parameter is present in the pixel URL
---
- To see the specific tasks where the …

Handle debug flags sent from C-S-S

---

CONTRIBUTING.md
Makefile
package.json
packages/ddg2dnr/README.md
packages/ddg2dnr/cli.js
scripts/bundleConfig.mjs
scripts/fetchMV3Blocklists.mjs
scripts/generateListOfSurrogates.js
scripts/updateMV3Blocklists.mjs
scripts/utils.mjs
shared/data/etags.json

Generate static MV3 rulesets for tracker blocking
So far, we have managed to keep the necessary declarativeNetRequest
rules for tracker blocking and related features to below the 5,000
dynamic rule limit[1]. However, as we expand the block list and our
protections, the limit is approaching. At the time of writing we're up
to around 4,000 dynamic rules, and that is trending upwards.
Furthermore, for our Safari MV3 port, we will need even more rules for
our protections, since rule conditions such as requestDomains and
excludedRequestDomains are not yet supported.
Therefore, we're going to move to static declarativeNetRequest
rulesets for tracker blocking. As a first step, let's set up the
instrumentation to fetch and update the current/fallback[2] blocklists,
and to generate the …

Generate static MV3 rulesets for tracker blocking

---

integration-test/helpers/testConfig.js
integration-test/storage-blocking.spec.js
playwright.config.js

- In some integration tests we patch the config object stored in `tdsStorage` directly.
- For MV3, we might not catch this config change unless the config updated event is fired.
- This PR triggers this event manually after patching, so MV3 rules will be correctly generated.
- This should fix some intemittent test failures, where config patches weren't picked up.

Force trigger config reload when patching config in tests

---

integration-test/atb.spec.js
shared/js/background/atb.js
unit-test/background/atb.js

Add counteract experiment atb allocation
**Reviewer:**
@sammacbeth @sballesteros 
Allocates users who installed the extension but haven't been assigned any atb into the counteract experiment.
1. `npm run dev-chrome`
2. In Chrome, install the extension (the dev version), wait for extension-success page to open, verify that either `atb=v388-2vk` or `atb=v388-2vj` is present in the URL.

Add counteract experiment atb allocation

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.1.2
Updates Autofill to version [8.1.2](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.1.2).
* Ema/fix script naming by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/364
* Minor fixes by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/365
* Send a breakage report flag when autofill is "activated" on the page by @muodov in https://github.com/duckduckgo/duckduckgo-autofill/pull/363
* Fix extension bugs by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/366
* Add regression test by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/367
* @muodov made their first contribution in …

Update autofill to 8.1.2

---

.github/dependabot.yml

Fixes #2201 : `patterns` is required.

Fix dependabot grouping syntax

---

shared/js/background/classes/site.js

When recreating a Site object with an existing TabState object, we were not resetting allow- and deny-list values when the URL changed. This means that an allowlisted site would have that state persisted to other sites after a navigation.
We can fix this by force setting the value to false when creating the Site object.

Force set list values to false on Site initialization

---

shared/js/background/amp-protection.js

See https://app.asana.com/0/414235014887631/1205292391529323/f for context.
This PR enforces strict checking for http links in AMP protection. Deep extraction has been updated to check if the extracted link is http and discards it otherwise. However deep extraction is currently disabled in the extension. I've made the same update to the simple link extraction case for google.com domains. For instance https://www.google.com/amp/s/javascript://example.com should redirect to a 404 page.
1. Smoke test this page: https://privacy-test-pages.glitch.me/privacy-protections/amp/
2. Check https://privacy-test-pages.glitch.me/privacy-protections/amp/ redirects to a 404 page.

Update AMP protection with strict http checking

---

shared/js/devtools/panel.js

This prevents https://github.com/duckduckgo/content-scope-scripts/pull/710 from breaking the devtools panel.

Move cookie stack trace extraction to the devtools.

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.3.0
Updates Autofill to version [8.3.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.3.0).
* Update password-related json files (2023-08-30) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/378
* Speed up tests and other perf improvements by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/381
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/8.2.0...8.3.0

Update autofill to 8.3.0

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.4.0
Updates Autofill to version [8.4.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.4.0).
* Improve non-English matching by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/374
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/8.3.0...8.4.0

Update autofill to 8.4.0

---

shared/js/background/helpers/arguments-object.js

- Due to referrer-trimming feature changes, we no longer need to send a `referrer` attribute with the arguments we sent to the content script.
- This PR removes that.
- Depends on https://github.com/duckduckgo/content-scope-scripts/pull/645

Remove unused referrer attribute on arguments object

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.4.1
Updates Autofill to version [8.4.1](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.4.1).
* Precompile regexes by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/382
* Add perf tests by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/383
* deps: remove deprecated content-scope-utils by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/384
* Update dependencies by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/368
* Fix perf regressions by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/385
**Full Changelog**: …

Update autofill to 8.4.1

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.4.2
Updates Autofill to version [8.4.2](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.4.2).
* Ema/perf followups by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/386
* Fix handler regression by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/392
* Bump markdown-it from 13.0.1 to 13.0.2 by @dependabot in https://github.com/duckduckgo/duckduckgo-autofill/pull/388
* Revert mutation observer for forms by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/396
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/8.4.1...8.4.2
This release has been tested during autofill development. …

Update autofill to 8.4.2

---

integration-test/atb.spec.js
shared/js/background/atb.js
unit-test/background/atb.js

**Reviewer:**
@jonathanKingston 
Removes code added in https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/2145, https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/2160, 
- Close any tabs for duckduckgo.com
- Build + install extension
- Post-install page (/extension-success) should open
- Confirm that no ATB letters are part of the `atb=` value

Remove Chrome Counteract Exp code

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/9.1.0
Updates Autofill to version [9.1.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/9.1.0).
* Re-enable mutObs with better safeguards by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/403
* Bump zod from 3.22.2 to 3.22.4 by @dependabot in https://github.com/duckduckgo/duckduckgo-autofill/pull/395
* Workaround for pcsretirement by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/406
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/9.0.0...9.1.0 …

Update autofill to 9.1.0

---

Makefile
browsers/chrome-mv3/manifest.json
browsers/chrome/manifest.json
browsers/firefox/manifest.json
integration-test/atb.spec.js
shared/js/background/atb.js
shared/js/background/events.js
shared/js/background/wrapper.js
shared/scss/noatb.scss
unit-test/background/atb.js

**Reviewer:**
We're not using this CSS rule for extension detection anymore. Removing it fixes a race condition on extension install in Firefox.
Asana: https://app.asana.com/0/892838074342800/1205807960803986/f
1. In Firefox, visit https://duckduckgo.com/ (extension not installed)
2. Click 'Add DuckDuckGo to Firefox', then cancel the install prompt.
3. Check the `natb` value in the URL bar.
4. Now go to `about:debugging` and install the extension.
5. When the postinstall page opens, check that the `atb` value matches `natb` from step 3.

Remove noatb.css.

---

shared/js/background/broken-site-report.js
unit-test/background/reference-tests/broken-site-reporting-tests.js

https://app.asana.com/0/0/1205842954277156/f
Parent Task: https://app.asana.com/0/72649045549333/1205644489547731/f
**Description**:
Adds a new parameter to breakage form submissions.
**Steps to test this PR**:
1. submit the form breakage form
2. verify that the param `protectionsState` has either a "0" or "1" value based on the rules mentioned in the Asana task.

adding protectionsState to breakage form

---

shared/js/background/broken-site-report.js
unit-test/background/reference-tests/broken-site-reporting-tests.js

https://app.asana.com/0/0/1205915950517975/f
**Reviewer:** @GuiltyDolphin @sammacbeth 
Switching to true|false instead of 1|0 for cross-platform consistency. See the parent task https://app.asana.com/0/1201141132935289/1205644489547731

switch to true|false for protectionsState param

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.0
Updates Autofill to version [10.0.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.0).
* Don't call getAvailableInputTypes from topFrame by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/411
* Super small fix by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/412
* Send getRuntimeConfiguration to native on macOS by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/379
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/9.1.0...10.0.0
This release has been tested during autofill development. For smoke test steps see [this …

Update autofill to 10.0.0

---

integration-test/data/staticcdn/trackerblocking/config/v2/extension-chromemv3-config.json
integration-test/navigator-interface.spec.js
shared/data/bundled/extension-config.json
shared/js/content-scripts/content-scope-messaging.js

The navigator-interface test is often flakey on MV3. This seems to be because, on a slow machine, extension startup and content-script registration are slow. The means that we actually load the test page before the content-scripts are registered.
Now that we exposed MV3 content-script registration via a component, we can wait for that to complete before loading the test page.

MV3: Request content-script config on first tick

---

shared/js/background/events.js

We're missing some errors that happen at navigation time. See https://app.asana.com/0/inbox/1199237043596759/1205948701794778/1205968619180325/f

Add web navigation errors to breakage reports

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.1
Updates Autofill to version [10.0.1](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.1).
* Tweak pulldown menu copy on desktop by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/433
* Update password-related json files (2023-12-06) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/434
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/10.0.0...10.0.1

Update autofill to 10.0.1

---

packages/ddg2dnr/package.json

I noticed that the reference-test version in ddg2dnr was out of sync with the parent project. Removing it from ddg2dnr's package.json will cause the version to be inherited from the extension.

ddg2dnr: share reference-tests dependency version with parent project.

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.2
Updates Autofill to version [10.0.2](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.2).
* Copy change by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/443
* Update password-related json files (2023-12-13) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/442
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/10.0.1...10.0.2

Update autofill to 10.0.2

---

shared/html/list-editor.html
shared/js/devtools/list-editor.js

**Reviewer:**
@sammacbeth 
**CC:**
@GuiltyDolphin 
The current list editor is functional, but to make it easier to use should have a better UI.
This PR uses the existing extension styles (in `base.css`) and replaces the list chooser dropdown with tabs, to save clicks.
See internal task: https://app.asana.com/0/0/1206280121954707/f
1. Once built, open `list-editor.html`
2. Check that the tabs change the textarea content.
3. Check that the buttons still work, e.g. remote file is loaded.

Update list editor with tabs and improved UI

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.3
Updates Autofill to version [10.0.3](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.3).
* Use the default branch when checking out repos by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/444
* Password update flows by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/453
* Bump @types/jest from 29.5.5 to 29.5.11 by @dependabot in https://github.com/duckduckgo/duckduckgo-autofill/pull/439
* Update password-related json files (2023-12-21) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/454
* Move test forms out of src by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/457
* …

Update autofill to 10.0.3

---

shared/js/background/background.js
shared/js/background/components/omnibox-search.js
shared/js/background/events.js

**Reviewer:**
Guards our use of `browser.omnibox` so the extension doesn't crash when this API is missing. This is the case in Firefox on Android and for Safari MV3 extensions.
I've also moved this code into its own component, as part of ongoing work to clean up `events.js`.

Prevent extension crash when omnibox API is not available.

---

shared/js/background/components/README.md

Readme to describe 'components' and how they should be used.

Add readme for components directory.

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.1.0
Updates Autofill to version [10.1.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.1.0).
* Support shadow dom by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/485
* New batch of fixes + integration test improvements by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/489
* Update password-related json files (2024-01-17) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/474
* Bump playwright from 1.38.1 to 1.40.1 by @dependabot in https://github.com/duckduckgo/duckduckgo-autofill/pull/458
* Update password-related json files (2024-01-26) by @daxmobile in …

Update autofill to 10.1.0

---

package-lock.json
package.json

We're not able to bump the version of `@playwright/test` due to errors when running `tsc` (see https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/2433). To fix it we need a definition of `Symbol` from `@types/node`.

Add @node/types to fix playwright type issue.

---

shared/html/devtools-panel.html

Apparently base.css is clashing with the devtools-panel stylesheet,
causing rows for blocked requests to be displayed incorrectly. The
workaround for that appears to have prevented the rows from being
hidden, when the toggle to show blocked requests is used. Without
digging more deeply into it for now, let's just ensure that blocked
requests are hidden with a more specific selector.
**Reviewer:** @GuiltyDolphin 
**CC:** @tagawa, @laghee

Fix blocked request filtering in the dev-tools panel UI

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.2.0
Updates Autofill to version [10.2.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.2.0).
* Remove unused Android UA check by @jonathanKingston in https://github.com/duckduckgo/duckduckgo-autofill/pull/494
* fix tracker radar kit reference by @brindy in https://github.com/duckduckgo/duckduckgo-autofill/pull/505
* Update password-related json files (2024-03-04) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/518
* separate 'third party provider' feature by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/252
* marking flaky tests by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/524
* remove …

Update autofill to 10.2.0

---

shared/js/background/background.js
shared/js/background/components/internal-user-detector.js
shared/js/ui/pages/options.js
shared/js/ui/views/internal-options.js

**Reviewer:**
This mirrors how we detect internal users on other platforms (for example [apple platforms](https://github.com/duckduckgo/BrowserServicesKit/blob/main/Sources/BrowserServicesKit/InternalUserDecider/InternalUserDecider.swift#L74-L76), in order to add a `isInternalUser` flag to settings. This can be used to expose additional settings in the options menu.
1. Open settings - note that the sections are as before.
2. Visit `use-login.duckduckgo.com` and login with DDG SSO.
3. Return to the settings page - there should not be a new 'Interal settings' section.

Detect internal users and add an extra section to settings for them.

---

shared/js/background/background.js
shared/js/background/components/debugger-connection.js
shared/js/background/components/resource-loader.js
shared/js/background/components/tds.js
shared/js/background/devbuild.js
shared/js/ui/views/internal-options.js
shared/scss/options.scss

Allows the config URL to be overridden for a session.
- Also opens a connection to the debugger server to trigger updates on the config is changed.
- Adds an option to the settings menu to allow set/unset of this config URL.
1. Visit use-login.duckduckgo.com and login to get recognised as an internal user.
2. Open the settings page.
3. The 'Custom config URL' setting should be displayed.
4. Type in a URL and hit 'Set'. The config at that URL should be loaded.
5. In settings, click 'Clear' to return back to the original config URL.

Custom config override

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/11.0.0
Updates Autofill to version [11.0.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/11.0.0).
* It's a major version change, but the API change is only affecting Android.
* Android: enable iframe support by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/536
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/10.3.0...11.0.0

Update autofill to 11.0.0

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/11.0.1
Updates Autofill to version [11.0.1](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/11.0.1).
* Fix regression by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/549
* Major version change 11.0.0 only affecting Android.
* Android: enable iframe support by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/536
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/11.0.0...11.0.1

Update autofill to 11.0.1

---

browsers/chrome-mv3/manifest.json
browsers/firefox/manifest.json

Our policy is to have the minimum supported Firefox version be the
previous ESR release, which is currently version 102[1].
For the Chrome MV3 migration, we'll be making use of the recent
increase of the dynamic declarativeNetRequest rule limit[2] that came
in with version 121[3].
Note: Increasing the minimum supported browser versions for Chrome MV2
builds isn't important now, since we'll be migrating Chrome
users to MV3 shortly.
1 - https://endoflife.date/firefox
2 - https://issues.chromium.org/issues/40282671
3 - https://chromium.googlesource.com/chromium/src/+/cbcff7e25340834b9ef92cdb05e20ab4f3a34564/chrome/VERSION

Increase the minimum supported browser versions

---

integration-test/onboarding.spec.js
shared/js/background/events.js
shared/js/background/onboarding.js

The onboarding code has some logic to display a welcome banner the
first time the user performs a DuckDuckGo search after installing the
extension. Until now, that code did not work for Chrome MV3 builds,
since it attempted to inject a script into the "main world" by
appending a <script> element - that does not work with MV3 due to the
stricter Content-Security-Policy used. Let's use the
scripting.executeScript API instead to inject the required code into
the "main world".
Note: This code is somewhat convoluted and could likely be simplified
in the future. But for now, with the upcoming MV3 migration
deadline, let's make the minimum changes required to get this
working!
**Reviewer:** @sballesteros, @sammacbeth 
1. Install the extension
2. Ensure DDG is the default browser if you're …

Fix the onboarding flow for the Chrome MV3 build

---

.gitignore

In the past, we wrote shared/data/smarter_encryption.txt when building
the extension and added it to the .gitignore to ensure it wasn't
accidentally included in the repository. Unfortunately however, this
means that if the file exists, it will be somewhat hidden yet be
included in builds. This is a problem given the file's >5MB
size. Let's remove the path from .gitignore, so that the file will be
noticed by developers and removed.

Avoid including old smarter_encryption.txt file in builds silently

---

integration-test/onboarding.spec.js
shared/js/background/onboarding.js

**CC:** @sballesteros 
When fixing the onboarding flow for the Chrome MV3 build[1], I made a
mistake. For MV3 builds, the page's onFirstSearchPostExtensionInstall
function was being called like:
onFirstSearchPostExtensionInstall({
isAddressBarQuery: false,
showCounterMessaging: true,
showWelcomeBanner: true
}, {
hadFocusOnStart: true
})
Instead of like:
onFirstSearchPostExtensionInstall({
hadFocusOnStart: true,
isAddressBarQuery: false,
showCounterMessaging: true,
showWelcomeBanner: true
})
(I had missed a subtle Object.assign call.)
Let's fix that here, and also add test coverage for that call to catch
similar mistakes in the future.
1 - https://github.com/duckduckgo/duckduckgo-privacy-extension/commit/2e4441d633715b455e24fa9311af19b2aeb05230

Ensure onFirstSearchPostExtensionInstallCalls is called correctly

---

shared/js/background/message-handlers.js

The popup UI (e.g. privacy dashboard) lets users disable protections
for a website. When the user clicks the toggle button, the website is
allowlisted and reloaded. With MV3, this requires a
declarativeNetRequest rule update which doesn't happen instantly. We
need to take care for that rule update to finish before reloading the
page, because otherwise some requests might still be blocked after the
reload.
1. Navigate to https://privacy-test-pages.site/privacy-protections/request-blocking/
2. Click to allowlist the website using the popup UI
3. Immediately click to run the tests after the page reloads
4. Ensure that the requests are now allowed.

Wait for user allowlisting to apply before reloading the website

---

shared/js/background/components/debugger-connection.js
shared/js/background/components/internal-user-detector.js
shared/js/background/devtools.js

**Reviewer:** @kzar @shakyShane 
Improves the config debugging to also open a websocket to a https://github.com/duckduckgo/privacy-protections-debugger server. Over this connection the following can happen:
- The browser can forward tab data to be shown in the debugger.
- The debugger can send commands, such as requesting a reload of a specific tab.
- The debugger can register to get devtools logging for a specific tab.
- The extension can forward `devtools` messages to the debugger.
1. Build the extension in dev mode.
2. Checkout and run https://github.com/duckduckgo/privacy-protections-debugger locally.
3. Go to the extension settings, and put in the local 'Custom config URL' (e.g. `http://localhost:3000/config`).
4. In the debugger, go to the 'Logs' tab. You should see the extension …

Protection debugging over websocket

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/11.0.2
Updates Autofill to version [11.0.2](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/11.0.2).
* Minor fix to websites by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/554
* More minor fixes to websites by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/555
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/11.0.1...11.0.2

Update autofill to 11.0.2

---

shared/js/background/components/debugger-connection.js

- Fix debugger websocket connection for secure contexts.
- Ensure `tabId` is treated as a number.

Fix websocket URL for non-localhost debugger instances.

---

integration-test/request-blocking.spec.js
packages/privacy-grade/src/classes/trackers.js

https://app.asana.com/0/1201141132935289/1207506709815881/f
Other platforms keep track of 3rd party requests, even when they are the same entity. See: https://app.asana.com/0/1201141132935289/1207506709815881/f
- Visit Microsoft.com
- Open the Privacy Dashboard
- You should see requests in the '3rd party' section from domains like `live.com` or other Microsoft properties
- these do not currently show.
---
- https://app.asana.com/0/0/1207550488916516

include same-entity none-trackers

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/12.0.1
Updates Autofill to version [12.0.1](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/12.0.1).
* generation: ensure password gen feature flag is respected by @sjbarag in https://github.com/duckduckgo/duckduckgo-autofill/pull/583
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/12.0.0...12.0.1

Update autofill to 12.0.1

---

integration-test/click-attribution.spec.js
integration-test/data/click-attribution-pixels.js
integration-test/data/staticcdn/trackerblocking/v6/current/extension-mv3-tds.json
integration-test/data/staticcdn/trackerblocking/v6/current/extension-tds.json
integration-test/fire-button.spec.js
integration-test/helpers/pixels.js
integration-test/helpers/playwrightHarness.js
integration-test/helpers/requests.js
shared/js/background/classes/ad-click-attribution-policy.js
shared/js/background/classes/tab-state.js
shared/js/background/classes/tab.js
shared/js/background/components/email-autofill.js
shared/js/background/components/tab-tracking.js
shared/js/background/devbuild.js
shared/js/background/events.js
shared/js/background/pixels.js
shared/js/background/settings.js
shared/js/shared-utils/pixels.js
unit-test/background/ad-click-attribution-policy.js
unit-test/background/classes/tab.js

This adds "pixel" requests to the mechanism we rely on to support ad
click attribution in DuckDuckGo products. These help DuckDuckGo
validate that the mechanism's logic is working correctly.
Further reading:
- https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/#duckduckgo-private-search-ads
- https://improving.duckduckgo.com/
**Reviewer:** @sammacbeth , @jonathanKingston 
1. Ensure the ad click attribution pixels fire correctly on Chrome using [the test page](https://www.search-company.site/) .
2. Ensure the pixels _don't_ fire on Firefox.
3. Ensure the integration tests and unit tests are passing.

Add pixels to the ad click attribution mechanism

---

integration-test/click-attribution.spec.js
integration-test/data/click-attribution-pixels.js
shared/js/background/classes/ad-click-attribution-policy.js
shared/js/background/classes/tab.js
shared/js/background/components/email-autofill.js
shared/js/background/pixels.js
unit-test/background/ad-click-attribution-policy.js

We recently added "pixel" requests to the mechanism we rely on to
support ad click attribution in DuckDuckGo products. These help
DuckDuckGo validate that the mechanism's logic is working correctly.
A few further adjustments are required:
1. The 'm_ad_click_active' pixel should only fire (and the
'm_pageloads_with_ad_attribution' counter incremented) when a request
is actually allowed by the mechanism.
2. The browser name (e.g. "chrome", "edge", etc.) should be appended
to the pixel names.
3. The extension's version number (e.g. "2024.7.10") should be
included with some of the pixels.
Further reading:
- https://github.com/duckduckgo/duckduckgo-privacy-extension/commit/f8755949344728145dcd9da970b7b1bfc8e7d926
- https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/#d …

Adjust ad click attribution pixel logic

---

integration-test/click-to-load-youtube.spec.js

The YouTube Click to Load integration tests are failing, and since
the feature's in limbo it's probably not worth spending too much
fixing them for now.

Disable YouTube Click to Load integration tests

---

package-lock.json
package.json
unit-test/background/atb.js

For some reason having a version of Puppeteer < 22 can cause
`npm install` to hang[1]. Let's update the dependency now therefore.
Note: I needed to update the dependency manually, since one of the
unit tests needed to be tweaked.
1 - https://github.com/npm/cli/issues/4028

Update puppeteer dependency to 22.14.0

---

package-lock.json
package.json
packages/ddg2dnr/lib/ampProtection.js
packages/ddg2dnr/lib/cookies.js
packages/ddg2dnr/lib/gpc.js
packages/ddg2dnr/lib/smarterEncryption.js
packages/ddg2dnr/lib/tds.js
packages/ddg2dnr/lib/temporaryAllowlist.js
packages/ddg2dnr/lib/trackerAllowlist.js
packages/ddg2dnr/lib/utils.js
packages/ddg2dnr/test/referenceTests.js
packages/ddg2dnr/test/utils.js
packages/privacy-grade/src/classes/trackers.js
shared/js/background/classes/ad-click-attribution-policy.js
shared/js/background/dnr-click-to-load.js
shared/js/background/dnr-config-rulesets.js

Some changes were required to get the type checking passing again:
- Functions that return declarativeNetRequest rules with/without rule
IDs need to be more clearly annotated, so that it's clear to
typescript when a rule's ID is available.
- Edge cases where getNextSessionRuleId() fails need to be handled
properly, adding rules with an undefined/null ID won't work.
- The DNRRule type needed to be replaced with the
chrome.declarativeNetRequest.Rule rule type, and with that some
string type rule properties needed to be cast to the correct enum
types.
See https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/#notable-behavioral-changes

Update typescript dependency to 5.5.4

---

integration-test/click-to-load-facebook.spec.js
package-lock.json
package.json

Unfortunately it seems that we no longer get the details of
chrome-extension://* requests from Playwright. Even when for example
website scripts are redirected to shim (aka "surrogate") scripts
provided by the extension. Previously those requests included
allowed/blocked/redirected status and URLs, but now they seem to
always show up as being blocked and with the URL of
chrome-extension://invalid/. The Facebook Click to Load integration
tests need to be simplified therefore, to just check for allowed
vs blocked requests.

Update @playwright/test dependency to 1.46.0

---

package-lock.json
package.json
shared/js/background/before-request.js
shared/js/background/companies.js
shared/js/background/events.js
shared/js/background/message-handlers.js
shared/js/background/popupMessaging.js
shared/js/background/utils.js
shared/js/background/wrapper.js

With this update, the way privacy-dashboard communicates with the extension has
changed. Instead of sending messages using the chrome.runtime.sendMessage API,
the chrome.runtime.connect API is used instead. In the future, that will allow
us to listen for the disconnect event as a way to know when the popup UI has
been closed by the browser (e.g. the user clicked away).
1. Check that the popup UI functions correctly, try things like allowlisting a page, or switching tabs, and make sure the popup closes itself. Ensure the website details populated in the popup UI looks right.

Update privacy-dashboard dependency to 6.0.0

---

shared/js/background/events.js
shared/js/background/message-handlers.js
shared/js/background/tab-manager.js
shared/js/background/utils.js
unit-test/inject-chrome-shim.js

The getTab, getCurrentTab, etc logic was quite confused. Let's tidy that up as
best we can for now:
- Remove the unused `getTab` and `getCurrentTab` message handlers.
- Remove the unused and outdated `utils.getCurrentURL` function.
- Remove the unused `callback` parameter from `utils.getCurrentTab` and add a
JSDoc comment for the function.
- Move the logic for getting a Tab Object for the currently focused tab into
the TabManager class.
- Note the current tab ID in session storage (in memory), so that the current
tab can (usually) be determined even when the developer tools or popup UI are
open.

Improve the getTab, getCurrentTab, etc logic.

---

shared/scss/_mixins.scss
shared/scss/views/_extension-page.scss

We started getting warnings when building our SASS stylesheets:
> Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
> More info: https://sass-lang.com/d/mixed-decls
This PR fixes those warnings by reordering `@include` statements.

Fix SASS deprecation warnings

---

.github/dependabot.yml

The current grouping is too large, making it difficult to figure out which dependency is causing failures. This PR creates 3 logical groups (types, test and build) to split up dependabot PRs into logical units.

Reorganize dependabot grouping

---

shared/js/background/background.js
shared/js/background/broken-site-report.js
shared/js/background/classes/site.js
shared/js/background/components/toggle-reports.js
shared/js/background/devbuild.js
shared/js/background/message-handlers.js
shared/js/background/utils.js
unit-test/background/classes/tab.js
unit-test/background/reference-tests/broken-site-reporting-tests.js
unit-test/background/toggle-reports.js
unit-test/data/extension-config.json
unit-test/inject-chrome-shim.js

When the user clicks to disable protections for a website, the "toggle reports"
feature prompts them to also send a website breakage report to us. This helps
increase the number of user reports we receive for website breakage issues, in
turn helping us fix or mitigate them. The feature also takes care to not prompt
the user too often, at the time of writing only prompting one to three
times (depending on the user's response) every 48 hours.
**CC:** @shakyShane 
1. Try disabling protections for a website, the "simplified breakage report" (aka "toggle reports") UI should show, prompting you to send a breakage report.
2. The UI should only show after < three accepted responses, and not after any declined responses.
3. A breakage report request should be made in the …

Add support for the "toggle reports" feature

---

shared/js/background/background.js
shared/js/background/components/dnr-listeners.js
shared/js/background/components/dnr.js
shared/js/background/dnr-config-rulesets.js
shared/js/background/dnr-gpc.js
shared/js/background/dnr-user-allowlist.js
shared/js/background/events.js

A couple of the DNR modules were registering listeners on import. This PR moves that sites into a component, so we have control over when those listeners get registered, and to what objects.

Move DNR module side-effects into a component.

---

browsers/chrome/manifest.json

A bug in the chrome.declarativeNetRequest API[1] meant that extensions could
block requests initiated by other extensions. This cross-extension request
blocking wasn't supposed to be possible[2], and led to lots of issues for users
with multiple browser extensions installed (for example, see this Privacy Badger
bug report[3]).
These cross-extension requests weren't associated with a tabId, and so could not
be differentiated from other such requests - including ServiceWorker initiated
requests. As a workaround, to avoid breaking the other extensions our users
might have installed, we stopped blocking any requests with no associated tabId.
Since then, we have fixed the bug in Chrome[4], and that fix was release with
Chrome 128. So let's increase the minimum supported Chrome version to 128, …

Bump the minimum supported Chrome version to 128

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/15.1.0
Updates Autofill to version [15.1.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/15.1.0).
* [Form] expand username re-categorization to phone by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/691
* [Matching] Add 'search' for forceUnknown by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/692
* [Release automation] Update asana usage by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/693
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/15.0.0...15.1.0
This release has been tested during autofill development. For smoke test steps see [this …

Update autofill to 15.1.0

---

integration-test/amp-protection.spec.js

Sets AMP tests to be skipped.
- These tests are regularly flakey because they depend on external sites.
- They occasionally perma-fail when a site changes its paths.
- This protection is not particularly relevant now that AMP is mostly dead.

Disable AMP tests

---

shared/js/background/broken-site-report.js
shared/js/background/components/toggle-reports.js
shared/js/background/message-handlers.js
unit-test/background/broken-site-report.js

The privacy-dashboard is going to be sending a new message
"getBreakageFormOptions", which is very similar to "getToggleReportOptions"
except for use by the standard breakage report UI flow. Let's add that now,
taking care to share the logic between those message handlers.
**Reviewer:** @jdorweiler, @mgurgel 
1. Disable protections for a website, then click to see report details.

Add getBreakageFormOptions message handler

---

.github/workflows/checks.yml
package-lock.json
package.json
pixel-definitions/common_params.json
pixel-definitions/common_suffixes.json
pixel-definitions/pixels/autofill.json
pixel-definitions/pixels/broken_site_reports.json

**Reviewer:** @nshuba 
Asana: https://app.asana.com/0/0/1208014515268142/f
- Documents some pixels and parameters sent by the extension, using the new [shared schema](https://github.com/duckduckgo/pixel-schema/tree/main).
- Added breakage pixels and one autofill pixel.
- Added a validation step to the lint CI check.

Document pixels sent by the extension

---

package-lock.json
package.json
shared/scss/_mixins.scss
shared/scss/_vars.scss
shared/scss/base/_forms.scss
shared/scss/base/base.scss
shared/scss/feedback.scss
shared/scss/options.scss
shared/scss/views/_allowlist.scss
shared/scss/views/_extension-page.scss

**Reviewer:**
We get a sass depcration warning from `lighten` and `darken` usage in the `duckduckgo-colors` library. That library is now deprecated, so this PR removes it and copies across the variable declarations that we were using from there.
See also https://app.asana.com/0/892838074342800/1209033116291734/f

Remove deprecated duckduckgo-colors dependency; fix sass warnings

---

CONTRIBUTING.md

**Reviewer:**
fixed #2830 
This pull request addresses typographical, grammatical, and clarity issues in the `CONTRIBUTING.md` file. 
1. Review the updated `CONTRIBUTING.md` file for accuracy, grammar, and improved clarity. 
The changes are only in documentation and do not affect the codebase. Verification was done to ensure all corrections are accurate.
Please review and provide feedback if further changes are needed. Thank you!

Fixed Typographical and Clarity Issues in CONTRIBUTING.md

---

shared/js/background/components/remote-config.js
shared/js/background/i18n.js
unit-test/background/remote-config.js
unit-test/inject-chrome-shim.js

- Allows the `target` condition on a sub-feature to be used to only enable it for a subset of users who match a given locale or locale-country.
- Includes more tests imported from Android.

Implement target conditions on rollouts.

---

.github/workflows/checks.yml
.github/workflows/ddg2dnr.yml

Fixes no-sandbox error as seen in https://github.com/duckduckgo/duckduckgo-privacy-extension/actions/runs/12767773293 and https://github.com/duckduckgo/duckduckgo-privacy-extension/actions/runs/12767773307

GH Actions: Rollback to ubuntu 22.04 for puppeteer-based actions.

---

pixel-definitions/common_params.json
pixel-definitions/pixels/ad_click_attribution.json

Adds schema for pixels sent for the ad-click attribution functionality.

Schema for ad-click attribution pixels

---

pixel-definitions/pixels/experiments.json
shared/js/background/background.js
shared/js/background/components/abn-experiments.js
shared/js/background/components/remote-config.js
unit-test/background/abn-framework.js
unit-test/background/remote-config.js

Implements metrics for A/B/N experiments, as per https://app.asana.com/0/1208889145294658/1208747415972722
Metrics implemented:
- `app_use` (triggered when the background service worker starts up).
- `search` (on SERP landing).
- `brokenSiteReport` (when the user has sent a broken site report).
Note, metrics are not active in Firefox.

A/B/N Experiment metrics

---

shared/js/background/background.js
shared/js/background/components/tds.js

(This PR is stacked on top of #2905).
Allow A/B tests to override the blocklist URL, so we can test blocklist changes side-by-side.

TDS (blocklist) override via A/B test

---

package-lock.json
package.json

Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.2.0
Updates Autofill to version [16.2.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.2.0).
* [Matching] Update regex to match for 'confirm password' by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/719
* Update password-related json files (2025-01-06) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/730
* [FormAnalyzer] Use conservative regex for attributes by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/735
* [FormAnalyzer] Don't flip scores on buttons with specific text by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/725
* [FormAnalyzer] add external link check for submit …

Update autofill to 16.2.0

---

shared/js/background/components/abn-experiments.js
shared/js/background/metrics.js
unit-test/background/abn-framework.js

**Reviewer:**
Our A/B/N framework assumes that:
1. Enrollment dates are sent in ET (UTC-5).
2. Conversation windows are calculated over calendar days (in ET), rather than rolling 24-hour windows from enrollment.
Our initial implementation used UTC dates (default for javascript `Date` objects), and using rolling windows, so this PR corrects that by:
1. Converting the stored enrollment timestamps to a date in ET when sending.
2. Setting the enrollment date to midnight in ET when joining an experiment. This means that conversion windows will get day-aligned without us having to change the rolling-window implementation.
This also contains a fix for a potential race with the `app_use` metric. If it is triggered too early, we may not yet have the config processed and ready to handle metrics.

Send enrollment dates in ET, and align conversion windows with ET days.

---

shared/js/background/background.js
shared/js/background/broken-site-report.js
shared/js/background/components/dashboard-messaging.js
shared/js/background/components/toggle-reports.js
shared/js/background/message-handlers.js
shared/js/background/storage/tds.js
unit-test/background/abn-framework.js
unit-test/background/dashboard-messaging.js
unit-test/background/toggle-reports.js
unit-test/data/extension-config.json
unit-test/helpers/mocks.js

**Reviewer:**
Some breakage reports were coming through with config version `undefined` on Firefox (https://app.asana.com/0/0/1209244730607066/f). This is likely caused by a race condition in the breakage report flow if the background is not fully loaded yet.
To fix this, this PR:
- Moves the sendBreakageReport function to a component.
- Removes static access to page context information, using components instead.
- Allows us to wait for the correct config lifecycle event before getting config version.
- Updates the toggle reports component to use this new entrypoint for sending reports.

Refactor broken site report message handlers

---

shared/js/background/background.js
shared/js/background/components/abn-experiments.js
shared/js/background/components/tds.js
shared/js/background/metrics.js

**Reviewer:**
Some fixes to address issues we've seen in A/A tests so far:
1. Change the app_use metric to trigger on webNavigation.
2. Fix a case when the blocklist override doesn't get removed when the user no longer has a cohort.
3. Add a handler for experiments set up in the `incrementalRolloutTest` feature.

NA Experiment fixes

---

.github/workflows/checks.yml
.github/workflows/pixel-validation.yml
package-lock.json
package.json
pixel-definitions/pixels/ad_click_attribution.json

**Reviewer:**
In Release 1.0.8 of pixel-schema there is a new option to validate pixel owners against a list of valid Github usernames (user_map.yml file in the internal-github-asana-utils repo).
I moved pixel schema validation out to the check.yml workflow and into a new pixel-validation.yml workflow. 
If you'd like to see the Pixel Schema Validation fail, you can introduce a temporary error in a pixel owner name (e.g. add a the work ERROR to the end of an valid pixel owner names (e.g. to one of the files in pixel-definitions/pixels). 
Without that, the pixel owners in this branch are all currently valid (ie. are Github usernames found in the user_map.yml) and the Pixel Schema Validation will pass.

Validate pixel owners through GitHub actions 
