- shared/js/ui/templates/shared/top-blocked-no-data.es6.js
Replace "tracker network leaderboard" with "tracker networks top offenders"
1. Remove extension and load it again
2. Open the main popup and verify the wording in the placeholder is right
3. Nothing else should have changed
> Update top offenders placeholder wording

- shared/scss/_tracker-network-icons.scss
- shared/scss/popup.scss
Fixing bug due to old revision committed to develop branch.
Re-adding the right icon classes and margins in the current grade details subview.
2. Visit any website
3. Open popup and click on "more details"
4. The subview should have icons for the tracker networks, everything should look as last production version there
5. Nothing else should be affected
> Fix icons missing on develop branch

- shared/html/options.html
- shared/js/ui/models/hamburger-menu.es6.js
- shared/js/ui/models/mixins/parse-user-agent.es6.js
- shared/js/ui/pages/options.es6.js
- shared/js/ui/templates/hamburger-menu.es6.js
- shared/js/utils.js
**Reviewer:**
@jdorweiler @russellholt 
Make the mailto's in options page and popup's hamburger menu work in Chrome (as well as Firefox).
> Port to Chrome: mailto's in feedback + broken site emails

- shared/js/ui/templates/shared/rating-hero.es6.js
**CC:** @russellholt 
Changes the phrasing on the rating from "Upgraded" to "Enhanced".
1. Check the header looks good
2. Make sure there's no instance of "Upgraded" that I've missed
> Change "upgraded" phrasing

- shared/js/background.js
**Reviewer:**
@laurengarcia 
**CC:**
@nilnilnil
> Remove isReady check preventing https upgrades

- shared/js/abp-preprocessed.es6.js
**Reviewer:**
@nilnilnil @russellholt @jdorweiler @laurengarcia 
https://app.asana.com/0/261348710882778/521171684280733
Changes from every 3 hours to every 30min
> More frequent list updates

- shared/data/constants.js
- shared/js/https.js
**Reviewer:**
@nilnilnil @laurengarcia 
The new https2 endpoint is live, switching the extension over to use it
> Use https2 endpoint

- shared/js/background.js
- shared/js/https.js
**Reviewer:**
@laurengarcia 
https://app.asana.com/0/72649045549333/522149647668475
**CC:**
@nilnilnil 
I was able to reproduce the error you mentioned in #23 after clearing everything and reinstalling. Seems like it was this missing reject handler on the promise, adding that made the error go away for me.
Can you test and see if everything works now here?
> Fix promise error

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
Don't open the popup with the Alt+G shortcut
2. Use Alt+G
3. Popup should NOT open
4. Popup will only open on direct click
> Remove Alt-G shortcut

- shared/js/https.js
**Reviewer:**
@jdorweiler @laurengarcia @nilnilnil @russellholt 
See task for more detailed explanation: https://app.asana.com/0/72649045549333/523002315037057
> Clear https-etag (forcing server load) when there's no local list

- shared/js/background.js
**Reviewer:**
@bsstoner @jdorweiler 
Clean up logic in `onInstalled` handler related to deleting indexedDB, delay it by 1 minute on startup.
> indexedDB cleanup

- shared/html/global.html
**Reviewer:**
@jdorweiler 
This will prevent the console errors currently on the safari branch, but it doesn't make the surrogates code work. That might be more complicated since we don't have a way currently to redirect child requests.
> Fix surrogates for Safari

- shared/html/options.html
**Reviewer:**
Update the "learn more" link to redirect to the new post install page.
2. Click hamburger button, then Settings
3. "Learn more" should have the updated link
> Update "learn more" link

- shared/js/ui/models/site.es6.js
- shared/js/ui/templates/shared/grade-scorecard-reasons.es6.js
- shared/js/ui/templates/shared/tracker-networks-text.es6.js
UX tweaks for the grade scorecard subview.
- For Tracker Networks
N Tracker Networks Blocked
or
0 tracker networks found
- For Major networks blocked
1 Major Tracker Network Blocked
or if more than 1
3 Major Tracker Networks Blocked 
if 0
0 Major Tracker Networks Found
- For major tracker networks:
'Site is a major tracker network'
2. Navigate to various sites and check the grade scorecard subview
3. UX should match the description above
4. Nothing else should be affected
> Grade scorecard tweaks

- shared/scss/_mixins.scss
**Reviewer:**
@jdorweiler 
**CC:**
@MariagraziaAlastra
> Fix safari knob

- scripts/tosdr.js
- shared/data/tosdr.json
> tosdr related site urls

- browsers/duckduckgo.safariextension/js/background.js
- browsers/duckduckgo.safariextension/js/content-script.js
- browsers/duckduckgo.safariextension/js/tabManager.js
**Reviewer:**
@jdorweiler 
Open new tab
start typing 'goo'
icon should no longer update to D
navigate to duckduckgo.com (without going to google first)
icon should update to A for duckduckgo
> Fix page load bug

- shared/js/background.js
- shared/js/settings.js
- shared/js/site.js
- shared/js/tab.js
**Reviewer:**
@jdorweiler @bsstoner @russellholt 
Stop force-downgrading sites with mixed http/https content.
1. pull down this branch and build for target browser
2. visit a site in our current upgrade list that contains mixed content, i visit: 1688.com
3. observe that site is auto-upgraded and the browser's native mixed content blocking is kicking in
4. observe that we are no longer force-downgrading the site to http:// in the main_frame
5. open popup and observe that we are displaying "Forced encryption" (we dont have UI to surface mixed content message(s) tho)
> Mixed content handling

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
Chrome and FF: update name and description in manifest.
> update name and description for Chrome, FF

- browsers/duckduckgo.safariextension/Info.plist
Update Safari name and description
~~Not sure if these are the right ones - please validate.
Line 83 might need to be "DuckDuckGo Privacy Essentials" instead of the short description.~~
Verified correct.
> safari description update

- shared/data/defaultSettings.js
- shared/js/background.js
Show the new post-install page (same as in #47) on install.
The page is now live, which makes this easier to test :smile: 
2. Page should be loaded in a new tab
3. Try reloading again from the interface - nothing should happen this time
4. Uninstall and install again - page should show
5. Close and reopen the browser - nothing should happen
> Show post-install page on install or update event

- shared/js/companies.js
**Reviewer:**
Previous code wasnt defensive enough, erroring on install.
> fix Companies.sanitizeData on install 

- shared/data/tracker_lists/trackersWithParentCompany.json
- shared/js/background.js
**Reviewer:**
Open the new post-install page on a new tab instead of updating the current tab with the new url.
1. Remove current extension
2. Build and load
3. Post-install page should be opened in a new tab
> Open post-install page on new tab instead of updating the current one

- shared/js/atb.js
**Reviewer:** @MariagraziaAlastra
> add browser type to survey

- scripts/tosdr-topics.json
- scripts/tosdr.js
**CC:** @dharb @russellholt 
This bunches several TOSDR fixes in the same PR (sorry). I'll add more of a description inline.
1. Run `grunt execute:tosdr --browser=chrome --type=dev`
2. Try the sites I've mentioned in the inline comments
> TOSDR data fixes

- shared/js/companies.js
- shared/js/ui/models/top-blocked.es6.js
Make sure the highest percentage is always 100% (fixes potential issues with caching)
2. Top blocked should look like before, if you had stats for it
3. Remove and reinstall extension or thrash the stats and start again
4. After 30 pages you should see the top blocked again. Nothing should be over 100%
> Max 100% for top blocked

- shared/js/trackers.js
**Reviewer:**
Look up related entities in checkSurrogate. This prevents us from blocking most of the stuff on analytics.google.com. There will still be two gstatic trackers blocked by easyprivacy. I'll have to whitelist those separately.
> lookup related entities in checkSurrogate

- shared/js/background.js
**CC:** @russellholt 
Setting DDG as the default search provider in the browser already adds this functionality (in chrome + firefox).
1. `npm run dev-chrome`
2. load local extension in chrome or firefox. highlight some text and right click on it. there should only be one duckduckgo entry in the context menu.
> Remove duplicate context menu item

- browsers/duckduckgo.safariextension/js/background.js
**Reviewer:**
Autocomplete requests can come through here and if you have a ddg search in your history this will cause you to automatically navigate to that page. We're still correctly sending atb in onBeforeSearch.
> remove atb from beforeNavigate

- shared/js/atb.js
**Reviewer:**
Migrate set_atb from localStorage over to settings.
1. migrating user should copy over localStorage
```
localStorage['atb'] = 'v1-1'
localStorage['set_atb'] = 'v2-1'
settings.updateSetting('atb', '')
settings.updateSetting('set_atb', '')
```
- result
```
settings.getSetting('atb')
"v1-1"
settings.getSetting('set_atb')
"v2-1"
```
2.  existing user should keep settings atb values
```
localStorage['atb'] = 'v1-1'
localStorage['set_atb'] = 'v2-1'
settings.updateSetting('atb', 'v3-1')
settings.updateSetting('set_atb', 'v4-1')
```
- result
```
settings.getSetting('atb')
"v3-1"
settings.getSetting('set_atb')
"v4-1"
```
> migrate set_atb

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/data/tosdr.js
- shared/data/tracker_lists/trackersWithParentCompany.json
> Chrome and Firefox Release 2018.1.25

- shared/js/background.js
Increases the redirect loop detection threshold to 3 seconds.
1. Open http://xe.com
2. Redirect loop shouldn't happen
> Increase redirect loop detection timeout

- test/easylistTestCases.js
- test/html/unitTests.html
- test/testEasylist.js
**Reviewer:**
Added a test to go with this fix to the abp parser, https://github.com/duckduckgo/abp-filter-parser/pull/2
> add host test

- scripts/tosdr-topics.json
- shared/data/tosdr.js
**CC:** @russellholt 
1. Open e.g. https://wordpress.com/
2. Privacy practices should show as "unknown"
> Don't match TOSDR on "device fingerprinting"

- shared/js/ui/templates/shared/tracker-networks-text.es6.js
- shared/scss/views/_tracker-networks.scss
**Reviewer:**
@andrey-p 
I had orphaned a couple of commits from #114 that Andrey had suggested during code review by not pushing them to origin. These were meant to have gone out with and were already approved here:
https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/114
> Lost commits from PR #114: UI changes to trackers subview hero counts

- README.md
- SAFARI.md
- SAFARI_README.md
**Reviewer:**
Adding a readme for Safari and steps for how to build it.
> Safari readme and build steps

- shared/js/trackers.js
- test/tests/trackers.js
Make sure domain names with `_` in them don't lead to a JS error.
1. Open https://www.zive.cz/ while monitoring the logs from the background page
2. You shouldn't get any JS errors (without the fix you get an error for `https://tracker_cnc.contentexchange.me/widget/EszYqNuK3wrRyDXwX-cibtgexhoe`)
3. Go to the `test/index.html` page and run unit tests
4. The new test I added shouldn't fail (it fails without the fix)
Note, there's some other tests failing there. I'm not sure what that's about.
> Fix domain error

- shared/js/atb.js
- shared/js/background.js
- shared/js/site.js
- shared/js/utils.js
**Reviewer:** self
**CC:** @dharb 
**Note** this doesn't merge into develop
Move another one of the globals to a utils method. I think this is straightforward so I'm self-merging.
> Move 'browser' global to utils

- shared/js/ui/models/hamburger-menu.es6.js
- shared/js/ui/models/mixins/parse-user-agent.es6.js
- shared/js/ui/models/site.es6.js
- shared/js/ui/pages/options.es6.js
- shared/js/ui/templates/hamburger-menu.es6.js
- shared/js/ui/templates/shared/email-feedback-footer.es6.js
- shared/js/ui/templates/shared/render-broken-site-href.es6.js
- shared/js/ui/templates/shared/render-feedback-href.es6.js
- shared/js/ui/templates/site.es6.js
**CC:** @russellholt @alohaas @b1ake 
This adds the following to all places where the user can pass feedback:
- extension version
- browser name
- browser version
The above bits of information should be added to feedback sent via:
1. the hamburger menu
2. the "report broken site" on the main popup
3. the options page
> Add more info to feedback

- .gitignore
- Gruntfile.js
- Makefile
- test/html/debugSite.html
- test/html/screenshots.html
- test/html/settings.html
- test/html/unitTests.html
- test/requireHelper.js
- test/testUtils.js
- test/tests/atb.js
- test/tests/https.js
- test/tests/sites.js
- test/tests/surrogates.js
- test/tests/trackers.js
**Reviewer:** self
**CC:** @dharb  @jdorweiler 
**NOTE** this doesn't merge into develop.
This unbreaks the current tests so that they work with Browserify. Or rather, unbreaks them to their existing point of brokenness.
The stuff I did isn't all that future proof, but I'm going to harden these tests anyway, so I just wanted to get them to pass for the time being.
That, and the fact that this is an instrumentation PR, is the reason why I'm gonna self-merge this PR.
> Get unit tests to work with Browserify

- shared/js/ui/models/whitelist.es6.js
- shared/js/ui/templates/whitelist-items.es6.js
- shared/js/ui/templates/whitelist.es6.js
- shared/js/ui/views/whitelist.es6.js
**CC:** @alohaas 
Followup from #137, where we found out the whitelist model doesn't update its list when removing an item.
This prevents the "no whitelisted sites" message from showing when:
- Whitelist already contains more than 1 domain
- User removes all whitelisted domains at the same time
The solution in this PR does the following:
- Update the list in the model when removing an item
- Take out rendering the list items into another template
- Selectively render the above mentioned list items template when an item is removed
See also screencasts:
- [No whitelisted sites, adding some](https://gfycat.com/SkinnyPerfumedIvorybackedwoodswallow)
- [Remove whitelisted sites with input hidden and visible](https://gfycat.com/CorruptBountifulBellfrog)
1. Build and …
> Update model when removing items from whitelist

- shared/js/trackers.js
**Reviewer:**
@dharb @russellholt 
Don't block related entities.
> don't block related entity

- Makefile
- package.json
- scripts/importers/companyList.js
- shared/js/trackers.js
- shared/js/ui/models/hamburger-menu.es6.js
- shared/js/ui/models/mixins/parse-user-agent.es6.js
- shared/js/ui/models/site.es6.js
- shared/js/ui/models/whitelist.es6.js
- shared/js/ui/pages/options.es6.js
- shared/js/ui/templates/hamburger-menu.es6.js
- shared/js/ui/templates/shared/email-feedback-footer.es6.js
- shared/js/ui/templates/shared/render-broken-site-href.es6.js
- shared/js/ui/templates/shared/render-feedback-href.es6.js
- shared/js/ui/templates/site.es6.js
- shared/js/ui/templates/whitelist-items.es6.js
- shared/js/ui/templates/whitelist.es6.js
- shared/js/ui/views/whitelist.es6.js
> Release version 2018.3.2

- shared/js/atb.js
- shared/js/utils.js
**CC:** @alohaas 
**Dependencies:** internal PR
Adds some more info to the uninstall survey.
1. Uninstall the extension
2. You should see the browser version and the extension version in the initial request to `atb.js`.
> Add browser and extension version to uninstall survey

- shared/js/background/atb.es6.js
> use absolute path

- Gruntfile.js
**Reviewer:** self
**CC:** @jdorweiler @MariagraziaAlastra @dharb 
Adding stack traces for the compiled files, both UI and background.
> Enable source maps for dev build

- .travis.yml
- karma.conf.js
- unit-test/data/grade-cases.json
> Test travis

- shared/data/constants.js
> remove easylist from constants

- .gitignore
- .travis.yml
- shared/js/background/abp-lists.es6.js
- shared/js/background/atb.es6.js
- shared/js/background/background.es6.js
- shared/js/background/classes/score.es6.js
- shared/js/background/classes/site.es6.js
- shared/js/background/classes/tab.es6.js
- shared/js/background/https.es6.js
- shared/js/background/redirect.es6.js
- shared/js/background/safari-events.es6.js
- shared/js/background/safari-wrapper.es6.js
- shared/js/background/settings.es6.js
- shared/js/background/tab-manager.es6.js
- shared/js/background/tracker-lists.es6.js
- shared/js/background/trackers.es6.js
- shared/js/background/utils.es6.js
- shared/js/content-scripts/content-script.js
- shared/js/content-scripts/on-install.js
- shared/js/content-scripts/social-widgets.js
- shared/js/ui/base/safari-ui-wrapper.es6.js
- shared/js/ui/templates/autocomplete.es6.js
- shared/js/ui/templates/hamburger-menu.es6.js
- shared/js/ui/templates/privacy-options.es6.js
- shared/js/ui/templates/privacy-practices.es6.js
- shared/js/ui/templates/shared/crossplatform-link.es6.js
- shared/js/ui/templates/site.es6.js
- shared/js/ui/templates/tracker-networks.es6.js
- shared/js/ui/views/site.es6.js
**CC:** @dharb @jdorweiler @russellholt 
Fixes a lot of small tweaks that Lint was complaining about. Some of them are nitpicky, but I figured we might as well do them. A couple are possible bugs.
This is based on some of the slightly more hairy changes in the diff. Sorry about vagueness.
A lot of this is covered in the beta tests anyway, so we should be fine.
1. Lint should pass without errors
2. The `atb` query string data should be set correctly on searches when installing the extension (note: we'd only be able to test that properly when the Beta is out)
3. Grade should be set correctly in the popup
4. Fetching the HTTPS list should work correctly in FF/Chrome
5. Trackers should be successfully blocked in Safari, and surrogates should still run
6. Tab …
> Lint manual fixes

- shared/js/background/chrome-events.es6.js
- shared/js/ui/base/chrome-ui-wrapper.es6.js
**Reviewer:**
Only respond to messages from our own extension.
> check sender id

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/js/background/chrome-events.es6.js
- shared/js/background/classes/tab.es6.js
- shared/js/background/redirect.es6.js
- shared/js/background/trackers.es6.js
- shared/js/content-scripts/element-hiding.js
**CC:** @jdorweiler @russellholt @kdzwinel @andrey-p 
Hide iframes and their wrappers when they contain blocked requests. This adds functionality to deal with three common forms of ads:
1. Top level third-party iframe:
`<div class="ad-class">`	        <--- ad wrapper
`<iframe src="...">`		<--- blocked request
`</iframe>`
`</div>`
2. Nested third-party iframe
`<div class="ad-class">`	        <--- ad wrapper
`<iframe src="...">`            <--- first party or otherwise unblocked request
`<iframe src="...">`    <--- blocked request
`</iframe>`
`</iframe>`
`</div>`
3. Nested third-party scripts that would have loaded iframes
`<div class="ad-class">`	        <--- ad wrapper
`<iframe src="...">`            <--- first party or otherwise unblocked request
`<script …
> Add Element Hiding Support

- Gruntfile.js
- browsers/duckduckgo.safariextension/Settings.plist
- shared/data/defaultSettings.js
- shared/js/background/abp-lists.es6.js
- shared/js/background/atb.es6.js
- shared/js/background/chrome-events.es6.js
- shared/js/background/chrome-wrapper.es6.js
- shared/js/background/debug.es6.js
- shared/js/background/https.es6.js
- shared/js/background/load.es6.js
- shared/js/background/safari-events.es6.js
- shared/js/background/safari-wrapper.es6.js
- shared/js/background/tracker-lists.es6.js
- shared/js/background/trackers.es6.js
- shared/js/content-scripts/on-install.js
- test/tests/atb.js
- unit-test/background/atb.es6.js
- unit-test/helpers/settings.es6.js
**CC:** @jkv 
- Tightens up ATB pipeline steps
- Adds `dev=1` to all requests made from dev builds of the extension
- Adds the ability to handle errors from the load module
- ... and adds unit test coverage as for the ATB module as much as possible.
See inline comments for more info.
Test the following two scenarios on Chrome, FF and Safari. Note, Safari may need to be put on DDH6 for us to test the entire flow.
**Case 1: no post-install success page (e.g. if the user installed via the Chrome web store)**
1. Install the extension with no DDG tabs open
2. The following requests should be made:
- `atb.js`
- `/exti?atb=v124-2`
3. Run a search. The following request should be made:
- `atb.js?atb=v124-2&set_atb=v124-2`
**Case 2: post-install success page**
1. Open a …
> Tighten ATB, add unit tests

- shared/js/content-scripts/element-hiding.js
No functionality change here, just refactoring to make the element hiding content script an ES6 class.
1. Make sure element hiding works exactly as it did before. Note that not all of the ads on the site we've been testing this on (yahoo.com) will be collapsed since they don't all contain blocked tracking requests.
> Refactor element hiding content script to be an es6 class

- shared/js/ui/templates/hamburger-menu.es6.js
- shared/js/ui/templates/privacy-practices.es6.js
- shared/js/ui/templates/search.es6.js
- shared/js/ui/templates/shared/crossplatform-link.es6.js
- shared/js/ui/templates/shared/hamburger-button.es6.js
- shared/js/ui/templates/shared/hero.es6.js
- shared/js/ui/templates/shared/rating-hero.es6.js
- shared/js/ui/templates/shared/toggle-button.es6.js
- shared/js/ui/templates/top-blocked-truncated-list-items.es6.js
- shared/js/ui/templates/top-blocked.es6.js
- shared/js/ui/templates/tracker-networks.es6.js
- shared/scss/views/_search-form.scss
**Reviewer:** @jagtalon (and probably @MariagraziaAlastra)
Adding better descriptions of stuff for better accessibility.
1. Load up the extension with a screenreader.
2. Get testin'
> Label various things

- shared/js/background/chrome-events.es6.js
- shared/js/background/pixel.es6.js
- shared/js/ui/models/site.es6.js
- shared/js/ui/views/search.es6.js
- shared/js/ui/views/site.es6.js
- shared/js/ui/views/top-blocked-truncated.es6.js
- unit-test/background/pixel.es6.js
Setting up anonymous engagement metrics for the extension.
Learn more here: https://duck.co/help/privacy/atb
2. Navigate through sites, open the popup, look at the subviews etc
3. Inspect the Network requests in the background, make sure the right metrics are sent as per specs
4. There are also new unit tests
> Add anonymous engagement metrics

- scripts/tosdr.js
**Reviewer:** self
**CC:** @MariagraziaAlastra @russellholt 
Makes sure the script to generate TOSDR data doesn't choke on weirdly formatted URLs.
> Handle badly formatted/nonexistent TOSDR sites gracefully

- shared/js/content-scripts/element-hiding.js
I introduced a bug in my last commit in https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/281 by calling forEach on an HTMLCollection. I'm guessing I forgot to enable/disable the extension after reloading it to clear cached content scripts after making the changes in that commit and missed the errors. This PR just fixes that issue by using Array.prototype.forEach.call in order to access the forEach method.
See https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/281
> Element Hiding - Fix forEach loop HTMLCollection regression

- shared/data/tosdr.json
- shared/js/background/classes/tab.es6.js
> update tosdr data and tab url

- shared/js/content-scripts/element-hiding.js
Should fix #294, but I'm not sure if there's any negative side effects.
**Reviewer:**
> return early if e.data is undefined

- Gruntfile.js
- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/js/background/classes/https-redirects.es6.js
- shared/js/background/classes/tab.es6.js
- unit-test/background/classes/https-redirects.es6.js
PRs in the release:
- #295 return early if e.data is undefined
- #296 Expand failed HTTPS protection to the entire hostname
- #298 Anonymous alert when HTTPS upgrades fail
> Release 2018.9.14

- shared/data/constants.js
- shared/js/background/chrome-events.es6.js
- shared/js/background/classes/https-redirects.es6.js
- shared/js/background/classes/tab.es6.js
- shared/js/background/https.es6.js
**Reviewer:**
Listen for https upgrade errors to remove bad upgrades.
Easiest way to find broken https upgrades is to:
1. Build a dev version of the extension.  
2. Open the extension console and set the https whitelist to an empty list
`window.dbg.https.whitelist = []`
3. Navigate to some sites that were on the whitelist. They should be completely broken now.
> Listen for https errors

- shared/data/tosdr.json
Add entry for privacyheroes.io to tosdr data.
1. `npm run dev-chrome`
2. Navigate to privacyheroes.io
3. Open pop up, privacy practices should now appear there.
> Add privacyheroes.io to tosdr data

- shared/scss/views/_hero-rating-container.scss
Minor graphical tweak.
The grade hero icon shouldn't have one pixel cut off.
> Avoid cutting off grade icon by 1px

- shared/js/background/chrome-events.es6.js
- shared/js/background/chrome-wrapper.es6.js
- shared/js/background/classes/site.es6.js
- shared/js/background/classes/tab.es6.js
- shared/js/background/utils.es6.js
- shared/js/ui/models/site.es6.js
- unit-test/background/classes/site.es6.js
**CC:** @dharb 
Just tightening up how we determine what's a special page and what isn't.
(Note, there's an outstanding bug where the popup might not update if you go from a non-special page to a special page. This PR doesn't fix that one.)
Open a bunch of special pages on Chrome, Firefox and Vivaldi.
None of them should be showing a grade, and the description should be sane.
> Handle special domains better

- shared/js/background/chrome-events.es6.js
Disabling adding/modifying CSP headers for now - will need much deeper testing before it is re-enabled.
Fixes #322, #323
> disable csp headers

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
disable CSP headers.
#322 , #323
> Rc 2018.10.04

- browsers/firefox/manifest.json
> fix firefox version number

- shared/js/ui/templates/feedback-form.es6.js
**Reviewer:**
@jagtalon 
Add disabled attribute for submit button when the user have no input yet
> Add attribute disabled for button for accessibility. Ref #268

- shared/js/background/chrome-events.es6.js
**Reviewer:**
Remove path from ehd request.
1. Build a dev version of the extension
2. clear the https whitelist, `window.dbg.https.whitelist = []`
3. Visit some sites that were on the whitelist and make sure the ehd request doesn't include the path
> remove path from ehd

- shared/js/background/chrome-events.es6.js
**CC:** @nilnilnil @dharb 
Update how often the extension pulls in new HTTPS and tracker lists.
You know, I'm not sure. Open the extension and wait for 12 hrs, and it should hit the CDN again.
> Update lists every 12hrs

- shared/js/background/chrome-events.es6.js
- shared/js/background/classes/site.es6.js
- shared/js/background/classes/tab.es6.js
- shared/js/background/companies.es6.js
- shared/js/background/tab-manager.es6.js
- unit-test/background/classes/site.es6.js
- unit-test/background/classes/tab.es6.js
Adds the webNavigation.onCommitted event as another signal that we should update the site URL.
This fixes two problems:
- not updating the popup around special sites (e.g. chrome://extensions)
- not updating the popup when we get 200 from a service worker, rather than the server (see below)
To test the first problem:
1. Open a new tab and open e.g. `chrome://extensions` or `about:addons` - the popup should say "extensions"
2. Open e.g. duckduckgo.com in the same tab - the popup should say duckduckgo.com
3. Open the extension page again in the same tab - the popup should say "extensions" again
4. Pressing back and opening the popup should always show the correct site name
And the second (requires a Gmail account):
1. Log into your Gmail account
2. Go to googlemail.com …
> Make sure Site class is kept up-to-date

- shared/js/background/classes/site.es6.js
- unit-test/background/classes/site.es6.js
I made a change to make sure we weren't over-matching on domains in the temp whitelist, but it ended up under-matching (specifically on subdomains). This change should fix that issue.
> Make sure temp whitelist properly matches on subdomains

- browsers/chrome/manifest.json
We want to test extension update procedure in Chrome. This version only updates the version number.
1. Build the extension
2. Load it in Chrome and see if version is 2019.3.6
> Release version 2019.3.6

- browsers/firefox/manifest.json
Rebuild the previous Firefox release using node v10.0.0 and npm 6.4.0
This PR only contains the updated manifest version for Firefox
> Firefox Release 2019-4-4

- package.json
**CC:** @kdzwinel @dharb @andrey-p 
Updating the node version requirements to minimum 10.0.0
There have been some internal changes in node and, for consistency and build reproducibility purposes, it helps to limit the allowed versions to the newest ones.
2. there should be no changes, everything works as usual
> Update minimum required node version to 10.0.0

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
> release 2019-5-29

- browsers/chrome/manifest.json
**Reviewer:**
#377 was reverted do to a failing test in the Chrome store. Should pass now that Chrome 75 is out.
> add prepopulated_id to the search provider

- package-lock.json
- package.json
Addresses https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/393.
> jQuery 3.2.1 -> 3.4.1

- shared/data/tosdr.json
**CC:** @dharb @kdzwinel 
Duck.com wasn't included in our tosdr data. This PR fixes that.
2. go to duck.com (try throttling so the redirect happens more slowly)
3. verify it has a privacy policy now
4. everything else should work as usual
> Add duck.com to tosdr data

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- use match for isSameDomainRequest in chrome #409
- Fix broken site check #407
- fix isSameDomainRequest for chrome #406
> release 2019-9-4

- shared/data/constants.js
> update tds url

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
**CC:** @jdorweiler @kdzwinel @dharb 
Releasing the following:
- #420 
- #417
> release 2019-12-12

- shared/js/background/chrome-events.es6.js
- shared/js/background/experiments.es6.js
- unit-test/background/https-service.es6.js
- Ensure experiment set **after** ATB is setup
- Ensure experiment activation also fires on `update` event so installed users are opted in also
- Open browser tab to https://duckduckgo.com/?natb=v215-2rz&cp=atbhc 
- This ensures the correct ATB is passed to extension on startup
- Install extension
- Open background page
- Should see console warn about experiment setup running
- Go to https://google.com
- Should see banner 
- Reload extension
- Should see console warn about experiment activation being skipped
- Dismiss banner
- Reload extension
- Should see console warn about experiment activation being skipped
- Quit chrome, and re-open
- Should see console warn about experiment activation being skipped
- Go to https://google.com
- Should **NOT** see banner
> Privacy Nudge Update

- browsers/chrome/manifest.json
- #435 Set up Privacy Nudge Banner Experiment
> Release 2020-4-5

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
**Reviewer:**
We're not using this API.
> remove unused cookies permission

- browsers/chrome/manifest.json
- package-lock.json
- #442 Remove unused cookies permission
> release 2020-4-6 on chrome

- browsers/firefox/manifest.json
**Reviewer:**
Add t=newext param to Firefox
> Add newext param

- shared/data/experiments-out.js
- shared/js/background/banner.es6.js
- shared/js/background/chrome-events.es6.js
- shared/js/background/experiments.es6.js
- shared/js/background/storage/tds.es6.js
**Reviewer:**
Test blocking with a much larger list built from the Tracker Radar.
1. In a separate tab go to https://duckduckgo.com/?natb=v215-6lm&cp=atbhc
2. Install the extension
3. Restart the browser or reload the extension to get into the experiment group
4. If you check the network tab of the extension console you should see that the tracker list came from /lm/tds.json
> Larger block list experiment

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- package-lock.json
- #444 Large block list experiment
> Release 2020-4-30

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- package-lock.json
> Release 2020-5-14

- Gruntfile.js
- shared/js/background/atb.es6.js
- shared/js/content-scripts/onboarding.js
**CC:** @MariagraziaAlastra @moollaza 
This implement an alternative post install workflow where the extension does not open the post install page but instead notify a new onboarding modal on the DuckDuckGo that it was successfully installed.
1. Open chrome and **uninstall** the extension if you have it installed already
2. Visit [https://ddh9.duckduckgo.com?t=hx](https://ddh9.duckduckgo.com?t=hx)
3. Clear all the cookies / local storage data associated with `ddh9.duckduckgo.com`
4. Reload [https://ddh9.duckduckgo.com?t=hx](https://ddh9.duckduckgo.com?t=hx)
5. You should see a "Get Started" button
6. Click on the "Get Started" button, you should see a modal and an animated button automatically opening a new window for the chrome store
7. **DO NOT INSTALL THE …
> Multi-step Onboarding: onboarding messaging

- shared/data/constants.js
- shared/data/experiments-out.js
**Reviewer:**
Updates the block list endpoint to v2.1
1. install extension
2. in extension console run `chrome.runtime.reload()`
3. check in the network tab that v2.1 url was used
4. check that tracker blocking is working correctly
> Update block list to v2.1

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- package-lock.json
**CC:** @sballesteros @moollaza @jdorweiler 
Releasing the following:
- #453 Update block list to v2.1
- #452 Multi-step onboarding: onboarding messaging
> Release 2020-5-28

- README.md
Update the README to include information about the Safari extension.
> Update README to point to Safari

- shared/data/constants.js
- shared/data/surrogates.txt
- shared/js/background/storage/tds.es6.js
**Reviewer:** @jdorweiler @kdzwinel 
Two major changes are included in this PR:
1. Surrogates are now loaded from a local .txt file (shared/data/surrogates.txt)
2. Surrogates have been rewritten from the ground up. I plan to document and add them to https://github.com/duckduckgo/tracker-radar soon. We will also be generating a lot more of these in the future.
1. build and install extension
2. visit a site that fetches a script that we have a surrogate for (eg vrbo.com, which loads google-analytics.com/analytics.js). Check that the surrogate is loaded by opening dev tools and looking in either the debugger tab (firefox) or sources tab (chrome) at the analytics.js resource.
> Serve our own local surrogates

- Gruntfile.js
- integration-test/background/test-fingerprint.js
- package-lock.json
- package.json
- shared/data/experiments-out.js
- shared/data/fingerprint-protection.js
- shared/js/background/chrome-events.es6.js
**Reviewer:** Konrad
Adding basic fingerprinting protection to the extension. This will prevent websites from gleaning screen, battery, and some system information provided by the window, navigator, battery, and screen API's.
1. Run automated tests with npm run test-int
2. Run manual tests by installing the plugin and going to any page. Open dev tools, and check values of window.availTop or availLeft (should be 0).
> Fingerprint protection

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
**CC:** @Charlie-belmer @dharb 
- #486 User Agent
- #495 Global Privacy Control
> Release 2020-10-13

- shared/data/fingerprint-protection.js
Fix occasional console error where cross domain iFrame gives console errors on anti-fingerprinting script
> Fix iFrame cross origin console errors

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
**CC:** @Charlie-belmer 
Releasing:
- #497 Fix issue with processing User Agent safe list
-  #498 Fix extension causing Firefox to ignore size in window.open()
- #501 Fix iFrame cross origin console errors
> Release 2020-10-21

- shared/html/options.html
- shared/js/ui/templates/breakage-form.es6.js
- shared/js/ui/templates/feedback-form.es6.js
- shared/js/ui/templates/hamburger-menu.es6.js
- shared/js/ui/templates/privacy-options.es6.js
- shared/js/ui/templates/privacy-practices.es6.js
- shared/js/ui/templates/shared/grade-scorecard-reasons.es6.js
- shared/js/ui/templates/shared/top-blocked-no-data.es6.js
- shared/js/ui/templates/site.es6.js
- shared/js/ui/templates/top-blocked.es6.js
- shared/js/ui/templates/tracker-networks.es6.js
- shared/js/ui/templates/whitelist-items.es6.js
- shared/js/ui/templates/whitelist.es6.js
> Copy changes

- shared/js/background/chrome-events.es6.js
- shared/js/background/tracker-utils.js
I found a couple of minor logic improvements while testing.
> Minor updates to Referrer trimming

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- #523 Don't overinject scripts into frames
- #515 Minor updates to Referrer trimming
- #511 Referrer Truncation
- #505 Copy Changes
> Release 2020-12-3

- shared/js/background/atb.es6.js
- shared/js/background/utils.es6.js
- shared/js/shared-utils/parse-user-agent-string.es6.js
- shared/js/ui/base/chrome-ui-wrapper.es6.js
- shared/js/ui/pages/mixins/chrome-set-browser-class.es6.js
This improves browser detection to include Brave and Edge (previously a bug prevented Edge detection) for some behavior. It also adds a parameter to atb requests with this browser value (Firefox, Chrome, Brave, Edge).
Asana: https://app.asana.com/0/inbox/1172258661922799/1199403702264245/1199505030150494
> Improve browser detection for edge and brave

- shared/data/defaultSettings.js
- shared/js/background/GPC.es6.js
- shared/js/content-scripts/GPC-moz.js
- shared/js/content-scripts/GPC.js
- shared/js/ui/models/privacy-options.es6.js
- shared/js/ui/templates/privacy-options.es6.js
**CC:** @pdol @kdzwinel 
Two changes here:
- Set GPC to default on
- Don't overwrite GPC signal if already set by UA or other extension. See https://github.com/EFForg/privacybadger/pull/2722 and https://github.com/globalprivacycontrol/gpc-spec/issues/11#issuecomment-736772505 for background.
1. Install extension in Firefox and Chrome
2. Verify that GPC setting is on, `navigator.globalPrivacyControl` is set to `true` on websites, and the `Sec-GPC: 1` header is attached to requests.
3. Turn GPC setting off. Verify that `navigator.globalPrivacyControl` is set to `false` on websites, and the `Sec-GPC: 1` header is *not* attached to requests.
4. Install other extension that sets GPC, such as Privacy Badger. Probably should test the next few steps twice: once with DDG …
> GPC tweaks. Properly deal with extension conflicts.

- shared/data/fingerprint-protection.js
- shared/js/background/chrome-events.es6.js
Improve anti-fingerprinting scripts to prevent some bypasses.
> Protect against some anti-fingerprint bypasses.

- Gruntfile.js
- package-lock.json
- package.json
**Reviewer:** TBD
Migrate from deprecated node-sass to dart sass, which should also compile on Apple M1 hardware
- npm i
- npm run dev-chrome
- install extensional locally in FF/Chrome
- confirm ui hasn't broken
> Testing switch top Dart Sass

- shared/data/constants.js
- shared/js/background/chrome-events.es6.js
- shared/js/background/redirect.es6.js
- shared/js/background/utils.es6.js
**Reviewer:** @Charlie-belmer 
**Depends on:**  https://app.asana.com/0/11472677167855/1185888722207947
We're renaming whitelist to unprotected along with the repo name too. There are other mentions we'd like to fix in this repo but they will be tackled separately.
1. This depends on the rename landing first
2. Load extension and ensure the content scripts are loaded into the page (warnings are shown if they're not)
> Rename the content blocking list code to unprotected.

- shared/js/background/utils.es6.js
- shared/js/content-scope/fingerprint.js
**Reviewer:** @Charlie-belmer 
- First pixel data returning '0' created div by 0 issues which was pretty common
- The image data wasn't being used correctly, but stringifying the key full length was really expensive with the crypto algo
- We could consider some method similar to nextRandom to return a short determinisitic string
- Verifying I'm hitting all the channels (I think I am anyway)
- TODO the same response appears to be returned toDataURL across origins.
> Fix canvas issues

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- package-lock.json
Releasing:
- #551 Fix Canvas issues
- #541 Canvas fingerprint protection
- #535 Switch to Dart SaSS
- #542 Rename the content blocking list to unprotected
- #546 Update to the latest standard ESLint config
- #447 Bump jQuery from 3.4.1 to 3.5.0
- #520 Unit test repair
- #527 Protect against some anti-fingerprint bypasses
> Release 2021-3-2

- package.json
**Reviewer:** @Charlie-belmer 
Fixes sites with `define` methods from coliding in scope with the sjcl we ship. See also: https://app.asana.com/0/inbox/1199237043596759/1200018203784721/1199999815816696
> Remove exporting from sjcl to prevent collisions.

- shared/js/content-scope/fingerprint.js
Fixes: #560
**Reviewer:** @Charlie-belmer
> Fix up konvajs single pixel getImageData issue.

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
Releasing the following:
- #558 Update icons
- #561 Fix up konvajs single pixel getImageData issue
- #562 Remove exporting from sjcl to prevent collisions
> Release 2021-3-8

- shared/js/background/chrome-events.es6.js
- shared/js/background/utils.es6.js
- shared/js/content-scope/fingerprint.js
- shared/js/injected-content-scripts/fingerprint-protection.js
> Add support for multiple script exemption lists

- shared/js/background/utils.es6.js
- unit-test/background/tracker-utils-tests.js
> Fix referrer truncation edge cases

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
New protections against tracking cookies, and improvements to fingerprinting protections:
* First and third party cookie blocking #570
* Messaging to counter Google's modal #568
* Performance improvements to canvas fingerprinting protection #575 
* Audio fingerprinting protections #553 
* Move surrogates to web accessible resource #550
> Release 2021-03-26

- package-lock.json
- package.json
- shared/js/ui/templates/privacy-practices.es6.js
We used "change-case" in one place to upper case first letter of a sentence. Turns out that this package is huge and includes a lot of suspiciously looking code (regexes). Let's drop it.
1. Go to youtube.com
2. Open the popup
3. Click on "Poor Privacy Practices"
4. Make sure that listed practices start with a capital letter
Stable extension vs this build
> Remove "change-case" to reduce the npm hell 👹

- shared/js/background/chrome-events.es6.js
Fixes dropping GPC request headers
> Don't drop request headers

- shared/js/content-scope/fingerprint.js
> Cache audio key when heavily reused

- package.json
- shared/js/content-scope/fingerprint.js
See: https://app.asana.com/0/inbox/1199237043596759/1200170965113765/1200172235197573
> Add missing codec to sjcl

- Makefile
**Reviewer:**
Always run `npm ci` before a release or beta build. This should make builds reproducible for given node version.
> Ensure dependencies match package-lock when building beta/release

- package-lock.json
- package.json
- shared/js/background/https.es6.js
This should help with package-lock issues on CI.
> Switch to npm version of jsbloom

- integration-test/background/click-to-load-integration-tests.js
**Reviewer:**
This test seems a little flaky - I'm wondering if this might help.
> Https URL for click to load tests

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
**Reviewer:**
- Remove innerHTML in favor of text nodes #630
- CSR cookies #631 
- Merge autofill #632
> Bump version to 2021.5.4

- CONTRIBUTING.md
> updated gruntjs' link and changed it to grunt-cli

- shared/js/background/classes/site.es6.js
**Reviewer:**
Fixes #381. Opening in favour of #425 to rebase and fix regex issue.
> Local files should not be graded

- shared/js/ui/templates/feedback-form.es6.js
**Reviewer:**
There is an issue with the feedback backend, meaning it reports an error, even though the feedback is successfully submitted. This fixes the client side by reporting that feedback was successfully submitted even if there was an error with the request.
https://app.asana.com/0/276630244458377/1200216229834078/f
> Suppress errors when submitting feedback

- shared/js/content-scope/cookie-protection.js
- shared/js/content-scope/protections.js
Bugfix for https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/636
1. Visit: https://www.igniteprocurement.com/
2. See the errors are gone in the console (this was a race condition so didn't always fire)
> Fixing timing issues with updates that fired earlier than the init call

- browsers/chrome/_locales/en/messages.json
- browsers/chrome/_locales/en_GB/messages.json
> Update chrome store description

- shared/js/content-scope/canvas-protection.js
- shared/js/content-scope/canvas.js
- unit-test/background/canvas.js
> Add Canvas unit test

- integration-test/background/grades.js
> Amend grading test for reddit.com

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
I updated the icons in #558, need to change the default icon too. Switching to a single icon size looked fine to me https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action
> update default icon

- integration-test/background/storage.js
> Wait for tds in storage integration test

- shared/js/content-scope/floc-protection.js
Fixes: #671
**Reviewer:** @sammacbeth @kdzwinel 
Extensions are likely causing a conflict with our code, so let's throw away the error.
> Wrap floc code in try

- shared/data/web_accessible_resources/moatheader.js
https://app.asana.com/0/inbox/1199237043596759/1200327303839559/1200342250073730
> Add moat add surrogate

- shared/js/background/classes/site.es6.js
**Reviewer:** @sammacbeth and @kdzwinel
> Add www. back into safelisting

- shared/data/web_accessible_resources/analytics.js
**Reviewer:** @dharb or @jdorweiler 
https://app.asana.com/0/inbox/1199237043596759/1200366914256457/1200363318819573
> Support getAll to get a Tracker object

- shared/js/background/classes/site.es6.js
**Reviewer:** @kdzwinel and @GioSensation
> Handle www. differently only for broken sites

- shared/js/content-scope/gpc-protection.js
**Reviewer:** @dharb or @sammacbeth 
Sometimes we are throwing errors when applying GPC to the page, it's most likely caused by conflicting with an alternate extension.
> Catch errors that are thrown by applying GPC

- shared/js/background/chrome-wrapper.es6.js
> Change chrome.extension.getURL to chrome.runtime.getURL

- shared/js/ui/templates/breakage-form.es6.js
- shared/js/ui/views/breakage-form.es6.js
https://app.asana.com/0/0/1200504149685841/f
* Make breakage report category optional
* Update category list
> Site breakage form updates

- shared/js/background/chrome-events.es6.js
Check if a site is broken before blocking 3p cookies
1. Visit a site on the temp allow list
2. Verify 3p cookies are not blocked
> Check broken site list for cookies

- shared/js/background/classes/site.es6.js
- shared/js/background/classes/tab.es6.js
- shared/js/background/redirect.es6.js
- shared/js/ui/models/site.es6.js
- shared/js/ui/templates/shared/grade-scorecard-grades.es6.js
- shared/js/ui/templates/shared/grade-scorecard-reasons.es6.js
- shared/js/ui/templates/shared/hero.es6.js
- shared/js/ui/templates/shared/rating-hero.es6.js
- shared/js/ui/templates/shared/tracker-network-icon.es6.js
- shared/js/ui/templates/shared/tracker-networks-text.es6.js
- shared/js/ui/templates/site.es6.js
- shared/js/ui/templates/tracker-networks.es6.js
- shared/js/ui/views/site.es6.js
- shared/js/ui/views/tracker-networks.es6.js
- shared/scss/_vars.scss
- shared/scss/base/base.scss
- shared/scss/popup.scss
Ensure we count broken site trackers and displaying this to users.
https://app.asana.com/0/0/1200517965702747/f
> Fix counting of trackers

- shared/js/background/chrome-events.es6.js
> Never block cookies on main_frame requests.

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
* Updated autofill (#716).
* Fixed an issue where first-party cookies were blocked incorrectly (#709).
* Fix an error with audio fingerprinting protection in Firefox (#710).
* Fix the display of trackers in the popup when protection is temporarily disabled for a site (#704).
* Fix 3rd party cookie not disabling when protection is temporarily disabled for a site (#707).
* Cross-platform reference tests for tracker blocking (#703).
* Updated the site breakage submit form (#699).
* Fixed a silent error on the settings page (#705).
* Added support for managed settings (#643).
> Release 2021.7.5

- integration-test/background/test-fingerprint.js
- shared/js/content-scope/do-not-track-protection.js
- shared/js/content-scope/protections.js
> Remove DNT navigator change

- shared/js/background/chrome-events.es6.js
**Reviewer:** @SlayterDev 
Adding this in case we need it sooner. Thanks for spotting this!
> Remove unused floc code

- README.md
> Update build status badge to point to Github Actions

- shared/js/content-scope/hardware-protection.js
> Change cores count to 2

- shared/js/background/chrome-events.es6.js
- shared/js/background/email-utils.es6.js
**Reviewer:** @alistairjcbrown 
**Asana:** https://app.asana.com/0/1162895505193104/1200571733782385/f
Fixes a bug that prevented autofill from being enabled automatically on first installation on Chrome. We were trying to read settings before they were ready, hence the error. I have now added `settings.ready()` before we proceed and things are fine 🙂. I've also taken the chance to improve the code a little bit.
Steps on [Asana](https://app.asana.com/0/1162895505193104/1200571733782385/f).
> Fix enable autofill in Chrome

- shared/js/background/utils.es6.js
This PR makes processing sites from `aboutBlank` or `sites` keys safer and more in line with new config structure.
> Restructure aboutBlank/sites processing

- shared/js/background/utils.es6.js
- unit-test/background/classes/site.es6.js
> Fix domain matching

- shared/js/background/events.es6.js
- shared/js/background/redirect.es6.js
- shared/js/background/utils.es6.js
Implement exception lists into contentBlocking and GPC headers
1. Go to https://privacy-test-pages.glitch.me/privacy-protections/request-blocking/
2. Add glitch.me to contentBlocking exceptions via debugger
3. Content should not be blocked.
> Respect contentBlocking exception list

- shared/js/background/events.es6.js
- shared/js/background/redirect.es6.js
This updates console logs that point to the unprotected repo. Repo URL subject to change.
1. Visit an unprotected site
2. Verify logs point to the right place
> Update unprotected repo logs

- package-lock.json
- package.json
**Release notes:**
- Fix Dax showing on email signup page 📧
Tested in https://github.com/duckduckgo/duckduckgo-autofill/pull/12.
> Update autofill to 3.1.1

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
> Bump version

- shared/js/background/redirect.es6.js
**Reviewer:** @GioSensation @sammacbeth 
`thisTab` was being checked in cases where it didn't exist. This PR moves it a bit later and performs an extra check for the tab.
1. Go to https://www.wga.com/users/ron-ratto
2. Click on the Pinnacle logo
3. The page opens in a new tab
4. Open the popup → 2 trackers found
> Perform tab check later and safer

- package-lock.json
- package.json
**Reviewer:** NA
Update autofill to version 3.2.0
- Use global event handlers for clicks on the tooltip and for form submission
- https://app.asana.com/0/72649045549333/1200085115126414
Tested during autofill release.
> Update autofill to 3.2.0

- package-lock.json
- package.json
Just updating the autofill dependency.
> Update autofill to 3.2.1

- shared/js/content-scope/fingerprinting-canvas-protection.js
> Add in canvas debugging methods

- shared/js/background/classes/site.es6.js
- shared/js/background/classes/tab.es6.js
- shared/js/background/events.es6.js
- shared/js/background/https.es6.js
- shared/js/background/redirect.es6.js
- shared/js/background/tracker-utils.js
- shared/js/background/utils.es6.js
- unit-test/background/click-to-load-tests.js
- unit-test/background/tracker-utils-tests.js
**Reviewer:**
This is to simplify checks into the same file so we can add denylisting
> Simplify allowlisting calculation to allow for adding further features

- shared/js/background/classes/site.es6.js
- shared/js/background/devtools.es6.js
- shared/js/background/events.es6.js
- shared/js/background/tab-manager.es6.js
- shared/js/ui/models/site.es6.js
- shared/js/ui/models/whitelist.es6.js
- shared/js/ui/templates/site.es6.js
- shared/js/ui/views/site.es6.js
- shared/scss/popup.scss
- test/tests/sites.js
**Reviewer:**
Depends on: https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/778
Implements the ability for the user to deny our overriding of the toggle.
> Denylisting

- README.md
**Reviewer:** @Charlie-belmer, @sammacbeth  and @kdzwinel
> Explain extension features in the README

- shared/js/ui/models/site.es6.js
**Reviewer:**
Spotted whilst doing: https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/783 the issue prevents sending the pixel based on the recent change: https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/779
> Fix allowlisting pixel

- package-lock.json
- package.json
- shared/js/background/events.es6.js
The domain regex was too lax. See https://app.asana.com/0/1198964220583541/1200753317890790/f.
> Fix domain regex and update autofill to 3.2.2

- shared/js/ui/models/site.es6.js
- shared/js/ui/templates/site.es6.js
**Reviewer:** @kdzwinel  or @GioSensation
> Fix tracker reporting and naming of allowlisted html

- .gitmodules
- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- package.json
- scripts/bumpVersion.js
**CC:** @kdzwinel, @sammacbeth 
This adds `npm run release update` so that we can easily update the extension whilst cutting a release.
Is there anything else we do in these merge commits just prior to merging that we should update automatically?
This update has changed some indenting but will not do this in future.
1. Run `npm run release update`
2. Check versions have updated
> Cutting a release changes

- unit-test/background/tracker-reference-tests.js
**Reviewer:**
Support for surrogate reference tests as defined in https://github.com/duckduckgo/privacy-reference-tests/pull/6 (which needs to be merged before this PR)
1. Checkout https://github.com/duckduckgo/privacy-reference-tests/pull/6 in duckduckgo-privacy-extension/unit-test/background/reference-tests
2. `npm test`
> support surrogate ref tests

- integration-test/background/storage.js
- shared/js/content-scope/tracking-cookies-3p-protection.js
**Reviewer:**
Tests for the fix in #797 . The issue however was only happening in Firefox, so the test doesn't actually surface the issue when the patch is removed. However the tests do show the steps to reproduce the issue in Firefox. There does seem to be a different periodic failure related to 3rd party JS cookie blocking on chrome though: https://github.com/duckduckgo/duckduckgo-privacy-extension/runs/3302776725?check_suite_focus=true
> Tests for 3rd party JS cookie blocking

- .github/workflows/publish.yml
- .github/workflows/stage.yml
- package.json
- scripts/bumpVersion.js
**Reviewer:**
Adds two CI jobs to improve the release process:
1. **Stage Release** - a manually triggered pipeline which will create a PR to `develop` to prepare for a new release. When triggering the release DRI provides the version number to bump to.
2. **Publish Builds** - triggered when a tag is pushed: creates extension builds for all platforms. This allows the release DRI to generate a release without needing to have a build environment set up.
> Release automation

- Gruntfile.js
- browsers/chrome/manifest.json
- package-lock.json
- package.json
- shared/js/background/csp-blocking.es6.js
- shared/js/background/devtools.es6.js
- shared/js/background/email-utils.es6.js
- shared/js/background/events.es6.js
> Initialise the use of the browser shim for simple background changes

- shared/js/background/devtools.es6.js
- shared/js/background/redirect.es6.js
**Reviewer:**
Fixes:
https://app.asana.com/0/892838074342800/1200955361390255/f
Also untested as working on something else.
> Make debugging matchedRule.rule optional to remove error

- shared/js/background/tracker-utils.js
- shared/js/background/utils.es6.js
- shared/js/background/wrapper.es6.js
To reduce the changes in: https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/843
> Change to native exporting as a prereq for browser shim

- shared/js/background/background.es6.js
- shared/js/background/events.es6.js
- shared/js/background/utils.es6.js
- shared/js/shared-utils/parse-user-agent-string.es6.js
- shared/js/ui/base/ui-wrapper.es6.js
**Reviewer:**
Removes the dependency on window.localStorage which isn't accessible in a worker scope.
> Migrate from using localStorage

- shared/js/background/load.es6.js
- shared/js/background/storage/https.es6.js
- shared/js/background/storage/tds.es6.js
(Stolen code from Konrad)
Creating as a draft as haven't tested this at all. Stole from Konrads branch.
> Migrate to using fetch

- shared/js/background/events.es6.js
- shared/js/background/redirect.es6.js
- shared/js/background/tracker-utils.js
- shared/js/content-scripts/click-to-load.js
> Remove user preference code for social trackers as unused

- shared/js/background/events.es6.js
These arguments are unused so removing.
> Remove unused getLists argument

- shared/js/content-scope/gpc-protection.js
This fixes #855.
**Reviewer:**
> Use `Navigator.prototype` for GPC signal injector

- shared/js/background/atb.es6.js
- shared/js/background/events.es6.js
Function doesn't accept an argument, so this is unused.
> Remove unused updateSetAtb argument

- Gruntfile.js
- browsers/chrome/manifest.json
- shared/js/background/atb.es6.js
- shared/js/background/channel.es6.js
- shared/js/background/csp-blocking.es6.js
- shared/js/background/devtools.es6.js
- shared/js/background/email-utils.es6.js
- shared/js/background/events.es6.js
- shared/js/background/wrapper.es6.js
- unit-test/background/atb.es6.js
- unit-test/background/click-to-load-tests.js
- unit-test/background/https.es6.js
- unit-test/background/mock-browser-api.js
- unit-test/background/storage/https.es6.js
Another carve out before the complicated one.
> Convert any background chrome API usage that's not using a callback

- shared/js/background/storage/tds.es6.js
This fixes the errors you reported:
```
Error in event handler: TypeError: Cannot read properties of undefined (reading 'includes')
at Site.isFeatureEnabled (<URL>)
at Site.isContentBlockingEnabled (<URL>)
at handleRequest (<URL>)
at subEventCallback (extensions::webRequestEvent:81:32)
```
Ultimately the better fix here is have a clean init and install phase that waits on all the dependencies.
We should be in a better place for this after #843 when all the message handlers are moved out of events and we can restructure some more.
> Fix start up config error

- shared/js/background/events.es6.js
> Ignore errors for tabs that aren't listening

- .github/workflows/stage.yml
We no longer need to update the submodule.
> No submodule to update anymore

- shared/js/background/redirect.es6.js
> Update blocking status when protections disabled

- package.json
- scripts/buildEntityMap.js
- scripts/httpsAllowlist.js
- scripts/tosdr.js
> Add scripts/ to linting

- shared/js/content-scope/utils.js
To fix https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/929 from the extension site to ensure a missing key doesn't break a feature.
1. Check out the config and remove the disabled lines from index.js
2. Ensure the generated/ output doesn't have fingerprintingCanvas in it
3. cd generated/ && npx http-server
4. Edit the config to point to this webserver:
```
diff --git a/shared/data/constants.js b/shared/data/constants.js
index aea733ac..e08f1e96 100644
--- a/shared/data/constants.js
+++ b/shared/data/constants.js
@@ -104,7 +104,7 @@ module.exports = {
},
{
"name": "config",
-            "url": "https://staticcdn.duckduckgo.com/trackerblocking/config/v1/extension-config.json",
+            "url": "http://localhost:8080/extension-config.json", …
```
> Ensure we allow for when a feature is disabled in the config

- Gruntfile.js
- package-lock.json
- package.json
- unit-test/background/tracker-reference-tests.js
In https://github.com/duckduckgo/privacy-reference-tests/pull/13 we removed surrogates.js file and replaced it with surrogates.txt to be closer to the actual configuration file.
Run tests! Or trust Github Actions to do so :)
> Read surrogates.txt instead surrogates.js

- package-lock.json
- package.json
**Reviewer:** @Charlie-belmer 
This PR brings together:
- additional tests that check for a CNAME related edge-case that we found (update of reference-tests submodule)
- and a fix for a bug we had related to that edge-case (update of privacy-grade package)
Note that bunch of other files were updated in the reference-tests repo, but that's unrelated. The relevant here change is https://github.com/duckduckgo/privacy-reference-tests/compare/bfaa7d497341419b4b8c1b4b0c96fe2da2e6ae17...ac33e76a15caac5e03c7752a3ad150f1b9099db5#diff-1c95c4a4033bb55c3e220061a1f70aba4195c9624933a9389f88732cdd35809b
Run the tests! Or trust Github Actions to do it well :)
> CNAME edge-case fix

- shared/data/web_accessible_resources/fb-sdk.js
- shared/js/content-scripts/click-to-load.js
- shared/js/content-scripts/fb-surrogate-xray.js
**Reviewer**: @jonathanKingston
**Cc**: @Charlie-belmer, @ladamski
https://app.asana.com/0/312629933896096/1201481772157517/f
A couple of further Click to Play code improvements that I've spit-out from my project work. I've combined the changes into one PR, but please don't squash the commits!
Summary of changes:
1. I've renamed the CTP events, so that they all start with "ddg-ctp-" or "ddg-ctp-entity-". The existing event names are OK, but I found it quickly got confusing as I added more related events. Having a consistent prefix made the events a lot easier to reason about and find in the code.
2. I've tweaked the onload event listener so that it only fires once. This was a subtle bug which caused problems with my project work.
1. Ensure the Facebook Click to Load functionality still …
> Click to Play code improvements 2

- shared/js/content-scripts/click-to-load.js
**Reviewer**: @jonathanKingston
**Cc**: @Charlie-belmer, @ladamski
Small change to improve the JSDoc comment of the `createReplacementWidget` function. The parameters weren't properly listed.
N/A
> Improve JSDoc comment for the CTP createReplacementWidget function

- shared/js/content-scripts/click-to-load.js
**Reviewer**: @jonathanKingston
**Cc**: @Charlie-belmer, @ladamski
Small change to promisify the `sendMessage` function in the Click to Play code. I split this out from my project work as it changes the indentation level of quite a lot of code and was going to make reviewing my changes a pain.
1. Ensure the Facebook Click to Load functionality still works OK on the test page https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/
> Promisify message sending in the Click to Play code

- shared/scss/views/_breakage-form.scss
https://app.asana.com/0/660109987080042/1144268132302183/f
1.  Open the site report
2. Check the text looks as above
> Remove bolding from site report text

- shared/data/constants.js
- shared/js/background/https.es6.js
- unit-test/background/reference-tests/https-upgrades-tests.js
- unit-test/helpers/mock-browser-api.js
As discussed in https://app.asana.com/0/0/1201277458549580/f this PR integrates standard set of tests for smarter encryption / https upgrades.
Only interesting part hers is that I found a small bug - we were not upgrading ws:// to wss://, so I fixed it, but it turns out that we were not capturing websocket requests at all. So now we are not only upgrading them, but also blocking them (if they match a known tracker). I think that's fine because other platforms (e.g. Safari extension) are blocking those since always.
1. Make sure that tests pass.
2. Verify that ws:// gets upgraded to wss://:
- you can sorta do it by running test on http://privacy-test-pages.glitch.me/privacy-protections/https-upgrades/ and then testing if background page reports "HTTPS: …
> Integrate reference tests for HTTPS upgrades / Smarter Encryption

- Gruntfile.js
- karma.conf.js
- package.json
- shared/js/ui/models/site.es6.js
- shared/js/ui/models/submit-breakage-form.es6.js
- unit-test/background/reference-tests/broken-site-reporting-tests.js
- unit-test/helpers/mock-browser-api.js
**Reviewer:** Sam
Reference tests for broken site reporting.
I also made some tweaks to test running setup.
Mostly just run tests, but I also touched the reporting form in the popup, so please make sure that it still works as expected.
> References Tests: Broken Site Reporting

- .github/workflows/stage.yml
**Reviewer:**
Indentation of the yaml file was broken.
> Fix workflow error

- integration-test/background/https-loop-protection.js
- shared/js/background/redirect.es6.js
See: https://app.asana.com/0/892838074342800/1201065068115223/f
1. Go to: https://good.third-party.site/privacy-protections/https-loop-protection/
2. Click start test
Ensure the result is http://
> Reenable https loop detection

- shared/data/constants.js
- shared/js/background/events.es6.js
Note: This PR changed in scope since the bulk of the logic will now be implemented in https://github.com/duckduckgo/content-scope-scripts
This PR is now just here to provide `platform.name` to the args that get passed to the content scripts.
> Adding platform.name = "extension" to be used by the new navigator interface

- shared/js/background/events.es6.js
This is triggered by the autofill registration not passing these args yet.
https://app.asana.com/0/312629933896096/1201651398928035/f
> Fix missing register arg

- shared/js/background/atb.es6.js
- shared/js/background/settings.es6.js
- unit-test/background/atb.es6.js
> ATB storage fix

- integration-test/background/atb.js
**Reviewer:**
https://app.asana.com/0/892838074342800/1201756947090679/f
Tests that we successfully get the stored ATB from storage when the extension reloads.
> Test ATB is loaded from storage on reload.

- integration-test/background/click-to-load-facebook.js
- integration-test/background/click-to-load-youtube.js
- integration-test/data/configs/click-to-load-facebook.json
- integration-test/data/configs/click-to-load-youtube.json
- integration-test/helpers/testConfig.js
Some integration tests depend on parts of the extension
configuration. We set those parts of the configuration manually, to
ensure the tests will run consistently. In the past, the test
configuration was hard-coded in the integration test files, but here
we move the test configurations out into separate JSON files for
improved readability.
**Reviewer:** @kdzwinel
> Move integration test configurations into separate JSON files

- package-lock.json
- package.json
- shared/js/background/events.es6.js
- shared/js/background/message-handlers.js
**CC:** @GioSensation 
Add a new message type to get user data for the email web app settings page.
1. Build extension
2. Go to settings route on email web app
3. Confirm Autofill tab shows on settings page
> Get data from device for email settings page

- unit-test/background/reference-tests/tracker-reference-tests.js
This includes a check for the exceptPlatforms entry of the TDS tests
since the "ports are ignored when matching rules" entry was failing.
**CC:** @SlayterDev
> Update the privacy-reference-tests dependency

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/data/bundled/extension-config.json
- shared/data/etags.json
- #1059 — @kzar 
- #1074 — @kzar 
- #1044 (includes autofill version 4.0.0) — @alistairjcbrown 
Check the test task in Asana.
> Prepare release 2022.3.4

- .github/workflows/stage.yml
> Create branch only if it doesn't exist

- .gitignore
- .gitmodules
- Gruntfile.js
- package-lock.json
- package.json
> Npm modules

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/data/bundled/extension-config.json
- shared/data/etags.json
> Prepare release 2022.3.30

- CONTRIBUTING.md
> Update CONTRIBUTING.md with module dev instructions

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/data/bundled/extension-config.json
- shared/data/etags.json
**Reviewer:** 
Merges in the changes added in the release.
> Prepare release 2022.4.18

- .github/workflows/tests.yml
So far, test artifacts are only actually saved if the tests pass! We
will need the test artifacts to debug failures - that is their whole
purpose!
Check that the CI is still running OK and that the test artifacts are still being saved.
> Ensure test artifacts are saved on failure

- integration-test/data/api_schemas/facebook-sdk.json
- shared/data/web_accessible_resources/fb-sdk.js
**CC:** @kdzwinel, @ladamski, @Charlie-belmer 
The Facebook SDK schema has changed, let's get the schema test passing again and make the corresponding change to the surrogate sscript.
- Ensure integration tests still pass.
- Smoke test Facedbook Click to Load, e.g. [with the test page](https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/).
> Update Facebook surrogate script for CheckboxPlugin SDK change

- integration-test/data/api_schemas/facebook-sdk.json
The changes are to FB.Canvas which is not mocked at all by the
surrogate script, so corresponding changes to the surrogate script
aren't required.
1. Check that the integration tests are passing.
> Update expected Facebook SDK schema

- integration-test/helpers/backgroundWait.js
- shared/js/background/background.es6.js
- shared/js/background/debug.es6.js
- shared/js/background/events.es6.js
- shared/js/background/message-handlers.js
- shared/js/background/startup.es6.js
- shared/js/background/storage/tds.es6.js
- shared/js/content-scripts/click-to-load.js
There are numerous race conditions caused by attempting to use
extension configuration before it has finished loaded. These race
conditions can cause exceptions in the background page on extension
install, exceptions in the first run page and integration test
failures.
To resolve some of those let's:
- Split the extension startup logic out into a separate module and
provide a ready() Promise that can be checked for when the
extension's startup sequence has been completed. That is especially
useful, since it provides an easy way to know that the Trackers
Object is ready for use.
- Provide a TDS storage ready() function that can be used to check if
all TDS configurations (or one specific configuration) have
finished loading. That is useful, for example, to wait for the
Click to Load …
> Add ready() Promises for TDS storage and extension startup

- shared/js/devtools/panel.es6.js
**Reviewer:**
https://app.asana.com/0/0/1202340939105722/f
Depends on https://github.com/duckduckgo/content-scope-scripts/pull/77
> Append callstack messages to jscookie rows

- integration-test/background/storage.js
- package-lock.json
- package.json
- shared/data/bundled/extension-config.json
- shared/data/etags.json
- shared/js/background/helpers/arguments-object.js
- unit-test/background/reference-tests/3p-cookies-tests.js
- unit-test/background/reference-tests/expire-1p-tracking-cookies.js
https://app.asana.com/0/0/1202348774384668/f
> Simpler cookie policy

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
> Prepare release 2022.5.30

- shared/js/background/wrapper.es6.js
With Chrome Manifest V3, the extension's background page is replaced
with a ServiceWorker. That ServiceWorker is destroyed and recreated
regularly, so the extension's state can no longer be maintained in
memory in the same way. Instead, the new chrome.storage.session[1] API
must be used to keep track of any state that can't be preserved to
disk.
Since chrome.storage.session is not available on other platforms yet,
let's add wrappers that fall back to a Map. That way, the extension's
state can be stored in a consistent way for all platforms.
This change is heavily based on @jonathanKingston's earlier work[2]. Full
credit to Jonathan for this change.
Note: The storage.session API is not Promisified by webextension-polyfill
like may of the other wrapped APIs. That is OK however, since …
> Add session storage wrapper

- shared/js/background/tracker-utils.js
- unit-test/background/tracker-utils-tests.js
**Reviewer:** @SlayterDev, @sammacbeth or @kzar 
https://app.asana.com/0/0/1202375243913314/f and also see: https://github.com/duckduckgo/privacy-configuration/issues/242
> Allow entity check for non trackers

- package-lock.json
- package.json
https://app.asana.com/0/0/1202363130524067/f
Bump content scope to 2.0.3
> Bump content scope

- .github/workflows/tests.yml
- integration-test/background/onboarding.js
- integration-test/config-mv3.json
With a few tweaks to replace references to `window` the onboarding
integration tests can run. Let's enable them now.
1. Check the MV3 integration tests are being run by the GitHub CI and are passing.
> Get onboarding integration tests running for Chrome MV3

- package-lock.json
- package.json
deps: bump autofill to 4.6.0
I've manually tested email protection sign in/out + autofilling emails on both firefox and chrome.
> deps: bump autofill to 4.6.0

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/data/bundled/extension-config.json
- shared/data/etags.json
> Prepare release 2022.6.15

- shared/js/background/events.es6.js
- shared/js/background/load.es6.js
- shared/js/background/storage/https.es6.js
- shared/js/background/storage/tds.es6.js
The TDS and HTTPS storage classes handle both storing and periodically
updating the extension configuration files. In order to know when an
update is required, the first step is to know both when a
configuration file was last updated and how frequently the
configuration file should be updated.
For that, let's:
- Move the update period into the respective classes.
- Take note of the lastUpdate time each time a configuration is
fetched (even if there weren't any changes).
Note: It is suboptimal how we are saving the lastUpdate field in
localStorage via the settings abstraction, instead of in
IndexedDB along with the rest of the configuration data. We're
doing it this way for two reasons.
1. Firstly, we need to update the lastUpdate time even if there
was no changes to the configuration. It …
> Include update timing information in TDS + HTTPS storage classes

- shared/js/background/startup.es6.js
- shared/js/background/storage/https.es6.js
- shared/js/background/storage/tds.es6.js
- unit-test/background/storage/https.es6.js
- unit-test/helpers/tds.es6.js
When the extension starts up, `httpsStorage.getLists()` and
`tdsStorage.getLists()` are called to load some of the extension's
configuration files. Those files are necessarily fetched remotely when
the extension is first installed, and periodically to keep them up to
date. But until now, the files were also fetched each time the
extension was restarted.
That wasn't a problem before, since with MV2 extensions the background
page can persist for a long time. But with the transition to MV3 that
is no longer the case - the background ServiceWorker is restarted
constantly. So let's tweak the `getLists()` methods to accept a
`preferLocal` parameter to avoid the files being fetched every time
the background ServiceWorker is restarted.
Note: Since entity tags were being utilised, the responses …
> Make use of locally saved TDS and HTTPS storage on extension startup

- .eslintrc
- package-lock.json
- package.json
- shared/data/constants.js
- shared/html/options.html
- shared/js/ui/base/index.es6.js
- shared/js/ui/base/localize.es6.js
- shared/js/ui/pages/options.es6.js
- shared/js/ui/pages/popup.es6.js
- shared/js/ui/templates/allowlist-items.es6.js
- shared/js/ui/templates/allowlist.es6.js
- shared/js/ui/templates/privacy-options.es6.js
- shared/js/ui/templates/user-data.es6.js
- shared/locales/en/options.json
- shared/locales/en/shared.json
**Reviewer:**
https://app.asana.com/0/1163321984198618/1170756233954550/f
> localization support, localize settings views

- package-lock.json
- package.json
Update the content-scope-scripts dependency to include a small bug fix
for a typo with a debugHelper() call. With this fix, the developer
tools panel should more accurately list applied cookie protections.
1. Navigate to https://privacy-test-pages.glitch.me/privacy-protections/storage-blocking/ in a new tab and open the page console.
2. Install the extension, open the options page and change `options.html` in URL to `devtools-panel.html`.
3. When dev tools page loads, select "storage blocking test page" in the top right drop down. Then click "Clear" and "Reload page" buttons.
4. Switch back to the storage blocking test page, and click "Store data".
5. Ensure that exceptions are not displayed in the console and "JS🍪 restrict (expiry)" items are listed in …
> Update content-scope-scripts dependency

- shared/js/background/classes/tab.es6.js
- shared/js/background/redirect.es6.js
- shared/js/background/tab-manager.es6.js
Reverts duckduckgo/duckduckgo-privacy-extension#1236
Reverting due to this causing an issue logging out of twitter.
Asana task: https://app.asana.com/0/1200223097357040/1200964410565699/f
> Revert "Properly handle requests initiated by ServiceWorkers"

- README.md
Since we are now also capping the expiry of cookies set by first-party
and non-tracking scripts, we should make that clearer in the README.
**CC:** @kdzwinel 
**Depends on:** 
-->
> Update cookie expiry explanation in README

- package-lock.json
- package.json
- shared/js/background/allowlisted-trackers.es6.js
- shared/js/background/amp-protection.es6.js
- shared/js/background/atb.es6.js
- shared/js/background/classes/https-redirects.es6.js
- shared/js/background/classes/site.es6.js
- shared/js/background/classes/tab.es6.js
- shared/js/background/devtools.es6.js
- shared/js/background/https.es6.js
- shared/js/background/load.es6.js
- shared/js/background/privacy-practices.es6.js
- shared/js/background/redirect.es6.js
- shared/js/background/storage/tds.es6.js
- shared/js/background/tab-manager.es6.js
- shared/js/background/tracker-utils.js
- shared/js/background/utils.es6.js
- shared/js/background/wrapper.es6.js
- shared/js/shared-utils/parse-user-agent-string.es6.js
- shared/js/shared-utils/sha1.js
- tsconfig.json
**Reviewer:** @kzar, @sammacbeth or @shakyShane
Add initial tsc linting, depends on: https://github.com/duckduckgo/privacy-grade/pull/43
> Add initial tsc checks

- package-lock.json
- package.json
https://app.asana.com/0/312629933896096/1202533910636853/f
Latest Autofill - no functional changes to the extension, but does include accuracy improvements etc.
> chore(deps): update Autofill to version 4.7.0

- shared/js/background/events.es6.js
The tracker-utils code does not work correctly until the extension
startup sequence has completed (startup.ready() has
resolved). Take care to check that startup has finished before
enabling tracker blocking or third-party cookie blocking. This fixes a
number of exceptions shown in the background console on extension
install.
Note that this approach is not ideal, since registering event
listeners asynchronously is not possible with Chrome MV3. It's
possible here since the event listeners are MV2 only, but the pattern
should generally be avoided.
See https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#event_listeners
**Reviewer:** @sammacbeth  
CC: @SlayterDev 
1. Install the extension (use Chrome) and check that the 3p cookie protection related exceptions aren't …
> Wait for extension startup before enabling cookie protections

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/data/bundled/extension-config.json
- shared/data/etags.json
> Prepare release 2022.7.18

- shared/js/background/amp-protection.es6.js
- shared/js/background/atb.es6.js
- shared/js/background/classes/site.es6.js
- shared/js/background/classes/tab.es6.js
- shared/js/background/devtools.es6.js
- shared/js/background/events.es6.js
- shared/js/background/events/3p-tracking-cookie-blocking.js
- shared/js/background/events/referrer-trimming.js
- shared/js/background/redirect.es6.js
- shared/js/background/storage/tds.es6.js
- shared/js/background/tab-manager.es6.js
- tsconfig.json
https://app.asana.com/0/0/1202638483988584/f
This:
- removes some unnecessary `@ts-ignore` declarations
- adds some types to help the typechecker
- replaces some `@ts-ignore` declarations with appropriate typing
- updates the `tsconfig.json` to check as many `shared/js/*` files as possible, without requiring functional changes or additions of `@ts-ignore`
- removes an instance of `@ts-nocheck`
There are NO FUNCTIONAL CHANGES. This does not touch any code but comments and the `tsconfig.json`
1. Run `npm run tsc` - if this passes then everything should be good
> Add and fix more type comments

- integration-test/background/click-to-load-facebook.js
This test is permafailing and we're just ignoring it. We should fix it properly but for now I'd like ci to go green.
https://app.asana.com/0/312629933896096/1202683879327693/f
> Reduce count check in ctl facebook as failing in ci

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/data/bundled/extension-config.json
- shared/data/etags.json
**Reviewer:** @shakyShane or @kzar
> Prepare release 2022.7.26

- .gitattributes
- .gitignore
**Reviewer:**
Removes unnecessary files from diffs.
> Add ignore and attr changes

- package-lock.json
- package.json
- shared/js/background/email-utils.es6.js
- shared/js/background/wrapper.es6.js
- shared/js/ui/base/ui-wrapper.es6.js
- shared/js/ui/models/site-company-list.es6.js
Additionally support debugging tabId param for the panel.
Ignore session errors for browser.storage.session as not in the types.
**Reviewer:** @shakyShane
> Migrate to browser polyfill for ui-wrapper.

- shared/js/background/classes/site.es6.js
- shared/js/background/redirect.es6.js
- shared/js/ui/models/mixins/calculate-aggregation-stats.js
> Fix states to be ignore-user to correctly grade the page

- shared/js/ui/templates/shared/grade-scorecard-reasons.es6.js
https://app.asana.com/0/0/1202768361762827/f
> Fix major networks text

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/data/bundled/extension-config.json
- shared/data/etags.json
> Prepare release 2022.8.9

- shared/js/devtools/panel.es6.js
**Reviewer:**
https://app.asana.com/0/312629933896096/1202767747178168/f
> Add new reasons to the devtool panel

- integration-test/background/test-fingerprint.js
**Reviewer:** @sammacbeth or @kzar or @GuiltyDolphin 
Wikipedia is failing to load in automation, perhaps they've started blocking GH actions aggressively (ideally we shouldn't be loading remote resources in automation but here we are)
As a quick fix I have swapped out wikipedia for duckduckgo to ensure the fingerprint tests are still working.
https://app.asana.com/0/312629933896096/1202795530517690/f
> Fix wikipedia test failing

- .eslintrc
- integration-test/background/atb.js
- integration-test/background/click-attribution.js
- integration-test/background/click-to-load-facebook.js
- integration-test/background/click-to-load-youtube.js
- integration-test/background/url-parameters.js
- integration-test/content-scripts/gpc.js
- integration-test/content-scripts/test-canvas.js
- integration-test/helpers/apiSchema.js
- integration-test/helpers/backgroundWait.js
- integration-test/helpers/testConfig.js
- scripts/asana-release.js
- shared/js/background/devtools.es6.js
- shared/js/background/helpers/arguments-object.js
- shared/js/background/load.es6.js
- shared/js/background/onboarding.es6.js
- shared/js/background/storage/tds.es6.js
- shared/js/background/utils.es6.js
- shared/js/content-scripts/click-to-load.js
- shared/js/ui/base/localize.es6.js
- unit-test/background/atb-utils.es6.js
- unit-test/background/reference-tests/fingerprinting-protection-tests.js
**Reviewer:** @kzar or @GioSensation 
After https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/1308 it's clear we should enable no-shadow to avoid similar mistakes in future.
> Enable no-shadow ESLint rule and apply relevant fixes to code

- package-lock.json
- package.json
Update to: https://github.com/duckduckgo/tracker-surrogates/pull/3
https://app.asana.com/0/0/1202795530517779/f
> Update tracker-surrogates to namespaced version

- unit-test/background/reference-tests/3p-cookies-tests.js
**Reviewer:** @SlayterDev 
Removes the references to files which aren't there as the feature isn't implemented currently and doesn't have test files.
Points to: https://github.com/duckduckgo/privacy-reference-tests/pull/54 which we should merge first and I update the reference for (to avoid broken histories again)
https://app.asana.com/0/312629933896096/1202815437790503/f
> Update reference tests, fixing the missing files and reference

- .gitignore
- .gitmodules
- package-lock.json
- package.json
**Reviewer:** @kdzwinel, @SlayterDev or @ladamski 
Moving to an npm module so dependabot will nag us when tests change.
https://app.asana.com/0/0/1202815836919368/f
> Move privacy-reference-tests to npm module

- CONTRIBUTING.md
> Remove wording of using submodules as no longer needed

- README.md
Replace "Features" section with a link to the new help page describing protections.
Add link to Opera and mention other chromium based browsers.
n/a
> Link Web Tracking Protections help page

- shared/scss/_mixins.scss
- shared/scss/popup.scss
Task: https://app.asana.com/0/892838074342800/1202842358782954/f
- Reduces the height of the popover contents so scrolling isn't required
- Updates overflow to not always show scrollbar
For the screenshots below, "Show scroll bars" on macOS was set to "Always"
No email protection | Email protection (not scrolled) | Email protection (scrolled)
--- | --- | ---
1. Use this build of the extension
2. When not signed into email protection, go to a webpage and view the popover
- The popover will not scroll, and no scrollbar is visible
3. Sign into email protection, go to a webpage and view the popover
- The popover will scroll, and a scrollbar may be visible depending on your OS and settings
> Remove scrollbar from popover when not required

- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/data/bundled/extension-config.json
- shared/data/etags.json
> Prepare release 2022.8.25

- integration-test/background/grades.js
> Fix reddit grading test

- package-lock.json
- package.json
> Update ddg2dnr dependency

- shared/js/background/startup.es6.js
- shared/js/background/tab-manager.es6.js
- On service worker restart we'll restore the tab state
- On update/install we create the tab objects fresh
**Reviewer:**
Recreates tab objects on startup when in the install case.
https://app.asana.com/0/892838074342800/1203142444460376/f
> Recreate tab objects when extension installed.

- shared/js/background/load.es6.js
> Fix url logging in load function

- .github/workflows/beta.yml
**Reviewer:**
https://app.asana.com/0/0/1203197597853167/f
There was a typo in #1469 which broke the workflow after it was merged into develop. This PR fixes that.
> Fix errors in beta workflow script

- browsers/chrome-mv3/manifest.json
- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- shared/data/bundled/extension-config.json
- shared/data/etags.json
> Prepare release 2022.10.31

- shared/js/background/startup.js
> Restore tab windows

- integration-test/background/request-blocking.js
- shared/js/background/allowlisted-trackers.es6.js
- shared/js/background/before-request.es6.js
- shared/js/background/broken-site-report.js
- shared/js/background/utils.es6.js
> Strip out URL params and fix up request-blocking tests

- shared/js/shared-utils/parse-user-agent-string.es6.js
- unit-test/shared-utils/parse-user-agent-string.es6.js
**Reviewer:**
We're wrongly detecting Opera which means we're not reporting this correctly to SERP.
https://app.asana.com/0/892838074342800/1203304923320764/f
> Fix up Opera UA matching

- shared/js/background/broken-site-report.js
**Reviewer:**
https://app.asana.com/0/0/1203228346742712/f
Reverting this change as we are not able to use it on the backend.
> Revert MV3 in breakage reports

- .github/workflows/beta.yml
**Reviewer:**
I caused a regression in the beta workflow when I renamed the beta zip in #1504. Here's the fix.
> Update mv3 release path

- integration-test/background/storage.js
- integration-test/content-scripts/gpc.js
- integration-test/data/configs/storage-blocking.json
- integration-test/helpers/harness.js
**Reviewer:**
- Update existing assertions to match new cookie names since https://github.com/duckduckgo/privacy-test-pages/pull/109
- Add new assertions for new tests added in test page changes.
> Update storage tests for updated test page

- shared/js/background/before-request.es6.js
- shared/js/background/events.es6.js
Issue on new tabs not being restored.
https://app.asana.com/0/892838074342800/1203403425387521/f
> Create tab object on tab create

- shared/js/background/message-handlers.js
`setList` was removed by mistake - it's used on the options page.
> fix: re-instate setList message

- package-lock.json
- package.json
- shared/js/background/classes/privacy-dashboard-data.js
https://app.asana.com/0/892838074342800/1203466326045183/f
The dashboard was requiring a field that is actually optional/not used
Dashboard PR: https://github.com/duckduckgo/privacy-dashboard/pull/13
> fix: only rely on 'nextAlias' for email data

- integration-test/background/click-to-load-youtube.js
- integration-test/data/configs/click-to-load-youtube.json
- shared/js/background/broken-site-report.js
- shared/js/background/classes/tab-state.js
- shared/js/background/classes/tab.es6.js
- shared/js/background/message-handlers.js
- shared/js/background/wrapper.es6.js
- shared/js/ui/templates/privacy-options.es6.js
- unit-test/background/classes/tab.es6.js
https://app.asana.com/0/0/1203325458386638/f
**Reviewer:**
> YouTube CTL part 2 - migration

- package-lock.json
- package.json
https://app.asana.com/0/892838074342800/1203485905915294/f
Includes a bump to `1.1.1`
https://github.com/duckduckgo/privacy-dashboard/releases/tag/1.1.0
https://github.com/duckduckgo/privacy-dashboard/releases/tag/1.1.1
The notable fixes for the extension are:
- fix(extension): fix search on MV3 by @shakyShane in https://github.com/duckduckgo/privacy-dashboard/pull/15
- fix(all): display name when entityName matches eTLD+1 by @shakyShane in https://github.com/duckduckgo/privacy-dashboard/pull/16
- fix(extensions): use chrome.i18n for language selection by @shakyShane in https://github.com/duckduckgo/privacy-dashboard/pull/17
1. ensure search works on MV3
2. change language on an OS level, restart the browser and then ensure the Dashboard is translated
> bump privacy dashboard for MV3 fixes

- .github/workflows/release.yml
For custom branch releases manually through workflow.
**Reviewer:**
> Allow workflow release processing

- package-lock.json
- package.json
> update content scope scripts ver

- shared/js/background/events.es6.js
**Reviewer:**
I moved the ATB update so that it will run for all onInstall events. This seems safer since we don't know exactly how upgrading to MV3 works.
> move atb to run on all install events

- shared/data/bundled/extension-config.json
- shared/data/etags.json
- unit-test/background/classes/tab.es6.js
We just turned on a new feature in the config, which caused this test to start failing.
> Fix test that depends on the number of enabled features in the config

- shared/data/constants.js
Fixes an error in MV3 when setting the action icon to a relative path.
> Fix: MV3 error setting a badge with a relative path.

- package-lock.json
- package.json
1. Build and install the MV2 extension (Firefox and Chrome).
1. Navigate to https://yelp.com/login
2. Click "Continue with Facebook"
3.  Click "Log in"
4. Ensure the Facebook popup window loads correctly and works
Note: There is a known issue where the popup will open twice, one being left empty. That is not a regression.
1. Navigate to https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/
2. Ensure Facebook content is blocked and replaced with placeholders
3. Ensure that clicking to unblock the content works correctly
1. Navigate to http://privacy-test-pages.glitch.me/privacy-protections/youtube-click-to-load/
2. Ensure that the YouTube content _isn't_ blocked, placeholders _aren't_ displayed and that the videos work correctly.
> Update the content-scope-scripts dependency

- .github/workflows/checks.yml
- .gitignore
- Makefile
- browsers/chrome-mv3/manifest.json
- integration-test/background/test-fingerprint.js
- integration-test/config-mv3.json
- package-lock.json
- package.json
- shared/js/background/classes/https-redirects.es6.js
- shared/js/background/declarative-net-request.js
- shared/js/background/https-service.es6.js
- shared/js/background/https.es6.js
**Reviewer:**
Smarter encryption for MV3:
- Fetch SE domain list at build time, convert it into DNR rules, then bundle that file with the build.
- When we detect a redirect loop, create a session rule to disable upgrades for that domain.
- For upgrades beyond the static DNR rule list, generate session upgrade rules when we get an upgrade hit from the SE API.
- Update SE API caching for MV3, using session storage.
Depends on https://github.com/duckduckgo/ddg2dnr/pull/68
Upgrades: http://privacy-test-pages.glitch.me/privacy-protections/https-upgrades/
Loop protection: https://privacy-test-pages.glitch.me/privacy-protections/https-loop-protection/
> MV3 Smarter encryption

- integration-test/background/atb.js
- shared/html/options.html
- shared/js/background/atb.es6.js
[Asana link](https://app.asana.com/0/72649045549333/1203703426683115/f)
**Reviewer:** TBD
As part of [O-10](https://app.asana.com/0/72649045549333/1203096262469803/f), we're redesigning and shipping a new post-install page which lives on a new URL `/extension-success`.
This PR replaces all `/app?post=1` (current post-install page) instances with the new one.
> Redirect to new post-install page

- integration-test/data/configs/click-to-load-youtube.json
- package-lock.json
- package.json
- shared/data/constants.js
Now that the rule matching code in privacy-grade has been updated to
properly ignore unsupported rule actions, it should be safe to switch
back to the v4 block list again. That is necessary to get Click to
Load working for MV3 builds again, and is the next step towards
removing the legacy social_ctp_configuration.json[1] configuration
file.
Note: We also needed to fix the Click to Load YouTube test
configuration, that was missing the surrogate script entry. It
turned out that this was working by accident using the v4 block
list actions in the test block list file.
1 - https://staticcdn.duckduckgo.com/useragents/social_ctp_configuration.json
**CC:** @ladamski 
MV2:
1. Check that Facebook Click to Load works correctly ([see the test …
> Start using the v4 block list again

- package-lock.json
- package.json
- shared/js/background/classes/custom-rules-manager.js
- shared/js/background/declarative-net-request.js
> Update the ddg2dnr dependency

- integration-test/background/test-fingerprint.js
**Reviewer:**
The MV3 Smarter Encryption now upgrades example.com via a navigation (rather than a redirect), which was breaking tests. This PR changes the protocol of the test page to https to prevent that and make the tests more reliable.
> Use secure page to avoid SE upgrade breaking the test.

- unit-test/background/classes/tab.es6.js
- unit-test/data/extension-config.json
**Reviewer:**
Use the unit-test extension config for tab serialization tests. Prevents failures when the bundled extension config is updated (e.g. on version bump).
---
- https://app.asana.com/0/0/1203865378831021
> Use static test config for tab unit-tests

- scripts/asana-release.js
**Reviewer:**
- Upload MV3 build to Asana release task.
- Suppress Asana API warnings.
---
- https://app.asana.com/0/0/1203887651923636
> Asana automation updates

- .github/workflows/asana.yml
**Reviewer:**
Adds a new workflow that adds and updates PR tasks in Asana.
Unfortunately, `pull_request_target` actions only start working after they get merged into the main branch, so we can't test this ahead of time.
---
- https://app.asana.com/0/0/1203910934070539
> Add action to sync open pull requests to Asana

- README.md
> Update CI check URL

- integration-test/background/click-to-load-youtube.js
**Reviewer:**
This test is failing about 50% of the time. We should disable it until we move forward with shipping this feature.
> Disable Youtube CTL test

- integration-test/background/privacy-dashboard.js
- integration-test/background/request-blocking.js
- integration-test/data/configs/serviceworker-blocking.json
- shared/js/background/before-request.es6.js
- shared/js/background/classes/sw-tab.es6.js
- shared/js/background/classes/tab.es6.js
- shared/js/background/declarative-net-request.js
- shared/js/background/events/referrer-trimming.js
- shared/js/background/tab-manager.es6.js
- shared/js/devtools/panel.es6.js
- unit-test/background/declarative-net-request.js
**Reviewer:**
---
- https://app.asana.com/0/0/1203879775591697
> Re-enable serviceworker blocking

- integration-test/background/atb.js
- shared/js/background/atb.es6.js
**Reviewer:**
After updating the post-install page with ATB parameter is appended with `&`. This should be `?` to create a valid URL.
> Correct post install pathname

- scripts/asana-release.js
**Reviewer:**
I didn't test #1681 well enough, and it failed in https://github.com/duckduckgo/duckduckgo-privacy-extension/actions/runs/4186630432. I tested this time by running locally to create the tasks that the broken run should have.
> Fix Asana release script.

- browsers/chrome-mv3/manifest.json
- browsers/chrome/manifest.json
- unit-test/background/newtab-tracker-stats.js
https://app.asana.com/0/0/1204021159411581/f
---
- https://app.asana.com/0/0/1204021159411581
> add CSP to allow framing in our domains

- integration-test/atb.spec.js
https://app.asana.com/0/892838074342800/1204087381449376/f
> Skip flaky atb test

- shared/js/background/atb.js
- unit-test/background/atb.js
https://app.asana.com/0/0/1204096480297395/f
Visit - `https://duckduckgo.com/chrome_newtab?ntp_test`
Should be redirected to `https://duckduckgo.com/chrome_newtab?ntp_test=&atb=v367-1`
> Add ATB to /chrome_newtab

- browsers/firefox/manifest.json
> Add default_locale to Firefox

- .github/workflows/checks.yml
This should help us catch cases where the build gets broken on a specific platform.
> Run build checks on multiple OSes

- Makefile
- Ensure the SOURCE_FILES variable includes node_modules/@duckduckgo/*
packages, even when they are symlinked for development.
- Ensure .git/ and node_modules/ subdirectories of symlinked
node_modules/@duckduckgo/* packages aren't included.
- Check node_modules/@duckduckgo/ exists, before looking for its
files. Otherwise, `make clean` fails when node_modules/ is empty.
- Avoid watching Emacs temporary files (files ending with "~") in
SOURCE_FILES or the other similar file lists.
- Have content-scope-scripts rebuild automatically on source change,
but only when the dependency is symlinked (when .git/) exists. That
is important, since it turns out that the content-scope-scripts
releases can contain source files that are newer than the included
build files - we want to use the released build …
> Improve Makefile handling of locally linked copies of our repositories

- Makefile
For builds, the Makefile first copies a bunch of files and then builds
some more. For the file copying we used rsync, with the --delete
option. That ended up being problematic, since sometimes the built
files could be deleted by rsync.
While we're at it, let's add/fix some comments and add a few missing
.PHONY dependencies.
**Depends on:**
> Stop passing --delete to rsync in Makefile and more tidy up

- integration-test/privacy-dashboard.spec.js
Simple migration of the dashboard integration test to Playwright.
> Migrate privacy dashboard tests to playwright

- integration-test/url-parameters.spec.js
Simple port of url-parameter tests to playwright.
> Migrate URL parameters test to playwright

- shared/js/background/broken-site-report.js
- shared/js/background/message-handlers.js
- unit-test/background/reference-tests/broken-site-reporting-tests.js
**Reviewer:**
Adds improved broken site debugging reporting for URLs that exist on the page. This assists with debugging the runtimeChecks feature.
https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/1842
> Breakage reporting tweaks

- browsers/chrome-mv3/manifest.json
- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
Enables running autofill in iframes created in unconventional ways, namely 
**Iframe created using a `blob:` scheme. PoC: https://gravida.pro/ddg/blob-test.html (box on the left)**
- Chrome: doesn't work
- Chrome mv3: works with [`match_origin_as_fallback: true`](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#injecting-in-related-frames)
- Firefox: works out of the box
**Iframe populated using `document.write` within the iframe. PoC: https://gravida.pro/ddg/blob-test.html (box on the right)**
- Chrome: works with `match_about_blank`
- Chrome mv3: works with [`match_origin_as_fallback: true`](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#injecting-in-related-frames)
- Firefox: works out of the box
**Iframe created …
> Run autofill in unconventional iframes

- shared/js/background/before-request.js
See https://app.asana.com/0/892838074342800/1204299256427920/f we're currently not using this code in C-S-S so let's remove unless we need it again.
> Remove tracker definition code as currently unused

- integration-test/click-to-load-youtube.spec.js
- integration-test/config-mv3.json
- integration-test/config.json
- integration-test/helpers/pageWait.js
Move the Click to Load YouTube integration tests over to Playwright.
Note: Some of the tests are disabled until the remaining
content-scope-scripts changes land.
**CC:** @franfaccin
> Port YouTube Click to Load integration tests to Playwright

- Makefile
If the package.json file in content-scope-scripts has been altered,
take care to reinstall its Node.js dependencies automatically.
**CC:** @jonathanKingston 
1. Clone content-scope-scripts somewhere and check out revision https://github.com/duckduckgo/content-scope-scripts/commit/8004fca6dd18cc02c7b223b98bd2fa758eca9f45
2. (Ensure content-scope-scripts/node_modules does not exist, delete it if you didn't use a fresh clone.)
3. Run `make clean` and `rm -rf node-modules` in the extension directory.
4. Edit package.json for the extension, so that the content-scope-scripts dependency points to your copy from step 1.
5. Run `npm install` in the extension directory.
6. Run `npm run dev-chrome` and ensure the extension is only build once + it took care to run `npm …
> Ensure content-scope-scripts node_modules are up to date

- package-lock.json
- package.json
**Reviewer:**
Adding this purely to hopefully fix: https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/1869
> Add in immutable-json-patch to fix build

- package-lock.json
- package.json
Reverts duckduckgo/duckduckgo-privacy-extension#1879
Solved this issue with #1881
> Revert "Add in immutable-json-patch to fix build"

- package-lock.json
- package.json
- unit-test/background/reference-tests/3p-cookies-tests.js
- unit-test/background/reference-tests/expire-1p-tracking-cookies.js
- unit-test/background/reference-tests/fingerprinting-protection-tests.js
- unit-test/background/reference-tests/gpc-tests.js
- unit-test/background/reference-tests/referrer-trimming-tests.js
**Reviewer:**
Fixes up the test integration into C-S-S.
- This was always going to be brittle; ideally these tests should really do a full integration and pass the config instead rather than pierce through to distinct parts of files.
- I've removed the small limit on dependabot that would have allowed us to catch this issue much faster.
> Update css tests

- package-lock.json
- package.json
**Reviewer:**
Bumps the release to use the 3 digit number and also installs the new dependency.
> Update C-S-S to 4.11.1

- integration-test/helpers/pageWait.js
- integration-test/legacy/click-attribution.js
**Reviewer:**
Prevents allowing of timeouts of these tests.
> Prevent timeout carveout for click attr tests

- shared/js/background/helpers/arguments-object.js
https://app.asana.com/0/892838074342800/1204420978843329/f trim out large data object that's not needed in the arguments object.
> Trim trackerAllowlist from arguments object

- shared/html/devtools-panel.html
- shared/js/devtools/panel.js
**Reviewer:** @GuiltyDolphin @sammacbeth 
- Replaced canvas debugging with a generic proxy debugging which is off by default.
- Added another row for runtimeChecks as it goes through proxies but also only 'matters' once it matches and starts interrogating.
- Depends on https://github.com/duckduckgo/content-scope-scripts/pull/440
Existing:
Default view:
Filtering examples:
> Proxy debugging

- shared/html/devtools-panel.html
- shared/js/devtools/panel.js
**Depends on:** https://github.com/duckduckgo/content-scope-scripts/pull/449
- Allows for e.error's that have an optional error.
- Also added toggles to filter them.
> Allow for filtering of exceptions and optionality of m.stack

- integration-test/data/configs/storage-blocking.json
- integration-test/storage-blocking.spec.js
- package-lock.json
- package.json
Requires:
https://github.com/duckduckgo/privacy-test-pages/pull/158
**Reviewer:**
> Validate that third party trackers load correctly

- browsers/chrome-mv3/manifest.json
- browsers/chrome/manifest.json
- browsers/firefox/manifest.json
- integration-test/data/configs/fingerprint-protection.json
- integration-test/data/staticcdn/trackerblocking/config/v2/extension-chrome-config.json
- integration-test/data/staticcdn/trackerblocking/config/v2/extension-chromemv3-config.json
- integration-test/fingerprint-protection.spec.js
- integration-test/gpc.spec.js
- integration-test/helpers/playwrightHarness.js
- integration-test/helpers/testPages.js
- integration-test/navigator-interface.spec.js
- integration-test/request-blocking.spec.js
- integration-test/storage-blocking.spec.js
- shared/data/bundled/extension-config.json
- shared/data/etags.json
- shared/js/background/amp-protection.js
- shared/js/background/classes/site.js
- shared/js/background/classes/tab.js
- shared/js/background/events/privacy-icon-indicator.js
- shared/js/background/script-injection.js
- shared/js/background/url-parameters.js
- unit-test/background/classes/site.js
- unit-test/background/reference-tests/amp-protection-tests.js
- unit-test/background/reference-tests/gpc-tests.js
- unit-test/background/reference-tests/privacy-configuration-tests.js
- unit-test/background/reference-tests/url-parameters-tests.js
**Reviewer:**
Ensure protections are fully disabled on localhost.
> Disable all protections for 'special' pages (e.g. localhost)

- shared/data/constants.js
**Reviewer:**
Updated the blocklist endpoint to a platform specific one. 
https://app.asana.com/0/11472677167855/1204602434877142
> update blocklist endpoints

- shared/js/background/classes/tracker-stats.js
- shared/js/background/devbuild.js
- shared/js/background/newtab-tracker-stats-debug.js
- shared/js/background/newtab-tracker-stats.js
- shared/js/background/startup.js
- unit-test/background/classes/tracker-stats.js
- unit-test/background/newtab-tracker-stats.js
**Reviewer:**
https://app.asana.com/0/0/1204520818036826/f
**Before**
Stats were collected for a rolling 1-hour time period - we stored timestamps
against company names so that we could evict old entries every 5 minutes.
`chrome.storage.local` data looked like this:
```json
{
"trackerStats": {
"totalCount": 4,
"entries": {
"Google": [1673438914778],
"Facebook": [1673438914778, 1673438914778, 1673438914792]
}
}
}
```
This worked well for 1 hr windows because even with thousands of entries the data did not grow too large.
The desired change to 24hr means this storage mechanism is no-longer appropriate - it grows too large
and at about 250,000 entries it exhausts `chrome.storage.local`
Because we don't need the granularity anymore, we can move to just storing packs of aggregated data instead …
> increase newtab stats to 24hr

- shared/js/background/newtab-tracker-stats.js
- shared/js/newtab/schema.js
- unit-test/background/newtab-tracker-stats.js
Just updating a string value that can be used by any UI
1. This value wasn't used yet, so the unit tests are enough here.
> update 'trackerCompaniesPeriod' to last-day

- shared/js/background/newtab-tracker-stats.js
- shared/js/newtab/schema.js
- unit-test/background/newtab-tracker-stats.js
Reverts duckduckgo/duckduckgo-privacy-extension#2019
> Revert "update 'trackerCompaniesPeriod' to last-day"

- shared/js/background/utils.js
- unit-test/background/utils.js
https://app.asana.com/0/892838074342800/1204816108720031/f
> Parse arbitary version strings for comparison

- shared/js/background/classes/tracker-stats.js
- shared/js/background/devbuild.js
- shared/js/background/newtab-tracker-stats-debug.js
- shared/js/background/newtab-tracker-stats.js
- shared/js/background/startup.js
- shared/js/newtab/schema.js
- unit-test/background/classes/tracker-stats.js
- unit-test/background/newtab-tracker-stats.js
https://app.asana.com/0/312629933896096/1204823706069784/f
This is identical to what we already merged in the past.
We reverted it for other reasons, (noted in the Asana task) - but now it's ready to be released
---
- https://app.asana.com/0/0/1204823706069784
> increase newtab stats to 24hr (2nd time)

- shared/js/devtools/panel.js
**Reviewer:** @GuiltyDolphin 
Fixes a bug where we were not hiding jsExceptions and also allows for filtering based on all fields.
> Improve debug panel filtering for all cells and also fixing hiding of exceptions

- integration-test/data/configs/fingerprint-protection.json
- integration-test/test-canvas.spec.js
- package-lock.json
- package.json
> Use local config for canvas tests.

- package-lock.json
- package.json
> Bump @duckduckgo/content-scope-scripts to 4.24.0

- CONTRIBUTING.md
**Reviewer:**
PR simply updates the link to the browser extensions integration page which was moved.
> fix: update link to the browser extensions integration page

- .eslintrc
- shared/js/background/devbuild-reloader.js
- shared/js/background/devbuild.js
- shared/js/background/dnr-config-rulesets.js
- shared/js/background/dnr-session-rule-id.js
- shared/js/background/events/privacy-icon-indicator.js
- shared/js/background/newtab-tracker-stats.js
- shared/js/background/tracker-utils.js
- shared/js/background/utils.js
- shared/js/newtab/newtab.js
- unit-test/legacy/declarative-net-request.js
**Reviewer:**
Removes warnings for import * and replaces it with an error to ensure we never do this again.
Ignores one test file that is painful to fix and needs a rewrite anyway.
> Remove * import warnings

- package-lock.json
- package.json
- shared/js/background/helpers/arguments-object.js
- unit-test/background/reference-tests/referrer-trimming-tests.js
**Reviewer:** @muodov 
Fixing up issue caused in the latest C-S-S referrer changes. This is largely fixing the test itself that is very coupled with the integration too much.
However we needed to disable the feature in the arguments object based on checking the referrer of the tab when it's safelisted. This was an actual bug with preventing us to disable the feature.
https://app.asana.com/0/312629933896096/1205182548153047/f
> Referrer cleanup and test fixes to merge latest C-S-S

- integration-test/atb.spec.js
- shared/js/background/atb.js
- unit-test/background/atb.js
> Make chrome counteract message experiment English only and non Linux

- shared/js/background/newtab-tracker-stats.js
- shared/js/background/startup.js
- shared/js/newtab/schema.js
- unit-test/background/newtab-tracker-stats.js
**Reviewer:**
https://app.asana.com/0/892838074342800/1205240789426967/f
---
- https://app.asana.com/0/0/1205240789426967
> add ATB to NTP data (in addition to URL redirect)

- package-lock.json
Reverts duckduckgo/duckduckgo-privacy-extension#2177
Reverting as it's breaking the build due to the following error:
`SyntaxError: Cannot use import statement outside a module`
Without transpilation we can't fix this issue I don't think.
> Revert "Bump asana from `d90978a` to `4fa104a`"

- shared/js/background/features/fire-button.js
> Remove fire button pixel

- integration-test/README.md
- integration-test/amp-protection.spec.js
- integration-test/click-to-load-facebook.spec.js
- integration-test/click-to-load-youtube.spec.js
- integration-test/data/staticcdn/trackerblocking/config/v2/extension-chrome-config.json
- integration-test/data/staticcdn/trackerblocking/config/v2/extension-chromemv3-config.json
- integration-test/facebook-sdk-schema.spec.js
- integration-test/fire-button.spec.js
- integration-test/helpers/testPages.js
- integration-test/navigator-interface.spec.js
- integration-test/privacy-dashboard.spec.js
- integration-test/request-blocking.spec.js
- integration-test/storage-blocking.spec.js
- integration-test/url-parameters.spec.js
- integration-test/youtube-sdk-schema.spec.js
- package.json
- packages/ddg2dnr/test/smarterEncryption.js
Replace occurrences of `privacy-test-pages.glitch.me` with `privacy-test-pages.site`.
> Move test pages off glitch.

- shared/js/background/broken-site-report.js
- shared/js/background/classes/tab-state.js
- shared/js/background/classes/tab.js
- shared/js/background/components/tab-tracking.js
- shared/js/background/events.js
- unit-test/background/classes/tab.js
To assist with triaging breakage, we'd like to know the status code and error state the user is when they report a broken website.
https://app.asana.com/0/0/1205738910117298/f
> Add site breakage reasons to reports.

- package-lock.json
- unit-test/background/reference-tests/broken-site-reporting-tests.js
**Reviewer:**
Updated the test code to support 
- https://github.com/duckduckgo/privacy-reference-tests/pull/112
n/a
> adding support in reference tests for protectionsState

- shared/js/background/broken-site-report.js
**Reviewer:**
https://app.asana.com/0/1201602070177732/1205869658195882/f
Ensure the `ampUrl` parameter is properly encoded in breakage forms
1. Go to https://privacy-test-pages.site/privacy-protections/amp/
2. Click through one of the simple AMP links
3. Submit a breakage report and ensure there are no issues.
> Ensure ampUrl is correctly encoded

- package-lock.json
- package.json
https://app.asana.com/0/0/1205883650709863/f
- tapping on 'website not working?' should reveal the breakage form as normal
> Moving the protections toggle on primary screen

- shared/html/devtools-panel.html
- shared/js/devtools/panel.js
**Reviewer:**
@sammacbeth 
**CC:**
@GuiltyDolphin @jonathanKingston 
The current devtools panel is functional, but to make it easier to use should have a better UI.
This PR uses the existing extension styles (in base.css) and triggers page reload when protections are toggled, to save clicks.
See internal task: https://app.asana.com/0/0/1206280121954708/f
Once built, open `devtools-panel.html`
Check that the page layout is not broken.
Check that the buttons still work, and that protection buttons also trigger a page reload.
> Update devtools panel with improved UI

- .github/workflows/asana.yml
Updating Github-asana sync to incorporate new features from https://github.com/sammacbeth/action-asana-sync/pull/98
> Asana sync changes

- integration-test/data/staticcdn/trackerblocking/config/v4/extension-chromemv3-config.json
- integration-test/helpers/backgroundWait.js
- integration-test/request-blocking.spec.js
- integration-test/storage-blocking.spec.js
- shared/js/background/background.js
- shared/js/background/components/resource-loader.js
- shared/js/background/components/tds.js
- shared/js/background/components/trackers.js
- shared/js/background/dnr-config-rulesets.js
- shared/js/background/events.js
- shared/js/background/message-handlers.js
- shared/js/background/startup.js
- shared/js/background/storage/tds.js
- unit-test/background/resource-loader.js
- unit-test/helpers/tds.js
Simplifies the loading of blocklists and config.
> Refactor TDS list loading

- shared/js/background/components/resource-loader.js
Our CDN is currently serving `cache-control: no-cache`, so we can't rely that the browser will cache these requests for us. With a small tweak we can send the `If-None-Match` header manually and handle the 304 server response.
1. Load the extention and open the background page.
2. Run `components.tds.config.checkForUpdates(true)` to trigger a fetch to the CDN. This should include `If-None-Match` and get a 304 response. 
3. Check that the loader will refetch if the etag changes, but running `chrome.storage.local.clear()` to reset stored etags, then reloading the extension.
4. Check that the loader can still load the resource if the cached data is missing, by running `await indexedDB.deleteDatabase('tdsStorage')` then reloading the extension.
> Implement manual resource caching.

- shared/js/background/components/email-autofill.js
> Fix regex for checking private address format

- shared/js/background/background.js
- shared/js/background/components/debugger-connection.js
- shared/js/background/components/devtools.js
- shared/js/background/components/resource-loader.js
- shared/js/background/components/tab-tracking.js
- shared/js/background/devtools.js
- shared/js/background/events.js
- shared/js/background/utils.js
- shared/js/devtools/panel.js
The devtools-panel.html page is for testing disabling/enabling
certain privacy protections, to help debug website
issues. Unfortunately the page did not work yet for Chrome MV3 builds,
let's fix that here. Since some refactoring is required anyway, let's
tidy things up a bit at the same time.
Some of the main changes:
- Instead of messing with the extension's (MV2) state of the various
privacy protections directly, we must now update the underlying
configurations. That way the MV2 state for those features updates
automatically and the MV3 decarativeNetRequest rules are also
regenerated as necessary.
- To access the ResourceLoader instances necessary for that, the
devtools code needs to be split out into the Devtools component.
- Instead of reloading pages right away after toggling …
> Refactor the devtools code, fixing Chrome MV3 support

- shared/js/background/classes/tab-state.js
- shared/js/background/i18n.js
- unit-test/background/classes/tab.js
- unit-test/background/reference-tests/broken-site-reporting-tests.js
https://app.asana.com/0/0/1207738418014187/f
Include country code when sending broken site report locale.
> Update broken site locale to include country

- package-lock.json
- package.json
- unit-test/background/atb.js
- unit-test/inject-chrome-shim.js
Some small tweaks to the unit tests were required to get them passing
again.
> Update jasmine dependency to 5.2.0

- package-lock.json
- package.json
- shared/js/background/classes/top-blocked.js
The latest TS introduced some type errors in legacy code. This PR modernizes that code so the errors are fixed.
> Bump TS to 5.6.3

- .git-blame-ignore-revs
**Reviewer:**
https://app.asana.com/0/1201203727797217/1208561434802767/f
> Ignore lint commits during git blame

- package-lock.json
- package.json
- shared/js/devtools/panel.js
- unit-test/background/reference-tests/gpc-tests.js
- unit-test/background/reference-tests/referrer-trimming-tests.js
- unit-test/node/reference-tests/3p-cookies-tests.js
- unit-test/node/reference-tests/expire-1p-tracking-cookies.js
- unit-test/node/reference-tests/fingerprinting-protection-tests.js
- unit-test/node/reference-tests/privacy-configuration-tests.js
**Reviewer:** @kzar / @sammacbeth 
Resolves the issues with: https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/2807 with: https://github.com/duckduckgo/content-scope-scripts/pull/1222
Tests should pass...
> Update C-S-S to 6.34.0

- .github/workflows/privacy-review.yml
**Reviewer:**
Add privacy review workflow for automated pixel triages
> Add privacy review workflow

- Makefile
- package-lock.json
- package.json
- pixel-definitions/pixels/experiments.json
- shared/html/rollouts.html
- shared/js/background/components/remote-config.js
- shared/js/background/components/resource-loader.js
- shared/js/devtools/rollouts.js
- tsconfig.json
- unit-test/background/abn-framework.js
- unit-test/background/remote-config.js
**Reviewer:**
- Handle the `cohort` option in the remote config, by randomly selecting a cohort using the provided cohort weights. (Implementation doc: https://app.asana.com/0/1208889145294658/1208680059799038/f).
- Provide an API for sub-features, upon seeing that a cohort was assigned, can trigger enrollment, which sends a pixel (https://app.asana.com/0/1208889145294658/1208747415972722/f).
- Adds a browser UI to allow rollouts and cohorts to be manually adjusted for testing purposes.
> Support for client-side A/B testing

- browsers/chrome/manifest.json
**Reviewer:** @dbajpeyi 
Move autofill resources to non-dynamic web-accessible-url to allow use from CSS
https://app.asana.com/0/892838074342800/1209596190436811
Before:
After:
1. [Visit fill.dev](https://fill.dev/form/registration-email)
2. Click the grey dax icon (for incontext signup).
> Fix: Console errors for web-accessible font resource

- .github/workflows/asana.yml
**Reviewer:**
https://app.asana.com/1/137249556945/project/1203415155983021/task/1209665807339668
- Migrate to external user map source.
- Auto-assign PR authors.
> Update asana sync action.

- .github/workflows/asana.yml
> Bump asana sync action

- pixel-definitions/ignore_params.json
- pixel-definitions/product.json
**Reviewer:**
Pixel schema changes to bump version with fix for https://app.asana.com/0/0/1209244730607066, and ignore random `scrlybrkr` param being added by a 3rd party educational proxy.
> add 'scrlybrkr' to common ignore list, bump app version

- .github/workflows/asana.yml
**Reviewer:**
https://app.asana.com/1/137249556945/project/908478224964033/task/1209670463076906
> Use org-wide PAT for asana sync action

- browsers/chrome/_locales/bg/messages.json
- browsers/chrome/_locales/cs/messages.json
- browsers/chrome/_locales/da/messages.json
- browsers/chrome/_locales/de/messages.json
- browsers/chrome/_locales/en/messages.json
- browsers/chrome/_locales/en_GB/messages.json
- browsers/chrome/_locales/es/messages.json
- browsers/chrome/_locales/et/messages.json
- browsers/chrome/_locales/fi/messages.json
- browsers/chrome/_locales/fr/messages.json
- browsers/chrome/_locales/hu/messages.json
- browsers/chrome/_locales/it/messages.json
- browsers/chrome/_locales/lt/messages.json
- browsers/chrome/_locales/lv/messages.json
- browsers/chrome/_locales/pl/messages.json
- browsers/chrome/_locales/pt_PT/messages.json
- browsers/chrome/_locales/ro/messages.json
- browsers/chrome/_locales/ru/messages.json
- browsers/chrome/_locales/sk/messages.json
- browsers/chrome/_locales/sl/messages.json
- browsers/chrome/_locales/sv/messages.json
**Reviewer:**
https://app.asana.com/1/137249556945/project/72649045549333/task/1209310057526151
> New extension name and description.

- package-lock.json
- package.json
- unit-test/background/reference-tests/gpc-tests.js
- unit-test/background/reference-tests/referrer-trimming-tests.js
- unit-test/node/reference-tests/3p-cookies-tests.js
- unit-test/node/reference-tests/expire-1p-tracking-cookies.js
- unit-test/node/reference-tests/fingerprinting-protection-tests.js
**Reviewer:** 
https://app.asana.com/0/312629933896096/1209843152695136/f
1. Updates C-S-S to 8.12.0
2. Fixes test cases to init features to the new format.
> Change lifecycle of C-S-S in reference tests

- .github/workflows/privacy-review.yml
**Reviewer:**
https://app.asana.com/0/1209184836195923/1209793117646011/f
> use "pull_request_target" in privacy review action

- .github/workflows/privacy-review.yml
**Reviewer:**
https://app.asana.com/1/137249556945/project/1209184836195923/task/1209319827754769?focus=true
> Update privacy-review dep

- .github/workflows/privacy-review.yml
**Asana task**:  https://app.asana.com/1/137249556945/task/1210024528570307?focus=true
Privacy Review task should be created upon label addition
---
- https://app.asana.com/0/0/1210024528570307
> Switch to composite workflow for privacy review

- .github/workflows/beta.yml
- .github/workflows/stage.yml
**Reviewer:**
We updated stefanzweifel/git-auto-commit-action which no longer pushes the branches.
> Push branches

- shared/js/background/classes/tab.js
- unit-test/background/classes/tab.js
**Reviewer:**
See: https://app.asana.com/1/137249556945/project/1199237043598868/task/1211044547694231
This trims out experiment data for users that have seen the experiment but aren't assigned a cohort.
> Trim experiments without a cohort from reports

- pixel-definitions/pixels/broken_site_reports.json
Adds definition for experiments as per https://app.asana.com/1/137249556945/task/1211065164045015?focus=true
> Add contentScopeExperiments pixel schema
